### ISSUE TITLE
Random sounds playing after drawing a shape to the screen

### ISSUE THREAD

**Issue by Thatguyjs** [processing/p5.js-web-editor#1023]
#### Nature of issue?

- Found a bug

#### Details about the bug:

Browser: Microsoft Edge 42.17134.1.0
Browser HTML: Microsoft EdgeHTML 17.17134

Operating System: Windows 10

#### Example:

// Move the mouse
function setup() {
  createCanvas(400, 400);
}

function draw() {
  background(220);
  rect(mouseX, 0, 20, 20);
}

#### Additional Details:

 - The problem only seems to occur while drawing something to the canvas.

**Comment by catarak** [comment]
@Thatguyjs thanks for reporting! can you try turning off the accessibility features? you can do this by going to preferences (the cog icon) -> accessibility -> uncheck all of the boxes. there was a bug a few days ago that a fixed in which these were getting turned on by default, but i think it got saved to your account if you updated your preferences.

**Comment by catarak** [comment]
@Thatguyjs i actually ran a database command to reset this, so it shouldn't be an issue anymore!

**Comment by Thatguyjs** [comment]
Thanks for replying, the database command fixed it for me!
