### ISSUE TITLE
Stroke of an elements on the edge of canvas gets cut by half

### ISSUE THREAD

**Issue by kshivanku** [processing/p5.js-web-editor#105]
Hi,

If you draw a rectangle at (0,0) with some strokeWeight, the left and top edge of the rectangle has less stroke (looks like half the value of strokeWeight). Don't know why that is the case.

Screenshot:
<img width="1280" alt="screen shot 2016-09-18 at 11 46 26 am" src="https://cloud.githubusercontent.com/assets/12475379/18617145/03b0ac8e-7d97-11e6-93e7-51f116a4c8ce.png">

**Comment by shiffman** [comment]
I took a look at your code and indeed see the same effect!  I checked and this is not a bug with the editor, but rather is just something related to the way p5.js works.  You could file it at https://github.com/processing/p5.js/issues if you like. However, I think this is by design (though it causes a strange effect here).  The strokeWeight thickness extends out from the center of the line and since the line is centered around (0,0) it extends off the page.
