### ISSUE TITLE
Add a profile photo with the username

### ISSUE THREAD

**Issue by nik72619c** [processing/p5.js-web-editor#1079]
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:
Right now, there's only the username which is showed in the app which seems to be a bit monotonous to me. I think an addition of a profile picture / avatar should be added.

@catarak please guide me with this

**Comment by catarak** [comment]
thanks for the feature suggestion! this is low priority—since there is currently not even a profile page, i'd want to step back and think about what this page should look like, and what would be important to put on there. at the very least, a user's sketches and, when it's developed, a user's collections!

**Comment by nik72619c** [comment]
okay cool! Please do let me know how this would be designed. would love to build this feature. :)
