### ISSUE TITLE
Linked js files are not downloaded from sketch

### ISSUE THREAD

**Issue by awarua** [processing/p5.js-web-editor#1099]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

Chrome
MacOSX

- Steps to reproduce this bug:
  - Open the following sketch: https://editor.p5js.org/creativecoding/sketches/ObakvEt8C
    - The sketch contains several javascript files (cookie.js, spaceshipParts.js, etc.)
  - Click 'download' from the 'file' menu
  - The zip will download. Unzip it. It does not contain all javascript files. It only contains the p5js library files and sketch.js

**Comment by catarak** [comment]
thanks for reporting! i think this issue here is that the files (`cookie.js`, `spaceshipParts.js`, etc) are technically of type `folder`. the bigger issue is that users shouldn't be able to add text content to a folder, nor should a folder be able to have an extension. i think there's an open pr with respect to the former.

**Comment by catarak** [comment]
i just pushed a fix that will prevent users from adding text content to folders. however, this will break your sketch, so I made a copy of it that will work: https://editor.p5js.org/cassie/sketches/Id2Uu66Fz you'll need to duplicate this to get back your original!

**Comment by awarua** [comment]
Thank you so much Cassie!
