### ISSUE TITLE
Add folder button is not functioning properly

### ISSUE THREAD

**Issue by plxity** [processing/p5.js-web-editor#1139]
#### Nature of issue?

- Found a bug

#### Details about the bug: 
![Capture](https://user-images.githubusercontent.com/28510494/63462996-cf543500-c479-11e9-8023-cb46a1e708b4.PNG)
![Capture1](https://user-images.githubusercontent.com/28510494/63463011-d5e2ac80-c479-11e9-9593-23926380c74d.PNG)

- Web browser and version: Chrome
- Operating System: Windows
- Steps to reproduce this bug:

#### Feature enhancement details:
Hover effect is missing in 'Add Folder' missing. Secondly, It does not display an error when the text field is empty and the button is pressed. For reference, It should work exactly like the 'Add File' button.

I would like to work on this.
#### New feature details:

**Comment by catarak** [comment]
thanks for making this issue! i am able to get the error to appear, but it's confusing because the functionality between the two forms is slightly different:
- when a user clicks "new file", the focus is placed on the input field. when the user then tries to click on the "add file" button, the error appears because the input has been blurred. 
- when a user clicks on "new folder", the focus is not placed on the input field. because the input field is empty, the "add folder" button is disabled. 

both of these behaviors "work" (they prevent the user from entering an empty file or folder name) but in different ways, and i agree, the flow should be the same.
