### ISSUE TITLE
saveStrings() to have the option to store/update in webEditor

### ISSUE THREAD

**Issue by ChristianPretorius** [processing/p5.js-web-editor#1154]
#### Nature of issue?

- Existing feature enhancement / New feature request

#### Feature enhancement details: / New feature details:
Using the web editor, I can upload a .txt file to my sketch files by manually adding it from my computer, I can access it with the loadStrings() function, but I have no way of updating the values in the .txt file. saveStrings() saves the file to my downloads folder, which I understand has it's usefulness in certain cases. Is there a way to save/update the original .txt file that was uploaded to my sketch files? If not, is it possible that we can add an optional command to saveStrings() method to change the directory to where we're saving to?

**Comment by catarak** [comment]
thanks for creating this issue! this is super interesting to think about. i think the functionality of `saveStrings` should be consistent inside of and outside of the context of the web editor, which makes saving it to your downloads folder makes sense. it's confusing to think about because the web editor fakes a file system, but doesn't give you a lot of that functionality.

one possible solution would be to add a web editor specific function (within the p5 namespace, so it would be like creating a p5 library). i don't know what would be a good name, and there's an edge cases to think about as well:
-  what happens if the string is super long, and holding it in memory would slow down/crash the editor? this is handled in the web editor by uploading super long text files to s3. 

this concept has come up before in the context of `saveFrames()` (#86). very open to ideas and dreams.

**Comment by ChristianPretorius** [comment]
Thanks for the response. I didn't think about the importance of consistency regarding inside/outside context of the web editor, considering that the downloads folder makes most sense.

I don't really understand how the web editor is creating the file system, where can I learn more about how this works?

Right now I am creating a game with a leaderboard.txt file that saves the positions of the top 5 players. Whenever the game is saved, it creates a new leaderboard.txt file that I then save to my desktop, which I then manually upload again to the file system and delete the old folder.

Is there any way that I could even automate this step? I am still a novice so apologies if this is the wrong forum to be asking these questions.

Thanks for your response and everything you've done for this project. Very cool :)

PS. Here's a link to my [project](https://editor.p5js.org/ChristianPretorius/full/3fMyE4M2w)

**Comment by catarak** [comment]
okay, interesting! sketches right now are 100% front end (contrasted with an app like Glitch that has server side and client side code) and therefore there's no concept of stored data. one way of handling this short term would be to integrate with a separate database/api service (like firebase?).

**Comment by ChristianPretorius** [comment]
awesome, I'll look into that. Thanks a lot!
