### ISSUE TITLE
Hosting Instance of web editor 

### ISSUE THREAD

**Issue by leonardof131** [processing/p5.js-web-editor#1156]
So I was redirected here from this forum post: https://discourse.processing.org/t/helping-a-teacher-with-the-web-editor/13822

Like I said on the forum, my name is Leo and I’m a teacher for an ONG in the favelas of Brazil that focuses in delivering STEAM education to poor children in my local region.
We’re planning to do some coding classes with them, and the easy of use of the p5.js certainly got our attention. Sadly, we cant always realy on internet access here.

We do have an internal websites with activities that students can access when the internet is down (wich is frequent occurrance). So with my very, very, veeeery limited knowledge of programming, I'm trying to make the web editor on our network. 

The main thing I want to do is have a default folder on the sidebar that has two images, one is our ONG logo and the other is the ONG mascot. So we can have an easy hello world where they can work with images.
I was able to create an default folder and show it, creating a new constant in the files.js, but I'm lost as how I can upload images.

My other question is dumb one, but I really dont know much about Js or Node. How can I host my "version" of the Web Editor ? I mean, I've been making the adjustments on the Visual Studio Code and checking it out with npm start, but I'm pretty sure thats only for testing purposes. 

I know this question is a bit different from the others around here, but seems like a good place to help me use this great tool to teach kids in a social vulnerability state, as is our job here. 

I know there’s a github for the Web Editor, but I’m quite lost on what I should do to put the editor on our website.

**Comment by catarak** [comment]
thanks for writing up this issue! recently, i've been thinking a lot about making it easier for folks to launch their own instance of the web editor, along the same lines as discourse or mastodon. right now, it's a little complicated, and i'd like to spend some time streamlining it, so that folks in your position could host their own version. i can spend some time documenting what would need to change in order to make this easier.

there is [documentation for setting up  your own instance on Heroku](https://github.com/processing/p5.js-web-editor/blob/master/developer_docs/deployment.md#self-hosting---heroku-deployment), so i recommend taking a look at that!

**Comment by simranaggarwal1999** [comment]
@catarak Hello ! I would like to contribute to the web editor. Can I contribute to this issue an could you guide me in doing so?

**Comment by pwab** [comment]
Hey @catarak was there any progress regarding this issue since your last post?

I went from [the wiki](https://github.com/processing/p5.js/wiki/Embedding-p5.js) to the [p5.js-widget](https://github.com/toolness/p5.js-widget) which seems to be exactly what I'm searching for. The widget seems to be abandoned (https://github.com/toolness/p5.js-widget/issues/77) - at least it is quite outdated.

Was any work done in the direction of making it possible to host and embed the web editor like the widget has done it?

**Comment by catarak** [comment]
Hey @pwab, unfortunately there hasn't been any progress on this! I believe what you're suggesting is different from what this issue is discussing, which is hosting your own instance of the web editor (like at a different URL). What you are suggesting is being able to embed a mini version of the web editor within a website—feel free to open a new issue!
