### ISSUE TITLE
editing setup takes two starts/stops before affecting canvas

### ISSUE THREAD

**Issue by kjhollen** [processing/p5.js-web-editor#121]
Hey there—we started using the editor in class at UCLA this week! I'll be logging a couple other little bugs, too, but everything is working great so far. :)

Noticed while showing students how to change the size of the canvas: making a change from say

``function setup() { 
  createCanvas(400, 400);
}``

to 

``function setup() { 
  createCanvas(400, 500);
}``

doesn't seem to take effect immediately when hitting the play button. But will show up if you press play again a second time. You can see the same if there's a call to background in setup: it won't update the first time but will update the second time. Changes made to draw show up the first time.

**Comment by catarak** [comment]
Just looked into this. The issue is that the preview refresh is currently throttled at 1000ms, so what's happening is that you're clicking the play button before the preview has refreshed with the new code.

I'm still figuring out what this throttling time should be, as it is related to issues such as #120 and #117.
