### ISSUE TITLE
Can't upload files with .tsv extension

### ISSUE THREAD

**Issue by trych** [processing/p5.js-web-editor#1219]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: Most recent Chrome and Firefox
- Operating System: macOS 10.13.6, but also on other macOS and Windows versions
- Steps to reproduce this bug:

Open the "Add File dialog" and drag a `.tsv` file in the dedictated drop field.
Then there is this uploading icon appearing that never disappears.

![20191126-134408_Screenshot_GoogleChrome](https://user-images.githubusercontent.com/9803905/69634580-d67b7800-1052-11ea-97af-1b972eed2eec.png)

And *only when I hover with my mouse over this icon*, then it tells me that this file type cannot be uploaded.
![20191126-134550_Screenshot_GoogleChrome](https://user-images.githubusercontent.com/9803905/69634703-12164200-1053-11ea-8d26-200d8a00ffeb.png)

But as I tried uploading via the file dialog at first, I didn't even discover this red info window at all and had no idea what was going on. (And it should be no problem to upload `.tsv` files either way.)

**Comment by catarak** [comment]
thanks for reporting! i think the culprit is [the following array](https://github.com/processing/p5.js-web-editor/blob/master/server/utils/fileUtils.js#L3) which whitelists file extensions that you can upload to the web editor. i think you can manually create a `.tsv` file, but it seems like a quick fix to be able to upload one.

**Comment by trych** [comment]
@catarak Thanks for fixing this! :)
