### ISSUE TITLE
After adding a new file modal should close

### ISSUE THREAD

**Issue by plxity** [processing/p5.js-web-editor#1227]
#### Nature of issue?

When a user adds a new file the modal does not close automatically. It should close immediately as a user clicks on add file button.

- Found a bug

#### Details about the bug: 

- Web browser and version: Chrome
- Operating System: Linux
- Steps to reproduce this bug:

**Comment by neilchauhan2** [comment]
Hi, can I try this one? I would like to solve this issue.

**Comment by RickBr0wn** [comment]
You're right, I have just replicated this locally. I'll work on this, if that is ok?

**Comment by RickBr0wn** [comment]
Looking in 'client/modules/IDE/actions/files.js', line numbers 69-71 and 91-93 have been commented out. Uncommenting them achieves the automatic closing of the modal after the file name has been entered (with no errors).

I assume they have been commented out due to the fact they conflict with something else. Any suggestions to this, or should I PR the uncommenting?

**Comment by catarak** [comment]
This modal used to close after adding a new file, but it's annoying if you're trying to upload a few files at the same. 

Ultimately, I think the solution is separating the "new file" modal to just create a new text file in the editor, and creating a new "upload file" modal (or really, when you just drag files into the editor, see #375).

**Comment by ashu8912** [comment]
Yes We can add a upload files option on sidebar and use the drag and drop feature to upload multiple files there on that modal and for adding a new file we can use that modal which closes once file is added.@catarak please share your views on this one.

**Comment by catarak** [comment]
This has been fixed by separating the "create file" and "upload file" modals.
