### ISSUE TITLE
Serious caching error with p5 Editor

### ISSUE THREAD

**Issue by everythingability** [processing/p5.js-web-editor#1234]
I can be working on a sketch, and open the Present or Full view and it doesn't reflect the changes I've made. 

I clear cache and reload... same thing... 

THEN I open a new Chrome window and open the sketch and it's a PREVIOUS version of the sketch...  Often if I save at that point I've then lost my work to an earlier version.

This has happened more than once...  don't know if it's the browser or the p5 Editor site...

**Comment by catarak** [comment]
Thanks for reporting! I have noticed this but I'm unsure how to fix it. Open to all ideas and suggestions!

**Comment by everythingability** [comment]
I have tried adding ?a=123 to the end of a URL but that only works once I've gone to the source and clicked the URLs in that (and appended a bit different)...

The REAL PROBLEM is when you return to an old tab, reload, edit and save.... argh!

**Comment by catarak** [comment]
If you do a hard refresh (shift + command/control + r), it should clear the cache! Not the best solution, but it's something.

**Comment by everythingability** [comment]
That doesn't work. Trust me.

**Comment by catarak** [comment]
got it. then I guess it's caching from the CDN. i guess possible solutions are:
- generate a unique link to the preview
- generate unique links to the included files (js, css, etc).
- ??? other methods to clear the cache

**Comment by ashu8912** [comment]
Ok So This Problem is there only till the user has not saved the sketch and has moved to a new tab one possible soultion could also be to store the current sketch that is in editing mode in localStorage that could preserve the sketch code between tab switchs
This would also take a very less amount of local storage space as we would be storing only the current sketch details in there.

**Comment by ashu8912** [comment]
Here we want to persist the cache inorder to make it more user friendly even when switching tabs.

**Comment by siddhant1** [comment]
I think the solution will be something like 
1. Cache the sketch strings in the user's browser.
2. Enable some form of cache invalidation strategy.

I would say a serviceWorker can do this job, cache the current files   and invalidate the cache as we save the files

**Comment by ashu8912** [comment]
Ok So The Browser is caching things will see what all is caching things

**Comment by ashu8912** [comment]
There are 2 problems here
1.The Code is not cached when in editing mode thus opening the unsaved code in new tab and than
opening the code in new tab doesn't depict the recent changes this is because our editing in  the code editor is not cached.
2.The Second Issue is browser caching.For Our Preview Similar urls are generated but each url even
Though its the same doesn't depict the recent made changes on the preview

**Comment by catarak** [comment]
This issue is focused on the browser caching issue. I'm going to open a new issue about updating the sketch in a different tab!

**Comment by wetmore** [comment]
Not sure if there is a better issue to add this on to, but when I was writing a sketch using a webworker using a file worker.js, any edits to worker.js wouldn't be reflected in the cache. Edits to sketch.js were updated fine. Whenever I ran the sketch, a stale version of worker.js would be used. As a workaround I had to duplicate the sketch to get a new ID for it in order to get the latest version of my worker.js file.

I wasn't loading worker.js in index.html. I tried that but it didn't help.

**Comment by catarak** [comment]
@wetmore I think you're in the right place! Thanks for the additional info.

**Comment by catarak** [comment]
I think the solution here is to add a header in the response from the server. Specifically, I was looking at how Glitch.com handles this. Glitch adds the header `cache-control: public, max-age=0`. I'm going to try this out!

**Comment by catarak** [comment]
It worked 😄 This will be fixed for the next release.

**Comment by dhowe** [comment]
Has this made it into the current editor?  I'm still seeing this problem - makes it virtually impossible to use web-workers in the editor
