### ISSUE TITLE
A Problem about the Present Mode

### ISSUE THREAD

**Issue by Real-John-Cheung** [processing/p5.js-web-editor#1268]
#### Nature of issue?

- Found a  bug (not sure if it's a bug)

#### Details about the bug: 

- Web browser and version: Safari 13.0.3 and Chrome 79.0.3945.130
- Operating System: macOS Catalina 15.10.1 
- Problem: I use a for loop like this to load images
```
for (let i=0;i<4;i++){
 let tem = "filename"+str(i+1)+".jpg";
imageArray.push(loadImage(tem));
}
```
and it work good as a sketch, as an embed and being run locally. But It doesn't work on the present page (aka on editor.p5js.org/account/present/projectcode) and it return a 404 error of wrong image path.
And if I use the normal method it work well on every mode.

**Comment by dhowe** [comment]
I have verified this issue on both Chrome and Firefox

**Comment by catarak** [comment]
Thanks for reporting! I am able to reproduce. Here's a basic example that shows it not working: https://editor.p5js.org/cassie/sketches/anZcPs6GU.

The issue is that in fullscreen/present mode, the sketch is making a request to `https://editor.p5js.org/cassie/present/anZcPs6GU/dog.jpg`, which doesn't exist, but `https://editor.p5js.org/cassie/sketches/anZcPs6GU/dog.jpg` does. Therefore, the options for fixing this are:
1. Do some magic so that the request goes to `https://editor.p5js.org/cassie/sketches/anZcPs6GU/dog.jpg`
2. Create the route s`GET /:username/present/:sketch_id/:file_name` and  `GET /:username/fullscreen/:sketch_id/:file_name` and have them resolve to `GET /:username/sketches/:sketch_id/:file_name`

**Comment by davidbmx** [comment]
I would like to work on this, this change has to be done on the server in the folder server/routes/embed.routes.js  ?

**Comment by catarak** [comment]
@davidbmx yes!
