### ISSUE TITLE
File Extension Change not working

### ISSUE THREAD

**Issue by shakti97** [processing/p5.js-web-editor#1288]
#### Nature of issue?
- Found a bug

#### Details about the bug: 

- Web browser and version: Chrome 80
- Operating System: Ubuntu 18.04
- Steps to reproduce this bug:
1. Expand Sidebar
2. Try to change the extension of the filename
3. It will not save the new extension.

**Comment by shakti97** [comment]
@catarak if possible , I would love to work on it:)

**Comment by DivyamAhuja** [comment]
I don't know if it is bug or it was intended to be like that cause it's coded like that if notSameExtension then name won't be updated.
So Idk if this should be handled
@catarak

**Comment by shakti97** [comment]
Yes, that why I raised issue because if you see most of the editor will let you change the extension while renaming,  if @catarak think that this is a real issue and needs to be handled than i will start working on it.

**Comment by catarak** [comment]
This is intentional—the extension is really important in determining how the file is handled. I'd like to prevent newer coders from accidentally changing the extension and therefore changing how the file is handled. Even though it seems like more steps, I think it's better for users to simply create a whole new file.
