### ISSUE TITLE
Signup new account using caps in name on https://editor.p5js.org 

### ISSUE THREAD

**Issue by po4599** [processing/p5.js-web-editor#1314]
It seems we are hitting a possible bug related to having caps in the login name. For example signup on https://editor.p5js.org with:

Login name: GeorgeZ
Password: 123456
Email: <a valid email address>
Note; These are all fake for testing purposes.

Upon signup, the account gets logged in OK. Log out. Then try to login with the info above. It fails, using either GeorgeZ or georgez. Using the email & password works OK. Upon login, upper right corner says
" Hello, GeorgeZ! "

I’ve had 3 failures in signup/login by parents of students in our class. They used caps in their child’s name. Fortunately, the email address works, but the students don’t often know or remember their parent’s email.

In followup, please also advise if it’s possible to CHANGE a login name or an email address to something else, as long as the new proposed login or email is not already taken.

Thanks!
-Peter

**Comment by jeremydouglass** [comment]
Related forum post: https://discourse.processing.org/t/signup-new-account-using-caps-in-name-on-https-editor-p5js-org/18427/

**Comment by shakti97** [comment]
I am able to reproduce the same bug, working on it to resolve this issue.

**Comment by shakti97** [comment]
hi @catarak, @andrewn , I found the cause, the cause was at the time of signup we are storing the details as it is but at the time of authentication in login we are comparing the stored details(username/email) by taking the lowercase of username/email entered.

So I think there should be case insensitive comparison in both case and in js case insensitive comparison is done by converting both side in same case and then compare.

Should I procced with this approach to resolve this bug @catarak @andrewn . I think this issue is a high priority bug which should be resolved as soon as possible.

**Comment by po4599** [comment]
I see the commit, and the requested merge.  @catarak @andrewn can you please review and merge?

**Comment by catarak** [comment]
I just went down a fun rabbit hole learning about whether email addresses are case sensitive. It turns out they _technically_ are, but basically no services treat them as case sensitive and it is best not to. 

However, usernames can be can sensitive, or at least they could be presented to the user as case sensitive. Username should store their case **but** be case insensitive for login.

**Comment by jeremydouglass** [comment]
> Username should store their case but be case insensitive for login.

And for account creation. Don't let use "FOO" create an account if there exists a user "foo".
