### ISSUE TITLE
Stuck trying to run npm build

### ISSUE THREAD

**Issue by leonardof131** [processing/p5.js-web-editor#1347]
Hello! I'm following the deployment docs to try and run the web editor on an EC2 Ubuntu 18 stance as an learning exercise to learn and run aplications on EC2 instances.

Everything goes to plan until the step where I should run `$ npm run build`. 
The terminal just stops like this: https://i.imgur.com/0OD83gA.png
The same happens if I run the command with `sudo npm run build`

The web editor works fine  with `$ npm run build`, and I want to believe everything is right with my .env file, and even if it wasn't, I think it should throw some error.

**Comment by leonardof131** [comment]
I installed the progress-bar-webpack-plugin to see if the process was just taking a long time or it was really stuck. 
After running it multiple times and leaving it for half an hour, I cant get past 90%

![Screenshot](https://user-images.githubusercontent.com/54316766/77920444-de535f00-7274-11ea-99ea-0969496feb0d.PNG)

**Comment by catarak** [comment]
My suspicion is that the EC2 instance is running out of RAM. You could try use htop to be sure that's the case. You could try using an EC2 instance with more RAM, or create [swap space](https://aws.amazon.com/premiumsupport/knowledge-center/ec2-memory-swap-file/).

However, rather than building your own instance, you could downloading a [Docker image of the p5.js Web Editor from Docker Hub](https://hub.docker.com/repository/docker/catarak/p5.js-web-editor). In this image, the web editor is already built. [On Heroku you can deploy images stored on Docker Hub](https://devcenter.heroku.com/articles/container-registry-and-runtime#pushing-an-existing-image), but you need to download the image locally first.

Or you can use the [Heroku template](https://github.com/processing/p5.js-web-editor/blob/master/developer_docs/deployment.md#self-hosting---heroku-deployment) linked in the deployment documentation!

**Comment by catarak** [comment]
Closing as this isn't a bug with the web editor. Feel free to open issues about deployment documentation!
