### ISSUE TITLE
Creating new Html files in the sketch directory

### ISSUE THREAD

**Issue by YoshK** [processing/p5.js-web-editor#1369]
Hi,
I was just wondering why .html isn't a supported extension when adding new files in a sketch project over the web editor?
It seems interesting to be able to do a bunch of forms to gather data that you will then use in your .js canvas.

Cheers,
YP

**Comment by catarak** [comment]
Great question! Right now the web editor only supports having one HTML file, because everything is rendered client-side and the HTML is not being served by a server. It would be cool to be able to support multiple HTML files but I think unfortunately it would result in some large changes to the web editor.
