### ISSUE TITLE
Force https connection on certain pages

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#139]
For Login/Signup, the user should be redirection to the https version of the site, and redirected back to the http version of the site once they are logged in, unless their initial connection is https.

**Comment by shiffman** [comment]
I'm not sure if this should be a separate issue, but some sketches require http and some require https.  Some examples:

* accessing webcam or microphone require https
* APIs served over https require https
* APIs served over http require http

I don't have any great ideas as to how we should make this evident / selectable by users beyond just changing the URL in the address bar.

**Comment by catarak** [comment]
The nginx configuration has been updated so that if login, signup, or password reset are loaded sever side, they will be redirected to https. I still need to
1. Force the front end to render these pages https (i.e. force them to render server side)
2. Redirect to http again post login
3. #170: have some interface for users to switch between http and https

**Comment by andrewn** [comment]
I've [prototyped a quick approach to redirecting login](https://github.com/andrewn/p5.js-web-editor/commit/e32f5c0a1032e12831b2cebea74d82b268e289c4) to HTTPS on the client. The higher-order component detects if the protocol is HTTPS when mounting the view component and redirecting if not.

Getting the view to redirect back to the original protocol afterwards is a bit trickier since the app is loading from scratch on `/login`.

1. We could pass a query string such as `/login?redirect=http` to tell the app whether to reload on HTTP afterwards;
2. If we have a global flag in local storage of the user's preference for HTTP/S (perhaps set by #170) then we could use that to determine where to redirect.

Does this approach make sense? Should I explore some alternatives?

**Comment by catarak** [comment]
This seems like the right direction to me! 

I think that the preference for http vs. https actually needs to be set on a project basis, since depending on what the user wants to do for that specific sketch, they may need it to be http or https. But I think it this setting should be http by default.
