### ISSUE TITLE
dom createA('#', 'link') function doesn't work as expected

### ISSUE THREAD

**Issue by yining1023** [processing/p5.js-web-editor#145]
I tried to run the following sketch: [http://alpha.editor.p5js.org/projects/rJ9PtlA0](http://alpha.editor.p5js.org/projects/rJ9PtlA0). It writes:

``` javascript
var a = createA('#', 'apples');
```

When user clicks on the link, it should do nothing. But in the editor, it will navigate the iframe to the whole web editor page, which totally makes sense. It's just an issue raised by running code in an iframe instead of the whole page. Maybe we could add something to prevent it from navigating away?

<img width="500" alt="screen shot 2016-10-14 at 6 50 58 pm" src="https://cloud.githubusercontent.com/assets/8662372/19404836/312ef046-923f-11e6-8828-070e4bbd5c56.png">

**Comment by shiffman** [comment]
@yining1023 it's working for me when I run the sketch, what specifically is not working for you?

**Comment by yining1023** [comment]
@shiffman helped me to narrow down the problem. So I rephrased the issue above.

**Comment by catarak** [comment]
In the future what I want to do is render the iframe preview on a separate subdomain, for security reasons. I think it will fix this issue, but I'm not 100% sure.

**Comment by MichaelPaulukonis** [comment]
If you run the sketch in full - https://editor.p5js.org/full/rJ9PtlA0 - clicking on the link will instead provide:

`{"message":"Asset does not exist"}`

As it attempts to navigate to `https://editor.p5js.org/full/rJ9PtlA0/#`

I have found the same behavior when attempting to navigate to anchor links in other sketches.

[Example here](https://editor.p5js.org/MichaelPaulukonis/sketches/XJS1uWHZw) which uses anchor HTML from MDN

----

Expected behavior:  clicking on link should cause page/sketch to navigate to anchor

Actual behavior: page/sketch disappears to be replaced with `{"message":"Asset does not exist"}`

**Comment by MichaelPaulukonis** [comment]
NOTE: Apparently, pre-pending `about:srcdoc` to the anchor links allows them to work.

So, instead of `<a href="#foo">in-page link</a>` you would have `<a href="about:srcdoc#foo">in-page link</a>`

[Example here](https://editor.p5js.org/MichaelPaulukonis/sketches/2qgicri_f) that works

Solution found on [stackoverflow](https://stackoverflow.com/a/59004815/41153)

**Comment by catarak** [comment]
oh, that's so awesome! the web editor could process all links that begin with a `#` and prepend them with `about:srcdoc`

**Comment by MichaelPaulukonis** [comment]
Sounds like that would work.

NOTE: it would have to be a prepend-on-render, or the links will not work when the sketch is downloaded, as the document is no longer `about:srcdoc`

**Comment by catarak** [comment]
Yes! There's some code in the web editor that doesn't get injected when a sketch is downloaded, which is
* infinite loop protection
* window console messaging
So this code could be injected there!

**Comment by masakakinoki** [comment]
The `about:srcdoc#` solution is not working for me.

Expected behaviour: clicking on the 'blue berry' links only causes mousePressed function

Actual behaviour: clicking on the 'blue berry' links causes mousePressed function and then shows a blank preview

Example:
https://editor.p5js.org/abirdwhale/sketches/URhqrGUvZ

**Comment by masakakinoki** [comment]
Instead of `about:srcdoc#`, `javascript:void(0)` works for me.
