### ISSUE TITLE
Self closing brackets

### ISSUE THREAD

**Issue by rjitsu** [processing/p5.js-web-editor#1499]
#### Nature of issue?

- New feature request

#### New feature details:

All brackets such as curly braces, round brackets and square brackets should be autocompleted,as this is a feature most programmers are used to.

**Comment by catarak** [comment]
Thanks for the suggestion! This issue has come up before and I've been on the fence about it (see #941). My initial reaction was not to add it, but my feeling right now is that it's so common in all code editors it doesn't feel right without it. Since this is a duplicate issue, I'm going to close it, but I'm going to mark #941 as a good first issue 😄
