### ISSUE TITLE
Add Emmet integration

### ISSUE THREAD

**Issue by andrewragy** [processing/p5.js-web-editor#1522]
#### Nature of issue?

- New feature request

#### New feature details: Add Emmet integration to HTML documents

**Comment by catarak** [comment]
Thanks for the suggestion! I would be interested in adding Emmet integration—it's a nice too that if you don't know about it, it doesn't get in your way at all (and you wouldn't need to turn it off because it's confusing to newcomers), but if you do, it's really useful! Emmet has even made a [CodeMirror plugin](https://github.com/emmetio/codemirror-plugin) so I think this wouldn't be a ton of effort to get this working.

**Comment by catarak** [comment]
Open to other thoughts about Emmet!

**Comment by andrewragy** [comment]
I have a question: why doesn't the editor use the monaco editor, it's newer than codemirror and has a more modern ui

**Comment by catarak** [comment]
The big issue is that the Monaco editor is not screen reader accessible.

**Comment by neelesh7singh** [comment]
Thanks @catarak  for stating the plugin saved a lot of googling. While going through the plugin I found one more nice feature that adds `emmet-open-tag` and `emmet-close-tag` class to the HTML tags we are inside which could be used to highlight them like this -

![](https://github.com/emmetio/codemirror-plugin/blob/master/example/emmet-tag-pair.gif?raw=true)

Should I add this feature too??

**Comment by catarak** [comment]
> Should I add this feature too??

Sure! It seems really useful.
