### ISSUE TITLE
Can't see shaders code

### ISSUE THREAD

**Issue by pavel-b-kr12** [processing/p5.js-web-editor#1595]
#### Nature of issue?
- Found a bug

#### Details about the bug: 

- Web browser and version: all Chromium, FireFox, Opera  tested
- Operating System:  Windows 10
- Steps to reproduce this bug:

open any example with shaders e.g. https://editor.p5js.org/p5/sketches/3D:_shader_as_a_texture
navigate to shader file. Nothing appears.

**Comment by catarak** [comment]
Thanks for reporting! It is not clear here, but these files are actually hosted externally to the web editor, and even though it appears they are empty, they are not (see #196). Since these are small text files, they probably should be hosted locally, and this would involve changing the `fetch-examples` script.

**Comment by pavel-b-kr12** [comment]
I think people goes to the examples to see that files (and play with them). Now they can't, without download it. But even after download, it is not possible to run examples without setup web server because files can't be loaded from local system because of cross-domain security restriction %\

**Comment by catarak** [comment]
@pavel-b-kr12 I hear you and I agree with you!

**Comment by ricknjacky** [comment]
@catarak I'd like to work on this issue, I'm new to the codebase can you please give me an insight as to what needs to be done?

**Comment by catarak** [comment]
@ricknjacky sure! The file [`server/scripts/examples.js`](https://github.com/processing/p5.js-web-editor/blob/develop/server/scripts/examples.js) pulls all of the p5.js examples from the p5.js website repository via the GitHub API and then uploads them to the web editor database. This is the file you'll need to edit. I would suggest the following approach:
1. Get this project running locally on your computer
2. Run the `fetch-examples` script, and make sure that it worked successfully by testing if you can run the p5.js examples on your local version of the web editor.
3. Edit `examples.js` so that shader files (I think they are `.vert` and `.frag` files) are created as a file in a sketch in the same way that `.js`, `.css`, or `.html` files are, with their text content inserted directly into the MongoDB database, rather than linked via a url like `.jpg` or `.mp3` files.

**Comment by ricknjacky** [comment]
![image](https://user-images.githubusercontent.com/50985033/95605066-0e768880-0a76-11eb-9031-cbbd19a9b470.png)

>Run the fetch-examples script, and make sure that it worked successfully by testing if you can run the p5.js examples on your local version of the web editor.

I get this error
@catarak please help me out here

**Comment by catarak** [comment]
@ricknjacky did you create a `.env` file with valid Github credentials?

**Comment by ricknjacky** [comment]
Yes I performed this command using 
`cp .env.example .env `

i refereed the docs step by step [here](https://github.com/processing/p5.js-web-editor/blob/develop/developer_docs/installation.md)

**Comment by ricknjacky** [comment]
Wait, I didn't do the 
>(Optional) Update .env with necessary keys to enable certain app behaviors, i.e. add Github ID and Github Secret if you want to be able to log in with Github.
step 

let me try once again

**Comment by ricknjacky** [comment]
![image](https://user-images.githubusercontent.com/50985033/95622960-21975180-0a92-11eb-91f8-ee300703148d.png)

To generate this
> @ricknjacky did you create a `.env` file with valid Github credentials?
 
I need to setup this, please tell me how to move ahead with this, as in what to enter or please tell me if it is arbitrary.

**Comment by ankitpal1029** [comment]
is this issue still open? i'd like to work on this.

**Comment by catarak** [comment]
@ankitpal1029 yes and go ahead and work on it!

**Comment by ankitpal1029** [comment]
@catarak  sure I'll get right to setting up the project , I'm new to contributing to open source projects 
Forgive me if I badger you with too many questions ⊙﹏⊙

**Comment by vulongphan** [comment]
@catarak @ricknjacky I had the same issue with running the `fetch-examples` script although I am sure I passed my correct github credentials (since I am able to login thru Github in my local development). I believe the error is emitted at line 78 (please see attached) and the problem should be within the `options` at line 51 (see attached), and more specifically I speculate that the issue is with the github api used in this case
![Screen Shot 2020-11-06 at 7 12 02 PM](https://user-images.githubusercontent.com/46087559/98381932-f5a4c700-2063-11eb-8bcc-bddfa31b78e5.png)

Could you please assess if my speculation is correct and how I can overcome this? 

Thank you.

**Comment by catarak** [comment]
That's super weird! I don't know what to tell you since it is working for me, and the only difference is the GitHub credentials. Are you sure you're giving the right permissions to your GitHub app?

**Comment by vulongphan** [comment]
@catarak is it possible that you can tell me what permissions I need to grant my Github App? I have enabled the `Contents` option but there is still the error `401 - Bad Credentials`. I have also searched for the permissions that I need to give my github app in order for it to access resources at `/repos` GitHub API endpoint but there is no useful document on this. 
I was looking at the GET repository API [here](https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#get-a-repository). I just dont know if I am heading in the right direction.

**Comment by catarak** [comment]
I would recommend trying to authenticate with the GitHub API outside of the context of the web editor to confirm your credentials work! You could write a small script to do this.

**Comment by vulongphan** [comment]
Hi @catarak, I wrote a script to check my credentials and I realized that (yes, I should have realized earlier) the credentials I created previously are for a Github app, while the correct credentials should be for an Oauth App. Hence, I have been able to run the `fetch-examples` successfully. If @ricknjacky does not mind, could I work on this issue?

Also, do you think that we should update the [installation guide](https://github.com/processing/p5.js-web-editor/blob/develop/developer_docs/installation.md) with a note that the Github credentials should be for an Oauth app instead of a Github app so that the incoming contributors won't run into the same issue as me?

**Comment by catarak** [comment]
> Also, do you think that we should update the [installation guide](https://github.com/processing/p5.js-web-editor/blob/develop/developer_docs/installation.md) with a note that the Github credentials should be for an Oauth app instead of a Github app so that the incoming contributors won't run into the same issue as me?

That makes sense to me! I think that there have been some changes to the GitHub API since I started this project, and maybe there wasn't a distinction between OAuth Apps and GitHub Apps then?

**Comment by vulongphan** [comment]
> @ricknjacky sure! The file [`server/scripts/examples.js`](https://github.com/processing/p5.js-web-editor/blob/develop/server/scripts/examples.js) pulls all of the p5.js examples from the p5.js website repository via the GitHub API and then uploads them to the web editor database. This is the file you'll need to edit. I would suggest the following approach:
> 
> 1. Get this project running locally on your computer
> 2. Run the `fetch-examples` script, and make sure that it worked successfully by testing if you can run the p5.js examples on your local version of the web editor.
> 3. Edit `examples.js` so that shader files (I think they are `.vert` and `.frag` files) are created as a file in a sketch in the same way that `.js`, `.css`, or `.html` files are, with their text content inserted directly into the MongoDB database, rather than linked via a url like `.jpg` or `.mp3` files.

@catarak Is it fine if I work on this shaders code issue since there hasn't been any update?

**Comment by vulongphan** [comment]
@catarak I am so sorry for mentioning you in many different issues and PRs. I think that is why you missed my comment on this issue. I just want to know if this issue still needs to be worked on and whether I can work on it.

Thank you!

**Comment by catarak** [comment]
No worries! Yes you can go ahead and work on this 😄

**Comment by vulongphan** [comment]
@catarak I have been able to add text content to the `.frag` and `.vert` files. However, I am not sure if my solution is of the best coding practice. Could you please have a look?
