### ISSUE TITLE
⌘T for reformat and ⌘R map to run

### ISSUE THREAD

**Issue by bensk** [processing/p5.js-web-editor#16]
Thanks!
👍

**Comment by catarak** [comment]
The comments are now working. For reference, the CodePen shortcuts.
<img width="601" alt="screen shot 2016-07-21 at 3 42 42 pm" src="https://cloud.githubusercontent.com/assets/6063380/17036321/d1d6e0f4-4f59-11e6-8372-11ebb1118c91.png">
Since ⌘ + T and ⌘ + R are basic browser shortcuts, maybe we want to use other shortcuts? Open to thoughts.

cc @shiffman @lmccart

**Comment by catarak** [comment]
Also considering: Command + Enter to Run, Command + Shift + Enter to Stop, as this is a standard keyboard shortcut.

**Comment by lmccart** [comment]
I agree, lets avoid ⌘ + T and ⌘ + R. What about ctrl + R, etc? Or is that refresh on windows?

**Comment by shiffman** [comment]
I like command enter!   So maybe. . . .

⌘ENTER --> RUN
⌘⇧ENTER --> STOP
⇧TAB --> AUTO-FORMAT

(@lmccart, yes, ctrl+r is refresh on windows.)

**Comment by catarak** [comment]
This is _almost_ done, just need to add the keyboard shortcuts to the keyboard shortcut modal

**Comment by kaganjd** [comment]
Gah, just seeing this now! Sorry bout that, I'll do it today.

**Comment by catarak** [comment]
no worries, I also forgot to tell you
