### ISSUE TITLE
Issue when I download on desktop my sketch

### ISSUE THREAD

**Issue by wrongTactic** [processing/p5.js-web-editor#1606]
Hi everyone, 
I'm having an issue when running locally a sketch that works perfectly on the online editor.
Actually the problem is that it can't find a JSON file that is in the same folder, but that issue doesn't happen while on the web editor. Any suggest?
Thanks everyone

**Comment by catarak** [comment]
Hi @wrongTactic! It could be that you need to use a web server when trying to run the sketch locally (for example, I usually use [`http-server`](https://www.npmjs.com/package/http-server), and then run the command in the same directory as my sketch. Since I don't think this issue is specifically a bug/feature for the web editor, I'm going to close it!
