### ISSUE TITLE
Bottom Padding issue in Keyboard Shortcuts model

### ISSUE THREAD

**Issue by KKVANONYMOUS** [processing/p5.js-web-editor#1654]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version:  Chrome
- Operating System:  Windows 10
- Steps to reproduce this bug:
 1) Go to **Help** menu
 2) Select **Keyboard Shortcuts**
 3) Check the bottom padding of Keyboard Shortcuts model. Also try to resize the browser size and you will see the padding issue more clearly

![Screenshot (14)](https://user-images.githubusercontent.com/58628586/97395674-726cce00-190b-11eb-85f7-a02bfe488b58.png)

**Comment by sagar-joshi** [comment]
On adding overflow property in the overlay-body class in _overlay.scss , the keyboard shortcuts tab looks like below: 

![Untitled](https://user-images.githubusercontent.com/42578673/97420708-ae1a8e80-1931-11eb-8dd8-4d025158c3d1.png)

 It also changes settings tab (otherwise the same problem was with settings also)

![Untitled1](https://user-images.githubusercontent.com/42578673/97420869-d7d3b580-1931-11eb-91d7-4e2abf35569c.png)

Creating a PR just in case the changes look okay.

**Comment by catarak** [comment]
Thanks for reporting!!! I'll check out your PR @sagar-joshi 😄
