### ISSUE TITLE
Serve preview iframe from subdomain

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#166]
This is for security reasons.

**Comment by jgrizou** [comment]
I developed a small webapp, called [p5live](https://p5live.jgrizou.repl.co/), that I think replicates what this issue is intended to and could be used to test interest from users.

See #1817 or read more at https://twitter.com/jgrizou/status/1371882296375132162

If useful, implementation details can be found at https://github.com/jgrizou/p5live
