### ISSUE TITLE
Mobile UI - Deploy Initial Version to Production

### ISSUE THREAD

**Issue by Swapnil-2001** [processing/p5.js-web-editor#1689]
Hi @catarak , I understand @ghalestrilo and you made significant progress towards creating a mobile friendly UI as part of this year's GSOC. Nonetheless, I was wondering if there is still something to contribute on that front. If so, I'd be interested to work on it.

Thanks!

**Comment by catarak** [comment]
Yes! @ghalestrilo did such awesome work 😄 I would recommend as a first step just running the mobile version locally on your computer, but adding the environment variable (to your `.env` file) `MOBILE_ENABLED=true`. If you want to use it on a phone, I recommend using something like [ngrok](https://ngrok.com/), because you'll need an https url in order to test it. It definitely doesn't cover all features of the web editor, but it has some of the basics covered.

I would like to deploy it to production soon, but what I think needs to happen first is:
1. Deciding on the minimum features that need to be covered
2. Another design iteration (which is currently happening!)
3. Testing to make sure these minimum features are met. 

Sorry that I don't have a specific task to give you, but even just getting it running locally on you computer and testing it and documenting your experience is super super helpful!

**Comment by Swapnil-2001** [comment]
Okay, no worries😄
Then I'll get it running locally and test it!

**Comment by ghalestrilo** [comment]
Only seeing this now!! Thanks for tying this loose end ❤️
Very excited to see this project pushed over the line
