### ISSUE TITLE
When pressing backspace key web editor does some backspaces that I don't want it to do

### ISSUE THREAD

**Issue by iKittyCode** [processing/p5.js-web-editor#1695]

**Comment by catarak** [comment]
Thanks for reporting! Can you describe what's happening in more detail? Like adding your browser/operating system, steps to reproduce, and so on.

**Comment by iKittyCode** [comment]
safari and chrome is my browser

**Comment by catarak** [comment]
Okay! I'm still not sure what exactly the issue is that you are reporting—can you describe in more detail what's happening and the steps to reproduce? If I can't understand the issue then I can't fix it.

**Comment by iKittyCode** [comment]
So when I press backspace it starts automatically backspacing things I don't want it to backspace

**Comment by catarak** [comment]
Thank you for your update, I really appreciate it! It unfortunately doesn't give me more context—you're simply restating the subject of the issue in different words. It's okay, writing a bug report is hard and takes practice! I am not experiencing this bug, so in order to figure out what's going on, I need specific details so that I can reproduce the issue and then fix it. Here are some resources for how to file bug reports:
- [Chapter 4: How to write clear and efficient steps to reproduce in your bug report](https://medium.com/we-are-testers/chapter-4-how-to-write-clear-and-efficient-steps-to-reproduce-in-your-bug-report-d96039a1c77d)
- [How to write a bug report that will make your developers happy](https://marker.io/blog/write-bug-report/)

I need to know stuff like:
- Is this happening all of the time, or only under certain conditions? 
- What's your operating system?
- Do you have any browser extensions installed that could affect this?

**Comment by iKittyCode** [comment]
This is happening whenever i press the backspace key more than twice
Os x, chrome Os
No i do not
