### ISSUE TITLE
Feature Request: prefers-color-scheme

### ISSUE THREAD

**Issue by setanarut** [processing/p5.js-web-editor#1748]
#### Nature of issue?

- New feature request

#### Feature enhancement details:
The site does not respect the [system preference](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) Also site turns to light mode with each page refresh.

#### New feature details:
use [prefers-color-scheme ](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) for dark mode.

**Comment by hazarek** [comment]
> Welcome! 👋 Thanks for opening your first issue here! And to ensure the community is able to respond to your issue, be sure to follow the issue template if you haven't already.

I prefer to wait for someone alive. stupid robot.

**Comment by catarak** [comment]
@hazarek I would first like to direct you to the [Code of Conduct](https://github.com/processing/p5.js-web-editor/blob/develop/.github/CODE_OF_CONDUCT.md) for this project. It's not okay for you to take out your frustration on the maintainers of this project.

I appreciate the suggestion. Do other websites do this? For me, I feel like since you can explicitly change this in the Settings, I wouldn't like that it would automatically change. But that's just me!

**Comment by setanarut** [comment]
> I appreciate the suggestion. Do other websites do this?

What other websites? There are billions of websites around the world. and all browsers support this CSS feature. this will become the standard in the future. For example: youtube.com has an automatic theme feature according to the device.

 > I would first like to direct you to the Code of Conduct for this project.

Was I disrespectful to a robot? I'm just having fun, calm down. I didn't violate Github's rules. your rules do not concern me. I also do not respect censors.

> I feel like since you can explicitly change this in the Settings, I wouldn't like that it would automatically change. But that's just me!

Site turns to light mode with each page refresh.

**Comment by setanarut** [comment]
nevermind, I don't want your project to improve thanks to me. I have no business with censors.
