### ISSUE TITLE
Private sketches

### ISSUE THREAD

**Issue by masterlaver13** [processing/p5.js-web-editor#1832]
All sketches are public to everyone.

- New feature request

#### New feature details:
All sketches that are made in web editor are public to everyone. They refresh instantly so someone can follow the work.
I suggest adding private sketches. I know, there is a solution: to work on downloaded files, but it is sometimes difficult. The person who has these files can have issues with compiling them.

When an author makes a sketch and he wants to sell it or use it for his class then there is a problem. It is public and it can be copied at any time if someone knows the username. 

I think web-editor is a powerful tool, there is everything in one place. In my opinion, it must have an option to make sketches private or public.

**Comment by slowizzm** [comment]
I like the openness of the web editor since it is based around learning and community. But I would like the option to be able to save a sketch and publish it when it is ready. Mostly as an educator to avoid my students accessing an assignment/demo/example before it is ready for them.

This may be related to #753. What happens if our repo gets set to private after we have imported?

**Comment by kjhollen** [comment]
Thanks for the suggestion @masterlaver13! We're already tracking this feature in #91, so I'm going to close this one. If you have any additional thoughts, please comment there!
