### ISSUE TITLE
if-else statement problem

### ISSUE THREAD

**Issue by JustinChan613** [processing/p5.js-web-editor#1844]
Hi all I am now doing a project, making a game. As I am making a random selection of player / ai playing first, I find it does not work at all. Would like to know where the problem is, Thanks.

https://editor.p5js.org/JustinChan/sketches/gdQ2nM9Ld

**Comment by slowizzm** [comment]
You'll have better luck getting help with this type of issue [here](https://discourse.processing.org/c/p5js/10). This is not a forum, this space is for issues related to the p5.js web editor.

**Comment by da091005** [comment]
@JustinChan613 
Like slowizzm said, this isn’t a place for coding help. This is a place to open issues related to the actual operation of the web-editor. 

That being said, your issue is that you’re calling noLoop(); but draw is sill being executed once after your AI moves, so the ellipse is being overwritten by the background() in draw.  So, delete your draw function and move your background(120) to the setup.
