### ISSUE TITLE
Suggestion: SQLite3

### ISSUE THREAD

**Issue by everythingability** [processing/p5.js-web-editor#1868]
This may not be suitable/possible, but it is my opinion that working with relational databases is WAY HARDER than it should be for learners who just want to learn the basics... tables, ids, foreign keys, joins etc.

If the extensions .sqlite3, .sqlite, .db were white listsed, would I be able to connect to a db from p5js (using a sql library)? Or would that not be doable? ( I'm know I could use glitch but I'm not a huge fan of Node.js, particularly for early coders.

Thanks all

Tom

**Comment by catarak** [comment]
Thanks for the suggestion! I think the solution would be to work with the [IndexedDB API](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API), which I have not at all tested if it works with the web editor. I also just found a library called [Lovefield](https://github.com/google/lovefield) which is a relational database that works in the browser.

It's not really best practice to access a database directly from the front-end (because of security issues), so even though it could be useful as a pedagogical tool my instinct is that it doesn't make sense to support `.db` files in the web editor.

**Comment by everythingability** [comment]
Thanks Cassie...

Lovefield does look good... got the Getting Started playing with p5js OK.

https://editor.p5js.org/remarkability/sketches/e0I3vtSxb

Tom
