### ISSUE TITLE
variables declared in console window are not stored

### ISSUE THREAD

**Issue by dipamsen** [processing/p5.js-web-editor#1876]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: Chrome 90.0.4430.212
- Operating System: Windows 10
- Steps to reproduce this bug:

declare a variable in the `ConsoleInput` and try to access it

![image](https://user-images.githubusercontent.com/59444569/119378914-6c41a300-bcdc-11eb-84b6-0bcfca8778c0.png)

**Comment by catarak** [comment]
Thanks for reporting! This unfortunately is a limitation in how the console works and I haven't figured out a way around it yet. The same issue actually occurs on CodeSandbox, CodePen, etc. which I take as a sign that maybe it's not a trivial thing to solve. 

The way around this is to use `var` instead of `let` or `const`. If you would like to access a variable in your sketch from the interactive console, you would have to define it using `var` as well. Let me know if you have more questions!
