### ISSUE TITLE
TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by adamcole123** [processing/p5.js-web-editor#1879]
#### Nature of issue

- Found a bug

#### Details about the bug: 

- Web browser and version: Edge
- Operating System: Windows 10
- Steps to reproduce this bug:

This is my setup function
```
function setup() {
	createCanvas(windowWidth, windowHeight);

	ui = new UI();

	graph = new Graph();
	graph.initialiseStreets();

	ui.driverButton = createButton('Driver');
	ui.restaurantButton = createButton('Restaurant');
	ui.destinationButton = createButton('Destination');
	ui.driverButton.position(10, 10);
	ui.restaurantButton.position(10, 20);
	ui.destinationButton.position(10, 30);
	ui.driverButton.mousePressed(changeSelectionMode(0));
	ui.restaurantButton.mousePressed(changeSelectionMode(1));
	ui.destinationButton.mousePressed(changeSelectionMode(2));
}
```

When i click one of the buttons, i get this error:
```
TypeError: Cannot read property 'call' of undefined
    at _main.default.Element.eventPrependedFxn (https://cdn.jsdelivr.net/npm/p5@1.3.1/lib/p5.js:63718:26)
p5.js:63718
```

Not sure if this is to do with my code, since im new to p5, any help would be appreciated :)

**Comment by catarak** [comment]
Hi @adamcole123! Thanks for reporting. Are you using any additional libraries to p5.js? The `UI` class and the `Graph` class are not included in p5.js, which could be the source of your issue. 

Also, in general, if you're looking for support with p5.js code, I recommend post in the [Processing Discourse](https://discourse.processing.org/) or on [Stack Overflow](https://stackoverflow.com/tags/p5.js/hot). GitHub is for reporting bugs in p5.js or the p5.js Editor rather than getting code help.
