### ISSUE TITLE
Can not use WebBluetooth function.

### ISSUE THREAD

**Issue by tetunori** [processing/p5.js-web-editor#1900]
#### Nature of issue?

- Found a bug

#### Details about the bug: 
Hi all, I found that I could not use WebBluetooth function on the latest p5js web editor as of 2021/07/15. So, now we can NOT use [p5.ble.js](https://itpnyu.github.io/p5ble-website/), [p5.toio](https://tetunori.github.io/p5.toio/), and so on.
Please check the demos below.
[p5.ble.js demo](https://editor.p5js.org/jingwen_zhu/sketches/R3-iiTn8H)  
[p5.toio demo](https://editor.p5js.org/tetunori/sketches/2J4HYQA35)

I could surely use it in June 2021 so I think some recent changes might affect.   
At least, this issue occurs on Chrome and Firefox environment. 
 
#### Environment 
- Web browser and version: Chrome 91.0.4472.124（Official Build）（64 bit）
- Operating System: Windows 10 Home, 10.0.19042 build 19042

#### Steps to reproduce this bug:
1. Access to one of the demos above.
2. Try to connect.(click Connect button or click screen on Preview window.) 
3. Problem occurs! The error log "**SecurityError: requestDevice() called from cross-origin iframe.**" is shown in the Console and BLE connection dialog never opens up.

Usually, BLE connection dialog below opens and we can connect to the BLE peripheral.
![image](https://user-images.githubusercontent.com/14086390/125787867-c1db663e-9831-4640-b1bc-516e67e03ebb.png)

Since WebBluetooth on P5 js web Editor is very easy to use and helpful for a lot of people, I hope this issue will be fixed.

**Comment by catarak** [comment]
Thank you for reporting! I did a little bit of research and unfortunately I don't know if it's possible to fix this at the moment. There's been an [open issue in Chromium about it since 2015](https://bugs.chromium.org/p/chromium/issues/detail?id=518042&desc=2), and there apparently was an [attempt to add this feature but it was abandoned](https://chromium-review.googlesource.com/c/chromium/src/+/657572) 😢 

If you use the ["present" view](https://preview.p5js.org/tetunori/present/2J4HYQA35), it should work, though I think if you are using it to do active development you will notice that it will cache previous versions of your sketch. I thought there was an open issue about this but I'm having a hard time finding it, so I will open an issue about that bug 😄 

I know it's really frustrating to have a feature no longer work and not have an answer when it could be fixed. This is an issue that many other online code editors face as well—for example, someone made a [bluetooth proxy example for Observable](https://observablehq.com/@tomlarkworthy/bluetooth). 

**Update**: I was wrong about the caching issue. That issue only comes up with media files, see #1738, #1860.

**Comment by tetunori** [comment]
Thanks @catarak for your first analysis.
I have checked with Docker environment and found the result below.

v2.0.2 : This issue occurred.
v2.0.0 : This issue occurred.
v1.4.2 : No problem.  This issue didn't occur.

I hope it will help you to analyze.

**Comment by tetunori** [comment]
I found that this issue occurs with the code [14513b9](https://github.com/processing/p5.js-web-editor/tree/14513b92771abffde507d0f6b48c194975e62cce) (just before merge #1894 ).

So, I think there is a cause in commits merged as #1894 .

**Comment by catarak** [comment]
Yes! This issue is caused by #1894, but unfortunately the change protects the p5.js Editor against Cross Site Scripting (XSS) attacks. I would like to be able to enable bluetooth connects from within the sandboxed iframe but it seems like browsers unfortunately prevent this, which is super frustrating.

**Comment by tetunori** [comment]
Thx for your response. I got the current situation and fully understandable. 
So, until the day when browsers supply any methods to allow WebBluetooth in iframe, let this issue remain open.

**Comment by pelikhan** [comment]
Maybe there is hope? WebSerial is enabled currently on the editor.

**Comment by tetunori** [comment]
The other day, I found the item on Permission policy support for WebBluetooth in Chrome v104 release(roadmap) status below.
https://chromestatus.com/feature/6439287120723968

I think this function might enable p5.js Web Editor(has cross-origin iframes) to support Web Bluetooth function and some libraries using the technology such as p5.ble.js, p5.toio and so on.

Actually, OpenProcessing has just already supported it and it does work now!
Example: https://openprocessing.org/sketch/1709870

**Comment by jasonjsnell** [comment]
I agree, it does look like OpenProcessing is able to use WebBluetooth in its iframe successfully.

@catarak could a similar solution be implemented for the P5 editor? 

I'm working on an EEG bluetooth template for ITP / IMA students who are new to code, and I'd love for it to work in the P5 editor rather than having them move over to VS Code.

**Comment by raclim** [comment]
Hi everyone! I just tried to implement a solution for this, please reopen this issue or create a new one if the Web Bluetooth function still doesn't work!

**Comment by tetunori** [comment]
@raclim I have confirmed and p5.toio works fine! Thanks for your fixing!
