### ISSUE TITLE
Create a variable = PROJECT ends up as "square" when referenced

### ISSUE THREAD

**Issue by rdyar** [processing/p5.js-web-editor#192]
I would like my little application to be able to change the `strokeCap` via the UI, so I am trying to create a variable to hold the selected choice.

For some reason if the variable is = PROJECT then I get "square". If the variable is SQUARE then I get "butt", if it is ROUND then I get ROUND.

Here is a screen shot of just a basic sketch with those 3 variable and a println to show what it does:

![image](https://cloud.githubusercontent.com/assets/7111699/20027919/8f3804f6-a2df-11e6-83a9-e8c57bef8faa.png)

**Comment by lmccart** [comment]
The variable names (PROJECT, ROUND, SQUARE) are used as shortcuts that hold the value that must be passed to the graphics canvas in order to set the stroke cap. We chose the var names to align with Processing's API, but HTML5Canvas has different names for them (square, round, butt) which you are seeing when you print to console. So this is correct behavior.

For future reference, library specific issues can be posted here: https://github.com/processing/p5.js/issues. This repo is just for web editor specific issues.

**Comment by rdyar** [comment]
thanks for the quick reply, after I posted I wondered why I posted it here instead of the library.

Using square, round and butt as my values works - hadn't tried that last night.
