### ISSUE TITLE
Google's OAuth 2.0 - Authorization Error

### ISSUE THREAD

**Issue by MartinMSPedersen** [processing/p5.js-web-editor#1946]
- Found a bug

#### Details about the bug: 

It is not possible to login using Google Auth.  
It gives this error: "You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy for keeping apps secure."

**Comment by code4humanity** [comment]
@catarak, would you mind giving me some context to fix this issue?

**Comment by cwhetung** [comment]
Seeing the same issue here.

**Cause:** Using Google OAuth to login. Redirected to the failure page (PDF attached).

Closing Chrome completely and several retries sometimes let me in, but it is inconsistent.

[p5js Sign in Error.pdf](https://github.com/processing/p5.js-web-editor/files/7470144/p5js.Sign.in.Error.pdf)

Let me know what other info I can provide!

Thanks,
Clay

**UPDATE** Seems to work on Safari, but not always on Chrome Version 95.0.4638.69

**Comment by johhnry** [comment]
Hi,

Some users (including me) seems to have the same issue. Here is a linked thread on the Discourse forum:

https://discourse.processing.org/t/error-400-invalid-request/33288

**Comment by DavidGriswoldTeacher** [comment]
We are also having this problem. We did not have an issue until today. My students' projects are inaccessible until we get this fixed...

**Comment by DavidGriswoldTeacher** [comment]
Following up, I think I may know how to solve this problem.

The screenshot below is partially in English and partially in Portuguese (because I'm physically located in Brazil), so sorry about that.

![image](https://user-images.githubusercontent.com/49095734/140309303-13b56438-02db-41c1-93a1-1e9f0d2b0e29.png)

When yo go to the Google help page for this error, one of the bullet points is shown below:

![image](https://user-images.githubusercontent.com/49095734/140308631-666b5c2f-8969-4f69-9c2d-31971037b5f7.png)

Since the  web editor seems set up to use HTPPS just fine, my guess is that if the redirect URI is changed to `https://editor.p5js.org/auth/google/callback` in the google developer console, everything should work fine.

**Comment by catarak** [comment]
Hey all,

This has been fixed, and I'm sorry for not fixing this sooner. We're a really small team (in fact, the editor team is just me, part time), and there are a lot of notifications on discord/discourse/GitHub/Twitter/etc. It's difficult to sift through them and find that things that need to be attended to immediately. In the future, for anything urgent, please email hello@p5js.org. And also, in the future, I'll do a better job of communicating how to reach the team for urgent issues. I really appreciate the patience and support!

**Comment by zeke** [comment]
Thanks for fixing this @catarak! We appreciate your hard work.
