### ISSUE TITLE
Antivirus software blocking editor from running sketches

### ISSUE THREAD

**Issue by kjhollen** [processing/p5.js-web-editor#1965]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

One of my students has a Microsoft Surface tablet with AVG Antivirus installed on the machine (they said it came bundled with the device and are using the free version). They noticed that over the weekend, the antivirus software started blocking the editor from starting their sketches when they hit the play button in the editor. The antivirus software reports a phishing attempt—maybe a problem with the embedded iframe? The same happens if they try to load the Fullscreen version via File -> Share. The Present version does not load at all.

I saw that some code related to the preview was updated late last week (#1964) so maybe this is affecting the issue @catarak?

- Web browser and version: Chrome (unsure of version number)
- Operating System: Windows 10
- Steps to reproduce this bug: Try to run a sketch on a Windows computer with AVG Antivirus installed.

**Comment by catarak** [comment]
Thanks for reporting! I think this is happening because of the recent phishing issues the site has been having—I've deleted the content but perhaps the site is still flagged. I'll need to think more deeply about how to prevent the phishing issues, short term and long term.

I think for now, this student can whitelist the site through the AVG software.

**Comment by kjhollen** [comment]
Ohhh that makes sense! Ugh. Ok, I've sent them a note about how to add the site to an allow list.

For anyone else who comes across this issue, here's the AVG tutorial on how to add an exception for a particular site: https://support.avg.com/answers?id=9060N000000To2XQAS and you need to add https://preview.p5js.org/* as the URL for the exception.

**Comment by catarak** [comment]
I just pushed [v2.1.5](https://github.com/processing/p5.js-web-editor/releases/tag/v2.1.5) which removes the Present view. I believe this is the easiest way to prevent phishing in the short term, since we don't have a support team to remove bad sketches promptly or have a way to scan for these types of abuses.

**Comment by kjhollen** [comment]
thank you for taking care of this! I think this is the right call.
