### ISSUE TITLE
Optionally hide the toolbar for embedded sketches

### ISSUE THREAD

**Issue by peilingjiang** [processing/p5.js-web-editor#1975]
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:

I noticed that for embedded sketches, now there's a toolbar for conveniently going to the editor and code. However, sometimes when I embed a sketch on the website, I might only want to demo or present it, and this toolbar might break the presentation and style of my website. I know I could just move all the code locally, but would it be possible to provide an option to `iframe` to disable it? (Or does it exist already?) Thanks a lot!

**Comment by catarak** [comment]
Thanks for the suggestion! I needed to add the header to the embedded view because of some recent issues with phishing, as folks could make their sketches look like a totally different website. There are possibly ways to prevent phishing and allow for a sketch rendering without the header, but I'm not sure what that is right now. 

I'm going to collect some of those ideas in #1971.
