### ISSUE TITLE
print() called within draw can cause a loss of work

### ISSUE THREAD

**Issue by tredden330** [processing/p5.js-web-editor#2016]
#### Details about the bug:

- p5.js version: 
- Web browser and version: chrome
- Operating System: Windows
- Steps to reproduce this:
Calling print() within draw causes a print prompt to show up with no way to exit the loop without closing the browser tab, which means you lose your work if you haven't saved it recently. I think it would be nice if there was a quick pop-up warning that using print() in draw might cause an infinite loop.

**Comment by DavidKozdra** [comment]
I could not replicate this, I made several print calls and it limited me to 5000 outputs, it did not freeze or cause issues
what web extensions are you using did you have a lot of stuff running on the browser? I know this was a while ago, but any more details would help, otherwise this issue should be closed. 
![image](https://user-images.githubusercontent.com/45106564/183536168-4299facf-f185-4836-b218-0cb26c7e5c54.png)

**Comment by raclim** [comment]
Hi! I couldn't replicate this issue as well, so I'm going to close this for now! Please feel free to reopen this or create a new issue, thanks!
