### ISSUE TITLE
Media load file location was "loose" and now "strict"?

### ISSUE THREAD

**Issue by REAS** [processing/p5.js-web-editor#202]
I'm having trouble running some older student files. They ran fine two weeks ago, now they are hanging on "Loading..." 

I think I have it tracked down to the code not correctly stating the location of an image, for example:

`day1 = loadImage("day-01.png");`

when the code should be this because that PNG is actually in a folder:

`day1 = loadImage("assets/day-01.png");`

The code above was working, but not it appears to not work. Did something change? I would personally prefer for only the bottom code to work.

**Comment by catarak** [comment]
yes! i did a big refactor of how the preview generation code works (5e0216f2ecf9f2a1ce006565887337a8c399ec8e) and now it actually respects the folder hierarchy rather than just matching files by name. therefore, i think only the bottom code works, but let me know if there are issues with that.

Note that it does not work for relative paths (i.e. '../assets/day-01.png).

**Comment by REAS** [comment]
Thanks for the quick reply! The good news is what you said, the bad news is I can't do my grading because the students' code all broke. :)
