### ISSUE TITLE
Inaccurate rendering during file upload

### ISSUE THREAD

**Issue by 3ru** [processing/p5.js-web-editor#2040]
Animation is not rendering properly when uploading multiple files of three or more.

#### Details about the bug:

- p5.js version: 1.4.0
- Web browser and version: Google Chrome 103.0.5060.114
- Operating System: Windows
- Steps to reproduce this:
1. uploading multiple files
2. only the top two upload completion animations work
(All files are uploaded successfully)

|Successfully uploaded|Only two animations|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/69892552/178658578-0e65bb3d-e30f-48da-80f1-2a81e6c4dedb.png)|![image](https://user-images.githubusercontent.com/69892552/178658590-924a1b46-98a1-45a3-b595-905a42321a2d.png)|

**Comment by lindapaiste** [comment]
I'm looking into this now.  I can see that the `dz-processing` class is only on the first 2 elements, and the `dz-success` only on the first one.  Those classes are handled internally by the dropzone package.  I've got to see what are passing in that's incorrect.
![image](https://github.com/processing/p5.js-web-editor/assets/28965286/e0a9c3de-35fd-4eae-8d92-c6b6a368b390)

**Comment by lindapaiste** [comment]
I did find one thing which we are doing wrong, though I don't think it fixes your issue.   It's supposed to stop showing the progress bar when the upload is done and show a check mark instead.   That doesn't happen because we are overriding the `complete` function instead of adding a secondary event handler.  Therefore the default `complete` behavior is not called and the `dz-complete` class never gets added.
https://github.com/dropzone/dropzone/blob/f50d1828ab5df79a76be00d1306cc320e39a27f4/src/options.js#L769-L776

https://docs.dropzone.dev/configuration/events#overriding-default-event-handlers

I suspect the problem has something to do with the `parallelUploads: 2` option.  But I'm struggling to get S3 uploads working on localhost so I don't know how much further I'm going to get with this.

**Comment by lindapaiste** [comment]
It's important to note that this issue only happens with asset files that are uploaded to S3.  It works fine when uploading .js files to the editor.
![image](https://github.com/processing/p5.js-web-editor/assets/28965286/fac6e2e9-dafb-45e4-8723-f3e1dc5bdcbd)

**Comment by lindapaiste** [comment]
Fixed by #2244
