### ISSUE TITLE
Mobile UI enhancement

### ISSUE THREAD

**Issue by dewanshDT** [processing/p5.js-web-editor#2133]
#### Feature enhancement details:

**current mobile editor and file drawer**

![ss1](https://user-images.githubusercontent.com/71703033/221407372-c2179d71-b9cc-4153-b162-8b3d2f219b49.jpg) ![ss5](https://user-images.githubusercontent.com/71703033/221407379-53251173-63fc-4cf2-9cba-56fbc83c5ab2.jpg)

**This UI can be enhanced according to the prototype created, I would like to work on this @raclim please assign this to me**

**Comment by Noothan-am** [comment]
@dewanshDT is this issue still open ? i would like to contriute on this

**Comment by dewanshDT** [comment]
I'm working on this, well you can check all projects section for more such tasks

**Comment by raclim** [comment]
Hi, since we already have several mobile related issues already (i.e https://github.com/processing/p5.js-web-editor/issues/2120 and the ones linked within it) I'm going to close this issue for now. @dewanshDT I'll be going through and be on the lookout for any mobile related work that you've done, thanks!
