### ISSUE TITLE
Css Breaks in Small size screen View   

### ISSUE THREAD

**Issue by Noothan-am** [processing/p5.js-web-editor#2149]
#### Feature enhancement details:
 -it is not responsive to small size screens

### to reproduce this 
https://editor.p5js.org/nikhilnandig/sketches/A7CziIEjZ
  
![image](https://user-images.githubusercontent.com/100135382/223020263-95415f86-ee4c-4faa-976e-1f958e5a14ce.png)

i want to work on this issue, could you please assign it to me ?

**Comment by raclim** [comment]
Hi @Noothan-am, thank you for bringing this up! We're currently working on the responsiveness of the editor, and have a few issues that detail the Mobile experience already (i.e. https://github.com/processing/p5.js-web-editor/issues/2120 is a recent example with links to other Mobile work). Since we already have issues pertaining to this up, I'll close this for now. :)
