### ISSUE TITLE
p5.js Web Editor unresponsive

### ISSUE THREAD

**Issue by Rean365** [processing/p5.js-web-editor#2173]
Hello, p5.js support! I am currently running into an issue while trying to use the p5.js web editor. When I am editing my code it will randomly become unresponsive leaving my code stuck and unsaved. I've been dealing with this issue for some time on multiple browsers Safari and chrome. Additionally, I keep getting the same error message (that will be attached). I haven't been able to complete any of my assignments for my computer science class. If you can please assist me with this issue I would very appreciative.  

p5.js username : rean.collado2026

<img width="498" alt="Screen Shot 2023-03-21 at 9 44 37 AM" src="https://user-images.githubusercontent.com/128492139/226628973-b06b4a6b-eb70-4b0e-b512-41462f4bb6e2.png">

**Comment by 3ru** [comment]
@Rean365 
I would like to see your code to solve the problem.
From the tabs at the top, click File -> Share and give us your edit URL.

**Comment by Rean365** [comment]
@3ru 
The problem isn't with my code because it happens with all of my p5.js projects. I've actually found out that it's only happens when I'm on that account and not on my other account.

**Comment by 3ru** [comment]
@Rean365 
Can you now reproduce the same problem using the original account?
In the image, it looks like you have the same sketch open in 3 or more tabs. Could the problem be due to insufficient browser memory due to too many open tabs?

**Comment by lindapaiste** [comment]
@3ru It looks like this is the code: https://editor.p5js.org/rean.collado2026/sketches/mme8h01MU There's nothing wrong with it.

@Rean365 If something happens only when logged in as you then naturally I can't reproduce it.  But maybe you can provide some more information.  Can you open up the Dev Tools in Chrome and go to the Console tab before loading the page?  Then load the page take a screenshot of the output in the console.  I'm hoping there will be some big red error message that would point me in the right direction.  For reference, this is what I see when not logged out:
![image](https://user-images.githubusercontent.com/28965286/227364922-d30d301b-b266-4871-92c0-f61245a16568.png)

It's definitely possible to mess up an account.  I know because I've done it 😱 While working on developing the web app I managed to set my `theme` preference to an invalid value, and now the whole editor crashes if I'm logged in.  I don't know how something along those lines could have happened for you, but who knows.
![image](https://user-images.githubusercontent.com/28965286/227366174-ea2f3212-7a28-46fd-912d-64cc9dbbe09e.png)

**Comment by Rean365** [comment]
The attached video is how the problem looks on my end. As soon as i click the run button it starts the problem. 

https://user-images.githubusercontent.com/128492139/227536917-c0cf97a3-5702-46d8-a564-60d0b4094dd3.mov

**Comment by lindapaiste** [comment]
> The attached video is how the problem looks on my end. As soon as i click the run button it starts the problem.

Well that’s a different code!  The `for` loop syntax isn’t right so it’s making an infinite loop.

**Comment by 3ru** [comment]
The code in the video needs to be modified a bit (`x<+40` -> `x+=40`). 

Yes, it is possible that you have `Auto-refresh` turned on, which caused an infinite loop while writing the code so far.
