### ISSUE TITLE
Issue migrating project from VS Code to Web Editor (TypeError: e.set is not a function)

### ISSUE THREAD

**Issue by EV401SALVATION** [processing/p5.js-web-editor#2190]
#### Details about the bug:

- p5.js version: 1.6.0
- Web browser and version: Microsoft Edge Version 111.0.1661.62 (Official build) (64-bit) 
- Operating System: Windows Version 21H2 (OS Build 19044.2728)
- Steps to reproduce this: Unknown

I have been working on creating a simple JRPG in processing for a while now, and I recently decided to move a beta version of it onto the p5.js Web Editor so I could embed it into my site. The program runs fine launching it from VS Code, but whenever I attempt to run it in the Web editor it gives me the error:

    TypeError: e.set is not a function
        at undefined:2:64726

As the program is about 12.5 thousand lines long and it runs fine in VS Code I have no idea where in the code there could be a problem nor how to find it. I think that the error is pointing to this portion of the p5.min.js file that my project's index.html file is pointing to, but I am not sure what to do with this information (the specific character is the first 'f').

    87:[ function(e,t,r){var o=e("../internals/is-regexp");t.exports=function(e){if(o(e))throw TypeError("The method doesn't accept regular 
    expressions");return e}},

Here is the link to the project as well:

    https://editor.p5js.org/donmharp/sketches/L2XlLZzE_

I'm worried that my project simply won't run in the web editor for a reason beyond my control, and I don't know any other way to host it and embed it into a google site. Does anybody know if this is a bug with the Web Editor, or if it is a problem with my code?

**Comment by lindapaiste** [comment]
Hey!  So the error trace is really confusing but I've tracked it down to two issues in your code:

1. Uppercase `.PNG` file extension on your files.
2. Use of Javascript built-in object object name `Map` in your code.

The file loading in the web editor is case-sensitive.  You've got some images which are `.png` and others which are `.PNG`.  I'm seeing 404 errors on images where the code is looking for `.png` but the file in your folder has `.PNG`.  You should be able to fix this by renaming all of your files to `.png`.

The `Uncaught TypeError: e.set is not a function` comes about when the editor tries to log the image load error.   The line which throws the error is in the `console-feed` package which is used by the editor.
https://github.com/samdenty/console-feed/blob/19a2c05f59e0f51ac32862d1a5c5d61f63a22c9b/src/Transform/replicator/index.ts#L193-L205
```
  _makeTransformsMap() {
    if (!MAP_SUPPORTED) {
      return
    }


    const map = new Map()
    this.transforms.forEach((transform) => {
      if (transform.lookup) {
        map.set(transform.lookup, transform)
      }
    })
    return map
  }
```
It's the `map.set` call there.  I was really puzzled by this,[ because a `Map` definitely has a `.set` property](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/set).  I didn't realize the issue until I added some breakpoints in dev tools and saw that the `map` variable which gets created by calling `new Map()` is an object from your code, rather than a [JavaScript Map object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map).  You should rename your `Map` class to something else.
![image](https://user-images.githubusercontent.com/28965286/229375287-42c3981d-6563-4754-a73b-afa127402731.png)

----

To web editor maintainers:

I wonder if there is anything we can do to separate the scope of variables in the user's code from the web editor code.  I have seen other issues like this where using a built-in JS object name causes problems.

**Comment by EV401SALVATION** [comment]
Thank you so much for the help! Once I had fixed those issues and converted a file from a .wav to a .ogg I was able to get it working!
