### ISSUE TITLE
Offensive auto-generated titles for sketches

### ISSUE THREAD

**Issue by mngyuan** [processing/p5.js-web-editor#2247]
### Topic

I just created a new sketch with the web editor and the automatically generated name was `Ebony owner`, which seemed a bit offensive to me. Thought it was worth flagging here based on past diversity statements I've read for fellowship applications, etc.

**Comment by limzykenneth** [comment]
@mngyuan I'm assuming this relates to the autogenerated title for a web editor sketch? If so please do file this issue over here: https://github.com/processing/p5.js-web-editor/issues as the web editor is maintained separately from the p5.js library (which is this repo).

**Comment by Qianqianye** [comment]
Thanks @mngyuan for bringing up this topic. Hi @raclim @catarak , can you take a look at this issue? Thank you!

**Comment by raclim** [comment]
Thanks @Qianqianye for bumping this up and @mngyuan for reporting this! I'm sorry that we missed this—I'll look into this and will try to get back with an update before the end of this week.

**Comment by lindapaiste** [comment]
Thanks for raising this issue.  Here is the code that we use to generate the sketch title:
https://github.com/processing/p5.js-web-editor/blob/1c05241e9ead4bc6f622188ba205c3329268fc72/client/utils/generateRandomName.js#L1-L13

We combine an adjective and a noun which are both generated using the [`friendly-words` package](https://www.npmjs.com/package/friendly-words) created by Glitch.  Here's some relevant info from `friendly-words`, emphasis added.
> The words are pulled from curated files. We want the words and their pairings to be friendly, positive, inspiring, whimsical, memorable, etc. They should also be words that most people can easily remember and spell.
>
> All of the words and their generated pairings should be safe for children of all cultures. This means that we permit absolutely no word pairings that invoke to hate speech, hostility, derogatory terms, etc.
>
> Despite our best efforts, **_it's easy for a pair of benign words to be combined into something inappropriate. Whenever we notice a generated pair that is problematic, we'll remove at least one of the words from that pair so that it won't reoccur._** We'll err on the side of trusting reports and removing potentially inappropriate words rather than defending the appropriate uses of a word.
>
> When adding words to the list, an abundance of common sense is required. **_If the word can be used as a slang term for an ethnicity or nationality, there's probably a context where it'll pair up with a verb or adjective that can make it feel unwelcome_**... so be mindful and avoid those.

"Ebony" and "owner" is definitely an inappropriate combination.  "Ebony" does have a racial connotation so there can be a lot of bad pairings from it.

As it turns out, you are not the first person to notice this!  "Ebony" was included in a list of removals [recommended of a group of teachers](https://github.com/glitchdotcom/friendly-words/pull/28).  That's the good news. It no longer appears in their [`predicates.txt` words file](https://github.com/glitchdotcom/friendly-words/blob/17f4219dbc88e0fa9cdbfa661a436a71a96906e5/words/predicates.txt#L359-L360).  The bad news is that it's still in the [generated `words.json` file](https://github.com/glitchdotcom/friendly-words/blob/main/generated/words.json) which is what is actually used.  Seems like they either forgot to regenerate this file, or have not put out a release since that update.

We have a few options here:

1. Submit a PR or an issue on the [friendly-words repo](https://github.com/glitchdotcom/friendly-words) and try to get them to put out a new release.
2. Include the wordlist in our own repo so that we have control over it.
3. Write a list of excluded words in our codebase (I don't like this because it means that our code contains a bunch of offensive words)

**Comment by lindapaiste** [comment]
I got `friendly-words` to release a new version!  Now all we need to do is update the p5 web editor to use the latest version of `friendly-words`.

**Comment by raclim** [comment]
Thanks so much @lindapaiste for hopping in and resolving this so thoroughly! 🙌
