### ISSUE TITLE
Resetting (Setting) password on an account created through Google/Github doesn't seem to be possible

### ISSUE THREAD

**Issue by aarondill** [processing/p5.js-web-editor#2282]
### p5.js version

N/A

### What is your operating system?

Linux

### Web browser and version

114.0.5735.198 (Official Build) (64-bit) 

### Actual Behavior

Accounts created through third party verification (Ie, Google/Github) don't allow (re)setting the passwords. The new/current password fields exist in the settings page, but as there is no current password, any attempt to set a new password **silently**(!!) fails with a banner saying "Settings saved."

### Expected Behavior

Either current password field doesn't exist unless a password is currently set, or an empty input is treated as a match when no password is currently set.
I'd like to migrate my account away from third party verification to native username/password login, but as I can't set a password, I can't do such.

### Steps:
1. Create an account with a third party authenticator (Google/Github)
2. Navigate to settings
3. Input a password to the "New Password" box
4. Press "Save All Settings"
5. Observe "Settings saved." Banner
6. Logout
7. Try logging in with your email/password
8. :disappointed:

**Comment by Akhilbisht798** [comment]
Hey, I can confirm this issue. I think you expected behaviour make sense here as we should not provide a way to create a password if they don't have already done so, or we can just match it with empty string and add a password feild by that means.

As you said password feild should not exists if we haven't used a password before i think that is great way of handling this.
Also many user prefer to sign up/ sign in with google or GitHub without entering password.

I have just one concern if suppose user want to change his/her method of sign in or up we should able to.


I would like to known your thoughts on this.

**Comment by Akhilbisht798** [comment]
I would like to known your thoughts on this.

**Comment by aarondill** [comment]
Sorry if I caused some confusion with my wording. I highly support allowing the user to change their login method, in fact, that's how I found this!

My suggestion is that *when setting a new password* the empty string is taken as a match for the "current password" as it's slightly more intuitive and likely easier to implement than my alternative suggestion.

**Comment by aarondill** [comment]
Ideally, this would allow the user to have multiple ways to sign in to their account as well. Ie, a password *and* third party verification (Google/GitHub)

**Comment by Akhilbisht798** [comment]
@aarondill okay this make sense. Just to match the new password to empty if user has not set password yet.

**Comment by Akhilbisht798** [comment]
Hey, I have started working on this issue. If you could assign me i can make the change and raise the pr.
