### ISSUE TITLE
Editor crashes when there is any error

### ISSUE THREAD

**Issue by dmccreary** [processing/p5.js-web-editor#2301]
### What is your operating system?

Mac OS

### Web browser and version

Goole Chrome

### Actual Behavior

Screen turns white whenever there is an errorl

### Expected Behavior

Error printed on the log file. 

### Steps:
Put any program with an error.
### Snippet:
```js
function setup() {
  createCanvas(400, 400);
  crashTest();
}

function draw() {
  background(220);
}
```

**Comment by wong-justin** [comment]
See also #2298 , #2296

**Comment by jht9629-nyu** [comment]
This is very serious bug. The editor is not usable for writing new code or change old code. Any script error and any edits are lost. Please fix ASAP or roll back to prior release. I have p5 summer course starting July 24 and will not be able to use the editor with this bug. Help!

Bug introduced in v2.7.0 yesterday 07/14.

**Comment by raclim** [comment]
Thank you so much for reporting this, I'm really sorry that this issue happened due to an oversight in upgrading the `console-feed` package  😭 (further details about the issue and its fix in https://github.com/processing/p5.js-web-editor/issues/2298)

I just deployed a new release which seems to resolve this issue for now, but please reopen this issue if it persists!

**Comment by dmccreary** [comment]
@raclim Thank You!!! It is working perfectly now!!  You are awesome!

I am teaching a class that uses ChatGPT to generate simulations:

http://www.coderdojotc.org/chatgpt-for-teachers/demos/p5/

We have about a dozen teachers that are not using p5.js to generate simulations! 

http://www.coderdojotc.org/chatgpt-for-teachers/demos/p5/motor.html
