### ISSUE TITLE
Error sending confirmation email

### ISSUE THREAD

**Issue by lindapaiste** [processing/p5.js-web-editor#2303]
### What is your operating system?

None

### Actual Behavior

The UI appears as though the email has been sent and shows the message:
> Unconfirmed. Confirmation sent, check your email.

But looking at the dev tools shows that the API request to `https://editor.p5js.org/editor/verify/send` was actually a 500 internal server error with response:
```
{
    "error": "Error sending mail"
}
```
That comes from this line of code:
https://github.com/processing/p5.js-web-editor/blob/4161f98c2127bbead3e317c699694589add135ce/server/controllers/user.controller.js#L248

![image](https://github.com/processing/p5.js-web-editor/assets/28965286/920a16a2-c56d-436a-b63b-6d5097d9c532)

### Expected Behavior

I expect the email to be sent.

### Steps:
1. go to https://editor.p5js.org/account
2. click "resend confirmation email" button

**Comment by adadgarg** [comment]
@lindapaiste It is showing the error message "Error sending mail: [Error: Unauthorized] { status: 401, details: 'Forbidden' }" indicates that the email sending is failing due to unauthorized access. The email service returns a 401 Unauthorized status code, indicating that the provided API key are invalid.
