### ISSUE TITLE
Make the site logo redirect to https://p5js.org/

### ISSUE THREAD

**Issue by mohamedaleya** [processing/p5.js-web-editor#2333]
### Increasing Access

Easier access to the main website from the editor with just one click.
Currently, users need to click on Help > About (or Reference) to be able to visit the main website from the editor.

### Feature enhancement details

It's not that much of an enhancement but it would be nice to make the logo in the left top corner of the editor redirect to the main website: https://p5js.org/

I am trying to get the project to run locally and can work on this feature.

**Comment by nsundriyal62** [comment]
can i work on this issue?
 if this is open and no one working on it
 @mohamedaleya

**Comment by mohamedaleya** [comment]
> can i work on this issue? if this is open and no one working on it @mohamedaleya

Sure!

**Comment by dhruvdabhi101** [comment]
If this issue is still open, i would like to work on this.

**Comment by Nivas7** [comment]
# can I work on this issue

**Comment by PiyushThapaa** [comment]
**can i work on this issue**

**Comment by revanthv999** [comment]
Can I work on this issue?
I am not sure where to start from and would be glad if anyone help me!!!

**Comment by raclim** [comment]
Thanks for raising this issue! I feel that this enhancement might not be something that we need, so I'm going to close this for now! 

The reason is that I feel like it might add distraction to the site experience, especially if it's being accessed from a screen reader. I'm also unsure if a link were to be implemented, if it should direct to the p5.js site or potentially reload the editor.
