### ISSUE TITLE
Design/UX Input

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#25]
I've added a bunch of features just to have them without worrying about the design/ux. Some stuff that would be awesome to have input on:
- Login/Sign Up - should these be separate pages or a modal layover? What do form errors look like? There's a design for toasts in the p5 design but not for form errors.
- Add File popup - Do we want this? This also needs a form error design. 
- Tabs - Do we need these? Happy to add these as they're an iconic part of the Processing IDE design but maybe not totally necessary.
- Sketchbook (Open in the Nav) - What should this page look like? Do we want to add folders? Eventually, should we integrate tutorials/reference sketches in here?
- Shrinking/Expanding Sidebar and Console
-  Navigation Organization - I just added Export and Clone to the Nav, but maybe we want these in a dropdown? Where should publish go? Any things missing in the navigation that we want?
- Project title editing - It would be nice to force the user to add a name.

Or, in general, any design bugs/feedback would be great.

cc @lmccart @shiffman

**Comment by lmccart** [comment]
A few thoughts.

* I like the idea of keeping this as a one page app. That is, relying more on modal layovers than separate pages whenever possible.
* Tabs - I'd say not necessary since we have the file list on the side. Let's keep it simple.
* Project title editing - can we pop up a modal that asks them to name it initially? or on new project select at least?
* Maybe it'd be better to display Modified date rather than Created, this might be more helpful in locating a project.

It seems like it could be useful to pull in a designer on this since there are a lot of parts that really need to be designed from scratch, let me chat with @shiffman and see what's possible.

**Comment by shiffman** [comment]
I agree it would be good to pull in a designer so look forward to figuring this out.

I'm somewhat partial to the tabs b/c I like the idea of operating in the editor as long as possible without every seeing `index.html` or `style.css`, but I agree this is probably redundant and I can learn to retrain my brain to look for the sidebar.

**Comment by kjhollen** [comment]
Hey all, just getting familiar with the project to prep for the school year—I'm excited to test out this online version of the editor! I'll share some thoughts soon, but wanted to say that if you're still looking for a little UX help, I'd be happy to contribute some time in the next two weeks or so before classes start. Great work so far.

**Comment by catarak** [comment]
@kjhollen we've hired someone for some UI/UX help to be implemented soon, but feedback is always welcome.

**Comment by lmccart** [comment]
thanks @kjhollen! though we will have a bit of a design upgrade after we get a round of design work on sep 12, any input is appreciated.

**Comment by catarak** [comment]
closing this as all of these issues have been broken out into separate tickets.
