### ISSUE TITLE
Adding social media icons to share directly in share feature

### ISSUE THREAD

**Issue by madtitan02** [processing/p5.js-web-editor#2514]
### Increasing Access

unsure

### Feature enhancement details

When clicked on the share button, it shows a copy link, Where we can add social media icons at the bottom of the dialogue box and when clicking on the icons it redirects them to the specific social media/mail.
Here is a screenshot of the current share feature, we can add social media icons at bottom 
![Screenshot 2023-10-19 014506](https://github.com/processing/p5.js-web-editor/assets/96717231/94cf604e-a8a4-418b-b1d8-10e607343ba0)

**Comment by madtitan02** [comment]
@lindapaiste if the community agrees can i start working on it I can submit a test pr if you want

**Comment by raclim** [comment]
Thanks for suggesting this! 

Although adding social media buttons to the Share overlay could provide be helpful, I think they aren't the only context where those Share URLs are used. I also feel that it's important to aim to be intentional and minimal with the site content to maintain its clarity and accessibility, which these buttons might distract from—though I could also see them not being a major addition/distraction!

I don't think this is something we'll implement this in the near future so I'm going to close this for now, but this could potentially be revisited!

**Comment by madtitan02** [comment]
sure if there is requirement for this to be done I am more than happy to code this issue out
