### ISSUE TITLE
Vanilla JavaScript console.log issues.

### ISSUE THREAD

**Issue by dcarroll242** [processing/p5.js-web-editor#2519]
### p5.js version

1.7.0

### What is your operating system?

Windows

### Web browser and version

Chrome 118.0.5993.88

### Actual Behavior

The console.log function doesn't work outside of p5 functions (setup & draw). I teach computer science at the high school level and we begin with all text-based activities that rely on the console. 

code:
console.log("hello world");

output:

### Expected Behavior

code:
console.log("hello world");

output:
hello world

### Steps:
1. 2. 3.
### Snippet:
```js

console.log("hello world");

```

**Comment by raclim** [comment]
Thank you so much for reporting this—I think this is also similar to https://github.com/processing/p5.js-web-editor/issues/2518! 

To keep issues organize, I'm going to close this one for now (which is now linked to the other issue), and will continue investigating this from there since it was brought it up first!

**Comment by dcarroll242** [comment]
Sounds good. Thanks!
