### ISSUE TITLE
The "+" button that toggles the menu with options to create a folder and create a file does not close the menu when clicking anywhere else on the screen.

### ISSUE THREAD

**Issue by gauravsingh94** [processing/p5.js-web-editor#2524]
### Increasing Access

When we are clicking on the plus "+" for creating the folder or file the menu which get toggle is not close when we click any where on the screen.

### Feature enhancement details

This will increase the user experience.

[Screencast from 2023-10-21 19-20-49.webm](https://github.com/processing/p5.js-web-editor/assets/99260988/5febbd2c-7372-4bfd-8bb6-c25d49aaaf9e)

**Comment by gauravsingh94** [comment]
I have fix this issue and i have raise the pr. 

Final Output will look like this.

[Screencast from 2023-10-21 20-11-46.webm](https://github.com/processing/p5.js-web-editor/assets/99260988/756f1a18-97b6-4a77-8b69-40f395f3ab73)

**Comment by lindapaiste** [comment]
I did some investigating here and the core issue is a [stale closure](https://dmitripavlutin.com/react-hooks-stale-closures/) of the `isFocused` variable in the `onBlurComponent` handler.

https://github.com/processing/p5.js-web-editor/blob/f21b84772c85927f8016d7c23aef7ad1a5a41b64/client/modules/IDE/components/Sidebar.jsx#L40-L47

The value of `isFocused` which is evaluated inside of the `setTimeout` will be the value _at the time when the `onBlurComponent` handler is executed_, **not** the value after the 200ms delay.  React handles the `setIsFocused(false)` state update asynchronously so we are getting the value before that update, when it was `true`, and therefore the line `dispatch(closeProjectOptions());` is never executed because `if (!isFocused)` is always `false`.

This setup wasn't/isn't an issue in the class components because we're looking at a property on an object, `this.state.isFocused`, so there is no stale variable.  For the record, [I'm the one who converted this to a function component](https://github.com/processing/p5.js-web-editor/commit/0ec02d6e4005269925c399d913d13facffdf11cd) so this bug is my fault as I didn't realize the mistake at the time.

I handled it properly in a new `DropdownMenu` component where I'm using a ref instead of a state to avoid the stale closure issue.  When using a ref we see the value of `focusedRef.current` after the 200ms delay.

https://github.com/processing/p5.js-web-editor/blob/f21b84772c85927f8016d7c23aef7ad1a5a41b64/client/components/Dropdown/DropdownMenu.jsx#L14-L15

https://github.com/processing/p5.js-web-editor/blob/f21b84772c85927f8016d7c23aef7ad1a5a41b64/client/components/Dropdown/DropdownMenu.jsx#L31-L38

IMO the best course of action for the long term would be to use that `DropdownMenu` component here and remove the buggy logic which is specific to this component.  But there are two holdups there:
1. Need to override the sizing on the dropdown so that it shrinks to fit like the current one.
2. Need to figure out how to control the state externally in order to support opening the dropdown when right-clicking the header.

**Comment by Ri-Sharma** [comment]
@lindapaiste in the below part of code we don't actually need setTimeout function
```javascript 
const onBlurComponent = () => { 
   setIsFocused(false); 
   setTimeout(() => { 
     if (!isFocused) { 
       dispatch(closeProjectOptions()); 
     } 
   }, 200); 
 }; 
```

It will also work if we just dispatch without the setTimeout function. Correct me if I am wrong!
```javascript
const onBlurComponent = () => { 
   setIsFocused(false); 
   dispatch(closeProjectOptions());
 }; 
```

**Comment by lindapaiste** [comment]
> @lindapaiste in the below part of code we don't actually need setTimeout function
> 
> ```js
> const onBlurComponent = () => { 
>    setIsFocused(false); 
>    setTimeout(() => { 
>      if (!isFocused) { 
>        dispatch(closeProjectOptions()); 
>      } 
>    }, 200); 
>  }; 
> ```
> 
> It will also work if we just dispatch without the setTimeout function. Correct me if I am wrong!
> 
> ```js
> const onBlurComponent = () => { 
>    setIsFocused(false); 
>    dispatch(closeProjectOptions());
>  }; 
> ```

Hey so I think that the intention of the `setTimeout` is that we close the dropdown when one item is blurred _and nothing else is focused in its place_.  It makes more sense if you thing about using the `Tab` key to navigate instead of mouse clicks.  In the class component version we have the `onBlurComponent` handler on each of the items in the menu.  The `Tab` key goes through each item of the menu, blurring one item and focusing on the next.  We fire the "close" handler when you tab off of the last item in the list.

When the focus changes from the first item in the list to the second, it goes through these steps:

1. `onBlur` is called on the first item.
2. `isFocused` is set to `false`.
3. The timeout begins.
4. `onFocus` is called on the second item.
5. `isFocused` is set to `true`.
6. 200 ms elapses.
7. The timeout is executed.
8. No "close" action is dispatched because `isFocused` is `true`.

In the `DropdownMenu` function component I lifted the `onBlur` handling up to to the list component rather than the individual list items, so the timeout checking is less necessary. But we still have a behavior that keeps the menu open if you `Tab-Shift` backwards onto the dropdown arrow.

**Comment by Ri-Sharma** [comment]
@lindapaiste How about integrating an external library for this functionality? That way we don't have to apply this on our own and we can just add extra functions on top of that.

I was looking around and found [This React Component](https://react-bootstrap.netlify.app/docs/components/dropdowns/), you can check it. We can also add it to all dropdowns in the web app.
