### ISSUE TITLE
Enhance User Interface Language for Password Confirmation

### ISSUE THREAD

**Issue by apsinghdev** [processing/p5.js-web-editor#2560]
### Increasing Access

This proposed idea changes "Please enter a password confirmation." to "Please confirm your password. Because "Please confirm your password" is a more straightforward and commonly understood instruction compared to "Please enter a password confirmation."

![p5-e2](https://github.com/processing/p5.js-web-editor/assets/109718740/2958ffae-7daa-4c47-9b6d-6e28d94ff738)

The phrase "Please confirm your password" enhances access to the p5.js Web Editor by providing clear and user-friendly language. This simplification reduces user confusion (eliminating the need for actions like "checking email" or filling out OTPs) and streamlines the registration and login process. Additionally, it aligns with web application standards and enhances accessibility for a broader user base.

### Feature enhancement details

This feature enhancement aims to change "Please enter a password confirmation." to "Please confirm your password. so that it aligns with web application standards and enhances accessibility by making the instruction simpler.

Can I work on this @raclim and @lindapaiste ?

**Comment by lindapaiste** [comment]
This is related to #2499.  Maybe a duplicate because the ideal solution is the same.  What we have now is "Please enter a ____" for all fields and it does not always make sense.  It's not event translated to other languages 😭 .  We need to move these texts into the [`translations.json`](https://github.com/processing/p5.js-web-editor/blob/develop/translations/locales/en-US/translations.json) file and we need to have a separate massage for each field.

https://github.com/processing/p5.js-web-editor/blob/9e463df39881cb933eea132026d6b2f472c80b4c/client/modules/User/components/AccountForm.jsx#L12

**Comment by apsinghdev** [comment]
> Please enter

I am a bit unclear on "We need to move these texts into the [translations.json](https://github.com/processing/p5.js-web-editor/blob/develop/translations/locales/en-US/translations.json) file and we need to have a separate massage for each field.". can you please provide some sort of reference so that I can understand this issue?

**Comment by raclim** [comment]
A majority of the text for the web editor is populated by using localized data from the `translations.json` files within the [`translations/locales`](https://github.com/processing/p5.js-web-editor/tree/develop/translations/locales) folder. I think @lindapaiste (please correct me if I'm wrong!) was trying to point out that for this element, we're currently generating the "Please enter a" text by directly returning a string rather than pulling it from the JSON files. 

I'm not looking very closely, but I do see the lines "Please enter a password confirmation" in lines 282 and 293 in `translations.json` file so maybe something exists there that hasn't been fully implemented yet?  

I do also agree that it's in the same vein of #2499, and this issue could probably be consolidated into it. I might edit the issue there to reference this one and close this one for now to organize issues!

**Comment by lindapaiste** [comment]
I'm reopening this because I misspoke before.  This is not the same as #2499, which is a buggy behavior that I just fixed.

The text is actually coming from the translation file that @raclim mentioned, and we have the text "Please enter a password confirmation" there.

https://github.com/processing/p5.js-web-editor/blob/a1a5efd44f64f4a449f07379098dcdfe049558eb/translations/locales/en-US/translations.json#L282
https://github.com/processing/p5.js-web-editor/blob/a1a5efd44f64f4a449f07379098dcdfe049558eb/client/utils/reduxFormUtils.js#L76

@apsinghdev I think you're right that **"Please confirm your password"** sounds better.  Do you agree @raclim?

To fix this we would find and replace "Please enter a password confirmation" with "Please confirm your password" in all `translation.json` files (some other languages copy the English.  `ko` is the only one in this case).

**Comment by apsinghdev** [comment]
thanks @lindapaiste for assigning me. I've started working on it.

**Comment by raclim** [comment]
> I think you're right that "Please confirm your password" sounds better. Do you agree @raclim?

Yeah, that does make more sense!
