### ISSUE TITLE
`Report a bug` and `code of conduct` exceeds from about modal when window size is resized

### ISSUE THREAD

**Issue by PiyushChandra17** [processing/p5.js-web-editor#2565]
### p5.js version

2.9.0

### What is your operating system?

None

### Web browser and version

Chrome and 117.0.5938.132

### Actual Behavior

`Report a bug` and `code of conduct` exceeds from about modal when window size is resized
<img width="632" alt="bug" src="https://github.com/processing/p5.js-web-editor/assets/47579287/0988f9c9-52a8-48e6-8537-42fede7b6caf">

### Expected Behavior

`Report a bug` and `code of conduct` should not exceed from about modal when window size is resized

### Steps:
1. Open the editor web app
2. Click on help dropdown
3. Select about option
4. Notice the about modal, position of `Report a bug` and `code of conduct` exceeds when we resize window size (should be inside modal)

**Comment by sanjay-sol** [comment]
@PiyushChandra17 can I work on this ?? 🚀

**Comment by PiyushChandra17** [comment]
@sanjay-sol Feel free to work on this, but also verify from @lindapaiste that is it a bug or intended design. Thanks!

**Comment by sanjay-sol** [comment]
Hello @lindapaiste, I want to inquire if I can address the matter brought up by @PiyushChandra17? I would like to ensure whether that design is intentional or if it might be indicative of a potential issue or bug . Thank you for your assistance.

**Comment by sanjay-sol** [comment]
Hey @lindapaiste  and @raclim , 

In the aforementioned issue, the behavior of the about component has been successfully resolved. Prior to the changes, it appeared as follows:

<img width="500" alt="bug" src="https://github.com/processing/p5.js-web-editor/assets/114111046/6fe29c80-3374-401e-9eba-9ba593cf7818">

Following the alterations, it now appears in an improved state:

<img width="500" alt="Screenshot 2023-11-04 at 3 43 36 PM" src="https://github.com/processing/p5.js-web-editor/assets/114111046/2520f71c-0184-4595-bbbb-ea36835a5f15">


The issue has been effectively addressed, resulting in a more satisfactory outcome.

As there haven't been any merged pull requests for issue #2531 and since it's behaviour also changes when the screen size goes less than 768 px  .
 I've redesign it to the best of my abilities. I kindly request feedback from @raclim and @lindapaiste regarding whether it's appropriate to retain these changes exclusively for issue #2565. If it's preferable to keep the modifications isolated to this specific issue, I'll be happy to re-submit the pull request with the code affecting issue #2531 removed.

**Comment by shree6** [comment]
Hey can i work on this @PiyushChandra17 ??

**Comment by Sahil-6-9** [comment]
Hey can i work on this @PiyushChandra17 ?? I am new to open source . I have solved this issue

**Comment by Sahil-6-9** [comment]
@lindapaiste Is this issue still active

**Comment by raclim** [comment]
Closing to organize and compile issues, linked in Megathread.
