### ISSUE TITLE
Instead of `Alert`, we should use `modal` for deletion of file/folder confirmation

### ISSUE THREAD

**Issue by PiyushChandra17** [processing/p5.js-web-editor#2574]
### Increasing Access

This feature would help increase access in the following ways:

* It will provide much better user interface experience
* It will look much cleaner than the existing one
* Look more professional

<img width="498" alt="delete-conf" src="https://github.com/processing/p5.js-web-editor/assets/47579287/0b34a089-be6d-416d-aab1-f8e4fdcae111">

### Feature enhancement details

We are using `alert` when we try to delete any file/folder in sketch files, instead we should use a `modal` with Yes and No button for the confirmation.

**Comment by Akhilbisht798** [comment]
This is a great Idea and I agree with you that it will make it better looking. I would like to work on this.

**Comment by yashpandey06** [comment]
@PiyushChandra17  are you working on this issue

**Comment by yashpandey06** [comment]
@PiyushChandra17 Can you let me know the platform like discord/slack where we discuss all things related to p5 organization...if you know !!!!

**Comment by PiyushChandra17** [comment]
@yashpandey06  Feel free to work on this, I think as of now we don't have any discord, slack channel but it would be nice and convenient.

**Comment by yashpandey06** [comment]
@PiyushChandra17 ohh thanks a lot!!!!

**Comment by lindapaiste** [comment]
This would be a really low priority for me because I think that the current browser dialogs are fine.  So it seems like a lot of work for not much benefit.

The advantage of going with our own is that we can make it look more similar to the modals that we currently have for things like new file etc.  Honestly I don't think those dialogs look all that great but I do see the advantage of consistency.

Current browser default dialog, for me in Chrome/Windows/light mode (will vary based on browser, OS, and system colors):
![image](https://github.com/processing/p5.js-web-editor/assets/28965286/45d18dce-9223-480f-bcbf-826ec2879900)
Current custom dialog:
![image](https://github.com/processing/p5.js-web-editor/assets/28965286/a3cda932-8504-4f09-a38e-c6437998b2b6)

This is minor but there are advantages to using native alerts because the browser can understand them better.  For example if I navigate away from the editor while a native confirmation is open, it shows a little blue dot over the tab icon.
![image](https://github.com/processing/p5.js-web-editor/assets/28965286/7e97aae6-ad42-4675-8c73-51d1ca57015f)

**Comment by ShashwatPS** [comment]
Can i work on this issue ?

**Comment by yashpandey06** [comment]
@ShashwatPS I am working on it will post pr soon ...you can try some other issues.

**Comment by ShashwatPS** [comment]
Got it.

**Comment by raclim** [comment]
I'm sorry if you all already started some work on this 😭 After reflecting on this issue I think this isn't something we're planning to prioritize in the near future, so I'm going to close this for now!
