### ISSUE TITLE
Web app shakes when switching tab b/w `Privacy policy`, `Terms of use`, and `Code of conduct`

### ISSUE THREAD

**Issue by PiyushChandra17** [processing/p5.js-web-editor#2581]
### p5.js version

2.9.2

### What is your operating system?

Mac OS

### Web browser and version

Chrome and 117.0.5938.132

### Actual Behavior

Web app shakes when switching tab b/w `Privacy policy`, `Terms of use`, and `Code of conduct`

https://github.com/processing/p5.js-web-editor/assets/47579287/4d361e5b-113a-420d-841a-9dd1e7253280

### Expected Behavior

Transition should be smooth and should not shake when switching tab b/w `Privacy policy`, `Terms of use`, and `Code of conduct`

### Steps:
1. Open the editor web app
2. Click on sign up
3. Click on privacy policy
4. Try to switch the tab b/w Terms of use and code of conduct
5. Notice the app shakes
6. Transition should be smooth

**Comment by lindapaiste** [comment]
I've noticed this and I definitely don't love it.  The root cause is that the scrollbar goes away while it's in the loading state from one page to the next, as the loading view is not tall enough to force a scroll. (seems like there's no spinner? and it's just empty?)

I'm not sure what the best solution is.  Maybe we force some outer container div to have a `min-height` of `100vh` such that there is always a scroll.  We expect the actual content to be very long so the `min-height` would only come into to into play while in the loading state.  It could cause an unnecessary scrollbar if a user has an exceptionally huge screen but that seems like an okay tradeoff.

**Comment by Akhilbisht798** [comment]
Hey @lindapaiste, I have worked on this and your `min-height` concept is working preety good.
