### ISSUE TITLE
App is getting crashed  in `localhost` on latest `develop`

### ISSUE THREAD

**Issue by PiyushChandra17** [processing/p5.js-web-editor#2582]
### p5.js version

2.9.2

### What is your operating system?

Mac OS

### Web browser and version

Chrome and 117.0.5938.132

### Actual Behavior

Error: UnknownEndpoint: Inaccessible host: `s3.' at port `undefined'. This service may not be available in the `<your-aws-region>' region.

<img width="1440" alt="Screenshot 2023-11-08 at 2 36 49 PM" src="https://github.com/processing/p5.js-web-editor/assets/47579287/b3e08a9a-8864-4168-a3e7-1185176b511c">

### Expected Behavior

App should work fine

### Steps:
1.Click on My sketches
2.Verify that the app crashes

**Comment by lindapaiste** [comment]
Ok there are two things going on here.  One is that I think your dev environment is not set up properly with S3.  But that brings me to issue two, which is what I'm more concerned with.  The whole app should not crash just because an API request failed.

**We have a lot of `catch` clauses that make assumptions about the shape/type of the `error` variable.**  This has been on my radar for a while, and there are some instances that I've fixed in pending PRs but I don't know if I've got them all.  Maybe I need to create a new issue to track progress (or maybe use this one?).

The problem in the code is right here:
https://github.com/processing/p5.js-web-editor/blob/031c3d01cde6d6ac59c39ce34bc8ab669b3e2a8f/client/modules/IDE/actions/projects.js#L24-L32

`error` could be any caught error, but this code will only work if `error` is an `object` with a property `response` which is an `object`.   If there is no `error.response` then the whole app will crash as you are seeing here.

[Here's a PR](https://github.com/processing/p5.js-web-editor/pull/2353/files#diff-e6c17f77f685be80cb620ab722bc1dc5ffbcd500153cb055b99e19fa0543fa3e) where I fixed a similar problem in a different thunk action, `getCollections`, by using optional chaining to prevent fatal errors if `error.response` is `undefined`.
https://github.com/processing/p5.js-web-editor/blob/0c0163b47e5bec6aeace60841d65ee849898b3c1/client/modules/IDE/actions/collections.js#L27-L33
