### ISSUE TITLE
Why we don't have a discussion tab in this project? A Slack or Discord channel would be nice

### ISSUE THREAD

**Issue by PiyushChandra17** [processing/p5.js-web-editor#2588]
### Increasing Access

This is will help every contributor, maintainer and collaborators communicate with each other effectively, though here @github issues gets the job done but it would be convenient to have. Also these channels will help in collaboration and networking way more better i think 💯 . 

### Feature request details

A Slack or any other channels alternatives is required for this project. @raclim @lindapaiste

**Comment by mhsh312** [comment]
I agree. Things would get done faster as well.

**Comment by yashpandey06** [comment]
I agree with you too ...it will help new contributors to put their thoughts clearly.

**Comment by apsinghdev** [comment]
Yeah ! I fully support it. we should have a discussion channel. I have been stuck in a problem for almost a week but have no one to ask. @lindapaiste @raclim please consider making a discord channel.

**Comment by mhsh312** [comment]
Hi @PiyushChandra17, related but kinda unrelated to this, can I have your discord? I would like to ask you a few questions.

**Comment by raclim** [comment]
There is currently [a discord channel](https://discord.gg/SHQ8dH25r9) and a [Discourse forum](https://discourse.processing.org/) for p5.js and Processing! 

We have considered opening up the Discussion tab for this project, but ultimately decided to streamline where conversations are happening as much as possible since we already have these two available. However, we could experiment with using Github's 'Discussions' feature if you all feel that would be better than switching between Github and Discord/Discourse (though I do feel like there is probably much higher engagement/variety of contributors there). Let me know and we can open one up!

I also just want to note that we don't necessarily emphasize speed in the development process here, and want to try to encourage approaching what we want to integrate deliberately and thoughtfully, while also considering the varying schedules/commitments of this project's contributors.

**Comment by apsinghdev** [comment]
hi @raclim i have fully set up web-editor in docker and it's working fine but whenever I am making changes in the local code they are not getting executed on localhost. when I terminate the container and start is again only then I am able to see the changes. And because of this my whole contribution process is stuck. I have tried a lot but not able to fix it, please help me a bit.

if any of you @PiyushChandra17 @yashpandey06 @mhsh312 guys know its solution then please suggest me.

**Comment by mhsh312** [comment]
Same thing happened to me with the docker installation so now I run the manual installation and it runs fine. Tbf I already had the MERN stack installed on my computer so a manual installation made sense anyway.

**Comment by apsinghdev** [comment]
thanks @mhsh312 I am going to do the same.

**Comment by raclim** [comment]
Just want to note here that I opened up the [Discussion tab](https://github.com/processing/p5.js-web-editor/discussions) for this repo, so please feel free to utilize the space there as well!
