### ISSUE TITLE
Inability to Replace Lines using Alt + ArrowKeys

### ISSUE THREAD

**Issue by perminder-17** [processing/p5.js-web-editor#2595]
### Increasing Access

Pressing Alt + ArrowKeys should replace lines, however, currently, it doesn’t execute the expected behavior.

### Expected behaviour
When pressing Alt + Up/Down ArrowKeys, the lines should be replaced with the lines above or below the current cursor position.
### Current behaviour
 Alt + ArrowKeys does not perform the line replacement as anticipated.

### This feature is essential for efficient coding and is commonly used in various code editors. Its absence hampers the workflow and efficiency.

**Comment by perminder-17** [comment]
Like in V.S code we can use alt + up/down arrow keys something like

https://github.com/processing/p5.js-web-editor/assets/127239756/05525add-7218-4b45-a225-18a2aee3743c

@lindapaiste @raclim @PiyushChandra17 needs your suggestion regarding this. It is very difficult for coders like us to replace lines by copying each line and then make space for, and then pasting the line where required.

**Comment by mhsh312** [comment]
I am interested in knowing how this will work out. From my understanding, the p5 editor uses [Code Mirror](https://codemirror.net/) to handle the code editor. So that would mean it all comes down whatever the current Code Mirror version (v5) being used supports line shifting or not. There's also plans for switching to v6 in the future so there's that too.

**Comment by apsinghdev** [comment]
nice idea @perminder-17 ! it would increase the usability of the editor. but as per my knowledge code mirror v5 doesn't provide this feature so I think this would only be possible in upcoming versions of Code Mirror

**Comment by perminder-17** [comment]
It would be great if @raclim and @lindapaiste share there thoughts on this🙂

**Comment by mhsh312** [comment]
So I looked into the [Codemirror manual](https://codemirror.net/5/doc/manual.html#commands) and there is no inbuilt function for shifting lines in the default keymap. However, CodeMirror supports the [Sublime Text keymap](https://codemirror.net/5/demo/sublime.html) that has the functions `swapLineUp` and `swapLineDown` which I believe does the job. 

So, my idea is we should import the sublime text keymap and only activate the `swapLineUp` and `swapLineDown` (so the other functions do not interfere with our current ones) and give it the `Alt+Up` key-binding to achieve the functionality we need. 

If for some reason we do not want to import the Sublime Keymap, we can just create a function similar to this: 

```
cmds.swapLineUp = function(cm) {
    if (cm.isReadOnly()) return CodeMirror.Pass
    var ranges = cm.listSelections(), linesToMove = [], at = cm.firstLine() - 1, newSels = [];
    for (var i = 0; i < ranges.length; i++) {
      var range = ranges[i], from = range.from().line - 1, to = range.to().line;
      newSels.push({anchor: Pos(range.anchor.line - 1, range.anchor.ch),
                    head: Pos(range.head.line - 1, range.head.ch)});
      if (range.to().ch == 0 && !range.empty()) --to;
      if (from > at) linesToMove.push(from, to);
      else if (linesToMove.length) linesToMove[linesToMove.length - 1] = to;
      at = to;
    }
    cm.operation(function() {
      for (var i = 0; i < linesToMove.length; i += 2) {
        var from = linesToMove[i], to = linesToMove[i + 1];
        var line = cm.getLine(from);
        cm.replaceRange("", Pos(from, 0), Pos(from + 1, 0), "+swapLine");
        if (to > cm.lastLine())
          cm.replaceRange("\n" + line, Pos(cm.lastLine()), null, "+swapLine");
        else
          cm.replaceRange(line + "\n", Pos(to, 0), null, "+swapLine");
      }
      cm.setSelections(newSels);
      cm.scrollIntoView();
    });
  };
```
(taken from the [Sublime Text Keymap](https://[codemirror.net/5/keymap/sublime.js](https://codemirror.net/5/keymap/sublime.js)), some modifications might be needed for the default keymap)

I am ready to code this if you agree. @lindapaiste

**Comment by lindapaiste** [comment]
> So I looked into the [Codemirror manual](https://codemirror.net/5/doc/manual.html#commands) and there is no inbuilt function for shifting lines in the default keymap. However, CodeMirror supports the [Sublime Text keymap](https://codemirror.net/5/demo/sublime.html) that has the functions `swapLineUp` and `swapLineDown` which I believe does the job.
> 
> So, my idea is we should import the sublime text keymap and only activate the `swapLineUp` and `swapLineDown` (so the other functions do not interfere with our current ones) and give it the `Alt+Up` key-binding to achieve the functionality we need.

Great find!  I did not realize that this was already supported by the Sublime keymap.  

But now I'm very confused and I have a lot of questions.  I thought this was a request for a new feature but it might be a debugging task because we're actually already loading the Sublime keymap - so why doesn't this work right now?

https://github.com/processing/p5.js-web-editor/blob/5d39d49b98a8604f30a50c8cd9db7aa359ca6b3a/client/modules/IDE/components/Editor/index.jsx#L27
https://github.com/processing/p5.js-web-editor/blob/5d39d49b98a8604f30a50c8cd9db7aa359ca6b3a/client/modules/IDE/components/Editor/index.jsx#L117

---

Edit: It does work!  But with different keys than what's suggested.  It's `Ctrl-Shift-Up` rather than `Alt-Up`.  Is that good enough?  Or should add additional key bindings.

**Comment by mhsh312** [comment]
I think `Alt+Up` is the industry standard so the key bindings should be changed. I will be interested as to where the changes will be done because I cannot find the keybinding object anywhere. ([Maybe this?](https://codemirror.net/5/doc/manual.html#:~:text=extraKeys%3A%20object,key%20map%20value.))
 Also it's great that p5 editor was already running with Sublime Key Map.

**Comment by lindapaiste** [comment]
> I think `Alt+Up` is the industry standard so the key bindings should be changed. 

I wonder if there are other command where VSCode differs from Sublime and which we use.  A lot of them are the same.  That is, a clear industry standard.  So that's nice.  `Alt+Up` is what VSCode uses but I don't know that it would be considered industry standard.  I use JetBrains/WebStorm as my IDE and they use `Alt+Up` to go to the previous function block.  Their swap line command is `Shift-Alt-Up`.  A third option! 🤯 So there may be no standard here.

https://code.visualstudio.com/docs/getstarted/keybindings
https://docs.sublimetext.io/reference/keyboard_shortcuts_win.html
https://shortcuts.design/tools/toolspage-sublimetext/

> I will be interested as to where the changes will be done because I cannot find the keybinding object anywhere. ([Maybe this?](https://codemirror.net/5/doc/manual.html#:~:text=extraKeys%3A%20object,key%20map%20value.)) Also it's great that p5 editor was already running with Sublime Key Map.

Yup, `extraKeys` is what we would use.  We have the Sublime addon installed which registers its commands to CodeMirror so we can reference them by name.  Like we do for the ones from the Emmet plugin:
https://github.com/processing/p5.js-web-editor/blob/5d39d49b98a8604f30a50c8cd9db7aa359ca6b3a/client/modules/IDE/components/Editor/index.jsx#L164-L165

If you want to see all of the available commands, you can add this to the Editor while running on localhost:
```
console.log(CodeMirror.commands);
```

https://codemirror.net/5/doc/manual.html#commands

**Comment by mhsh312** [comment]
> I wonder if there are other command where VSCode differs from Sublime and which we use. A lot of them are the same. That is, a clear industry standard. So that's nice.
> https://code.visualstudio.com/docs/getstarted/keybindings
> https://docs.sublimetext.io/reference/keyboard_shortcuts_win.html
> https://shortcuts.design/tools/toolspage-sublimetext/

If programmers could decide on a universal industry standard, we would have flying cars by now. :P
Although I am biased towards `Alt-Up` and `Alt-Down` because I am VS-Code gang, I think most other frequently used shortcuts are same in both so we don't need to worry about changing all the differences.

> Yup, `extraKeys` is what we would use. We have the Sublime addon installed which registers its commands to CodeMirror so we can reference them by name. Like we do for the ones from the Emmet plugin:

Makes sense. I just checked and adding this to the code implements the feature:

```
'Alt-Up': 'swapLineUp',
'Alt-Down': 'swapLineDown',
```

Should I just make a PR and we get this done?
