### ISSUE TITLE
Translate 'Autocomplete Hinter' into Hindi

### ISSUE THREAD

**Issue by apsinghdev** [processing/p5.js-web-editor#2601]
### Increasing Access

in this, all the headings and buttons are in Hindi except 'Autocomplete Hinter'

![p5-issue2](https://github.com/processing/p5.js-web-editor/assets/109718740/4b6a8791-8126-43b9-8786-d997672f527f)

### Feature enhancement details

it would be better if we convert this in Hindi as well so that it matches the language of whole page.

**In order to reproduce it**

- got to https://editor.p5js.org/
- on Top-right corner, click on 'English' button
- then select Hindi as Language
- then click on settings wheel
- and notice 'Autocomplete Hinter' in सामान्य सेटिंग्स tab

**Comment by avengsum** [comment]
@apsinghdev After looking into the issue I got to know that this is not only a problem with Hindi but the Autocomplete Hinter is not translated into any language.
![france](https://github.com/processing/p5.js-web-editor/assets/123776031/4c220626-387a-4219-a40a-286c40c2ed96)

so @apsinghdev  @lindapaiste assign me this issue so that I start working on the translation of Autocomplete Hinter for all languages

**Comment by mhsh312** [comment]
This has already been mentioned [here](https://github.com/processing/p5.js-web-editor/issues/2591#issuecomment-1806904032).

**Comment by apsinghdev** [comment]
> This has already been mentioned [here](https://github.com/processing/p5.js-web-editor/issues/2591#issuecomment-1806904032).

hey @mhsh312 ! I am not able to see its reference in #2591. can you please explain? or have you fixed it?

**Comment by mhsh312** [comment]
![image](https://github.com/processing/p5.js-web-editor/assets/135870090/fc7a642e-81e3-4f5c-8b20-81b440977553)
