### ISSUE TITLE
Refactor legacy `Searchbar` Class component into Functional component

### ISSUE THREAD

**Issue by PiyushChandra17** [processing/p5.js-web-editor#2602]
### Increasing Access

This would help in the following ways:
* Functional based components are modern way of writing clean and concise components
* Less line of code
* Easy to read and debug
* use of `useState` , `useEffect` and `useRef` hooks comes into play
* Easy to integrate with the `Redux` workflow

### Feature enhancement details

We should refactor the old legacy class components into more modern way `Functional` components

**Comment by mrkirthi-24** [comment]
Hey @PiyushChandra17, I would like to work on this issue.

**Comment by mhsh312** [comment]
This issue was already raised [here](https://github.com/processing/p5.js-web-editor/issues/2358). There are already multiple PRs related to the searchbar there. One of the maintainers already mentioned [here](https://github.com/processing/p5.js-web-editor/issues/2599#issuecomment-1808629909) that checking these PRs is a long process because shifting from class to functional components is a tedious task that frequently breaks something.

**Comment by PiyushChandra17** [comment]
@mhsh312 I think in the long term, functional component is the way to go as it's more modern and up to date. Yes i agree with @lindapaiste on [this](https://github.com/processing/p5.js-web-editor/issues/2599#issuecomment-1808629909]) one. Closing this issue 👍
