### ISSUE TITLE
MobileNav `username` color does not match with logo color

### ISSUE THREAD

**Issue by PiyushChandra17** [processing/p5.js-web-editor#2604]
### Increasing Access

Currently mobile nav username default color is "blue" which seems quite odd. Color must be consistent throughout the app.
<img width="492" alt="Screenshot 2023-11-14 at 3 26 35 PM" src="https://github.com/processing/p5.js-web-editor/assets/47579287/6d316bc8-0210-4486-bb0b-32356ff7a349">

### Feature enhancement details

We need to change the mobile nav username color to match the logo color. ie `ed225d`

**Comment by avengsum** [comment]
while working on this issue i found out that when we change the color npm run test fails

**Comment by lindapaiste** [comment]
@PiyushChandra17 This was definitely intentional and not a mistake.
https://www.figma.com/file/27wGlxCRns7tyXoEIbcmTA/p5-Mobile---2020?type=design&node-id=1493-5066&mode=design&t=ML3V8CL6ShkVjrzL-0
https://www.figma.com/proto/27wGlxCRns7tyXoEIbcmTA/p5-Mobile---2020?node-id=798-11180

@avengsum Some components have snapshot tests and you need to update the snapshots if you change the appearance (HTML or CSS)

**Comment by PiyushChandra17** [comment]
@lindapaiste Thank you for the information. Closing this issue 👍
