### ISSUE TITLE
Fixing translations in the Hindi language

### ISSUE THREAD

**Issue by mhsh312** [processing/p5.js-web-editor#2609]
### What is your operating system?

Windows

### Web browser and version

Microsoft Edge: 118.0.2088.76 (Official build)

### Actual Behavior

As mentioned [here](https://github.com/processing/p5.js-web-editor/issues/2591#issuecomment-1806904032), the translations of the following phrases is missing for the Hindi language:
- [x] Nav.Sketch.Title
- [x] Nav.Auth.Asset
- [x] Nav.File.Open
- [x] Nav.File.Duplicate
- [x] Nav.File.Share
- [x] SocialAuthButton.LogoARIA
- [x] About.Forum
- [x] About.PrivacyPolicy
- [x] About.TermsOfUse
- [x] About.CodeOfConduct
- [x] Preferences.FontSize
- [x] Preferences.SetFontSize
- [x] Preferences.AutocompleteHinter
- [x] Preferences.PlainText
- [x] Preferences.AutocompleteHinterOnARIA
- [x] Preferences.AutocompleteHinterOffARIA
- [x] KeyboardShortcuts.CodeEditing.ColorPicker
- [x] Common.p5logoARIA
- [x] NewFileForm.Placeholder
- [x] NewFolderForm.Placeholder
- [x] ResetPasswordForm.EmailARIA
- [x] AccountForm.EmailARIA
- [x] AccountView.SocialLogin
- [x] AccountView.AccountTab
- [x] APIKeyList.Name
- [x] APIKeyList.Actions
- [x] SignupForm.EmailARIA
- [x] AssetList.HeaderName
- [x] AssetList.HeaderSketch
- [x] Feedback.Title
- [x] Collection.HeaderName
- [x] CollectionCreate.FormLabelARIA
- [x] DashboardTabSwitcher.Assets
- [x] CollectionList.HeaderName
- [x] SketchList.HeaderName
- [x] Cookies.Header
- [x] Cookies.Body
- [x] Cookies.AllowAll
- [x] Cookies.AllowEssential
- [x] Legal.PrivacyPolicy
- [x] Legal.TermsOfUse
- [x] Legal.CodeOfConduct

I thought of creating this tasked issue because I saw multiple people posting about finding individual un-translationed phrases here and there and this seemed better than creating issues for each one separately over a period of time. 
This way, the whole process can be tracked easily making everyone contribute to a one compiled issue.

### Expected Behavior

All the phrases should be displayed in Hindi.

### Steps to reproduce

1. Open the editor web app
2. Click on language preferences
3. Try changing the different languages and observe the mentioned phrases
4. Verify that they do not get translated in Hindi

**Comment by apsinghdev** [comment]
Literally a nice idea, @mhsh312! Is this the final list of phrases that needs to be translated into Hindi? I am asking this because I have gone through the translations.json file, and there are other phrases that are either missing or copied from the English, in addition to the list of phrases provided above.

for example -

`Nav.File.Open`
`Nav.File.Duplicate`
`Nav.File.Share`
`Preferences.PlainText`

just name a few .

Also I am assuming that we are not translating in Absolute HIndi because that won't be Understandable. We are Translating in hindi words that are prevalent and known by majority of the hindi speakers. So if there is any sort reference /library/module from where we are taking these translations, provide some suggestions. 
need your thoughts @lindapaiste

**Comment by mhsh312** [comment]
I don't think it's a final list. These are the ones that lindapaiste found so far. I will keep adding more to these. 
About where we could get these translations from, you can check out the PR that I did for the first translation issue (linked in this current issue). I have mentioned how I translated that practicular phrase. Since the PR was merged, I assume that change is acceptable by the maintainers.

**Comment by umangutkarsh** [comment]
Maintainers, @lindapaiste  @mhsh312 . I've opened a pr to fix the translation-error-issue of 'AutocompleteHinter', please review it and provide feedback if anything else is required.
Thanks.

**Comment by umangutkarsh** [comment]
Hi @lindapaiste . I've opened some more PRs. Please take out your time and review those. And if there's anything which needs to be worked upon in these PRs and the other PRs, then please let me know. 
Thanks

**Comment by umangutkarsh** [comment]
> Hi @lindapaiste . I've opened some more PRs. Please take out your time and review those. And if there's anything which needs to be worked upon in these PRs and the other PRs, then please let me know. Thanks

@lindapaiste . Any updates? Or are there any changes required in the PRs?

**Comment by ajaysharma-dev** [comment]
I've added Hindi translation of Cookies object  #2706 .

**Comment by shaleshkalyan** [comment]
Added hindi translation of Legal object #2708

**Comment by reach2saksham** [comment]
Hello Maintainers, 

I compared the English translation file with the Hindi translation JSON file and have added all the missing keys in the pull request #2729.

Request you to kindly review and merge.

Regards,
Saksham Jain
IIT Roorkee

**Comment by swrno** [comment]
Hello @umangutkarsh, #2691 and #2699 are almost the same, the only difference is #2699 converts the translation in all available languages but #2691 translates only in Hindi. It will cause many problems when language is changed from one to another. Always we have to keep in mind and check our codes
multiple times before making any PRs, because it can cause errors in production.

What do you think @raclim @lindapaiste ?

**Comment by umangutkarsh** [comment]
> Hi @lindapaiste . I've opened some more PRs. Please take out your time and review those. And if there's anything which needs to be worked upon in these PRs and the other PRs, then please let me know. Thanks

Hey @lindapaiste . Hope it doesn't burden you, but any updates?
Thanks :)

**Comment by raclim** [comment]
Thanks for all of your work and input here on this! 

I just reviewed the file and it seems like a translation was ascribed to all of the listed phrases. I'm going to close this for now since it seems to be complete, but please definitely feel free to open up a new issue if any changes or new translation fixes are needed!
