### ISSUE TITLE
My Staff List (Sketches and Collections) are not readable with dark mode on Mobile Device

### ISSUE THREAD

**Issue by shibomb** [processing/p5.js-web-editor#2625]
### What is your operating system?

None

### Actual Behavior

My Staff List (Sketches and Collections) are not readable with dark mode on Mobile Device.

![Sketches 2023-11-22 1 31 59](https://github.com/processing/p5.js-web-editor/assets/958471/58243213-66a9-484c-8997-170dd1db7954)

### Expected Behavior

The background color of the rows should be dark.
![Sketches 2023-11-22 1 41 15](https://github.com/processing/p5.js-web-editor/assets/958471/2d260c44-c943-422b-8d12-a10ad11df2f7)

### Steps:
1. Open Web Editor on Mobile Device.
2. Set dark mode. 
3. Open My Staff.

**Comment by lindapaiste** [comment]
Good catch!  There might be some colors that are hardcoded instead of using theme variables.

Edit: it seems like we **are** using variables, but those variables don't have the colors that we want for the dark and contrast themes.  We may want to create new variables instead of reusing these `search-` and `modal-` ones.  We've talked about creating more generic/standardized properties like `surface-0`, `surface-1` etc. but that has never been implemented.
https://github.com/processing/p5.js-web-editor/blob/fcbc05e2e65d934ea5416599b60f71592aedecf7/client/styles/components/_sketch-list.scss#L36-L39
https://github.com/processing/p5.js-web-editor/blob/fcbc05e2e65d934ea5416599b60f71592aedecf7/client/styles/components/_sketch-list.scss#L53-L55

https://github.com/processing/p5.js-web-editor/blob/fcbc05e2e65d934ea5416599b60f71592aedecf7/client/styles/abstracts/_variables.scss#L173
https://github.com/processing/p5.js-web-editor/blob/fcbc05e2e65d934ea5416599b60f71592aedecf7/client/styles/abstracts/_variables.scss#L151
