### ISSUE TITLE
Position of `cross` in about modal is not aligned `center` in blue border box

### ISSUE THREAD

**Issue by PiyushChandra17** [processing/p5.js-web-editor#2647]
### p5.js version

2.9.3

### What is your operating system?

None

### Actual Behavior

Position of `cross` in about modal is not aligned `center` in blue border box

<img width="55" alt="about-x" src="https://github.com/processing/p5.js-web-editor/assets/47579287/169411c7-ccaf-45f8-9a56-75668ddd791e">

### Expected Behavior

Position of `cross` in about modal should be aligned `center` in blue border box

### Steps:
1. Open the editor web app
2. Open the about modal
3. Click on Close
4. Notice it's not aligned center wrt box

**Comment by Subhrajit-Dutta** [comment]
Can I work on this?

**Comment by lindapaiste** [comment]
We definitely have some asymmetric padding on the `overlay__close-button` class.  Right now the "x" is closer to the right than to the top and I'm not sure if we want to maintain the current position?  If so, we can use a negative margin or adjust the padding on the parent to keep in the same place while having balanced padding on all 4 sides of the button.

**Comment by raclim** [comment]
Thanks for pinpointing this! To update, I've brought on a designer to redesign the About page, which should be completed by around next month. Part of the redesign includes turning the About modal into a fullscreen page, which will remove the "x". Since this does not have a "high priority" label and with the new designs to come, I'm going to close this issue and the associated PRs for now. However, please be on the lookout for the upcoming designs!
