### ISSUE TITLE
Editor Component should be changed to Functional Component

### ISSUE THREAD

**Issue by Typicalcodes** [processing/p5.js-web-editor#2687]
### Increasing Access

It is important to update components according to new Functional components.

### Feature enhancement details

The component uses useRef for setting a reference to the Codemirror instance which can be used in any useEffect and function. I am referencing a pull request for these issue.

**Comment by lindapaiste** [comment]
We've tried converting both `Editor` and `ConsoleInput` to functional components in the past, but it's very hard to get these CodeMirror components working properly with hooks since the CodeMirror instance has its own internal state.  It's hard to get the correct dependencies on your callback function so that we don't have stale closures.   I've tried converting `Editor` myself and gotten to the point where I realize that it's a complicated mess and it isn't worth it.  We decided that it's best to keep them as class components for now since we know that they work.  I will check out your PR but I'm skeptical.

See this comment for some of the issues that we had on the `ConsoleInput`: https://github.com/processing/p5.js-web-editor/pull/2409#issuecomment-1722600806

**Comment by Typicalcodes** [comment]
Please see my latest commit. I have changed a lot of things and fixed most.
