### ISSUE TITLE
Sidebar's "Toggle project options" button overlaps the sidebar title "Sketch Files" when dragged to minimum width.

### ISSUE THREAD

**Issue by Ri-Sharma** [processing/p5.js-web-editor#2698]
### Actual Behavior

The sidebar title "Sketch Files" gets overlapped by the sidebar "Toggle project option" button.

![Screenshot 2023-12-07 215550](https://github.com/processing/p5.js-web-editor/assets/80570105/ceb320f5-bce2-47cc-84e7-8113edba9b36)

### Expected Behavior

When dragged to minimum width it should look like this.

![Screenshot 2023-12-07 221046](https://github.com/processing/p5.js-web-editor/assets/80570105/a71892a5-6b7a-454a-b3d6-bc6ccf08921a)

### Steps to reproduce

Drag the sidebar to it's minimum width.

**Comment by aryanas159** [comment]
Can I be assigned to this issue.

**Comment by Ri-Sharma** [comment]
> Can I be assigned to this issue.

Hey @aryanas159 thanks for your interest, but I am currently working on this.

**Comment by lindapaiste** [comment]
I'm fine with this either way.  I don't have a problem with the current overlap because it only happens if the user drags the sidebar too small, and I think it's to be expected in that case.  But if we want to adjust the width I don't have a problem with that either. 

Note that "Sketch Files" is a translated string, so some languages will still have an overlap even with a larger width because the text might be longer.

I checked to see what width we are using on mobile but it's half of the screen rather than a fixed pixel amount.  That's enough to prevent overlap on all but the very smallest devices (<280px for English).

**Comment by Ri-Sharma** [comment]
@lindapaiste  yeah I forgot about the translations in other languages, and if we keep the min-width according to the language in which the "Sketch Files" length is longest it would look weird.
And I think we do not need to concern about the mobile mode because half the screen size is enough.

If we just increase the min-width to 150px from 125px (i.e. already implemented min-width) the default files will not get squashed if sidebar is dragged to min-width.
![Screenshot 2023-12-07 215550](https://github.com/processing/p5.js-web-editor/assets/80570105/a9d7d8ee-71e6-4f35-82b9-05fe2b23f52d)

So should I proceed with this?

**Comment by lindapaiste** [comment]
> So should I proceed with this?

@raclim do you have an opinion?

**Comment by raclim** [comment]
@lindapaiste I don't think I have a strong leaning either way as well! I guess it wouldn't hurt to try it out!
