### ISSUE TITLE
About Block content overflowing on changing language

### ISSUE THREAD

**Issue by swrno** [processing/p5.js-web-editor#2700]
### p5.js version

v1.9.0

### What is your operating system?

Windows

### Actual Behavior

![Screenshot (40)](https://github.com/processing/p5.js-web-editor/assets/94161758/fcc66310-1e54-4610-be24-9c42ce4dec7d)

### Expected Behavior

![Screenshot (38)](https://github.com/processing/p5.js-web-editor/assets/94161758/15c3923b-6f5d-4727-afd6-a63897cafd2b)

### Steps:
1. Open p5.js Web Editor 2. 
2. Change the language to Italiano
3. Toggle the About Block

**Comment by aryanas159** [comment]
Can I work on this issue?

**Comment by afrinxnahar** [comment]
It's overflowing for Spanish, Turkish and Ukranian languages also

**Comment by lindapaiste** [comment]
Thanks for catching this.  The language-dependent part here is the width of the text in the columns and this wrapping happens for Italian etc. even on very wide screens 😭.  What we want is for the long text "Codice di comportamento" to wrap _within_ the column rather than causing the whole column to wrap.

Not much thought was put into the responsive breakpoints for the About modal and it's become clear that there's a lot of problems with it.  All I did was put in a `flex-wrap: wrap` to make it somewhat okay.  In the long term we probably want to go back to the drawing board and really think about what it should look like at each breakpoint.  It's not a good design when it's at that two-column wide stage.

We should definitely fix this but it's related to a bunch of other issues regarding this modal and it might make sense to address them all at once with a better responsive design.

**Comment by KrishavRajSingh** [comment]
I want to work on this

**Comment by hemanggs** [comment]
Can i be assigned this issue ,if anyone  else is not working on it.
