### ISSUE TITLE
Content not aligned 

### ISSUE THREAD

**Issue by gunjjoshi** [processing/p5.js-web-editor#2748]
### Increasing Access

Rectifying this would result in proper layout and uniformity.

### Feature enhancement details

The current CSS is causing inefficient layout shift, as shown in the screenshot below. The "x" element is taking up extra width, pushing the rest of the content to the left. This can be jarring for users and make the page look unprofessional.

<img width="1470" alt="Screenshot 2023-12-21 at 1 22 16 AM" src="https://github.com/processing/p5.js-web-editor/assets/67432819/000ae2fd-a029-4cb4-b30c-c3e7b1ca146c">

**Comment by raclim** [comment]
Thanks for raising this issue! Since I don't think we're going to have a release over the next two week and we're planning to take down this modal on January 15th, we probably will not address minor issues with the fundraiser modal for now. However, we'll definitely try to keep these in mind for the one next year!
