### ISSUE TITLE
CopyableInput is a class component

### ISSUE THREAD

**Issue by rahulkhattri0** [processing/p5.js-web-editor#2752]
### Increasing Access

This particular component that is being used in the share modal is implemented using legacy react class component.

### Feature enhancement details

This component can be converted to a functional component.

**Comment by rahulkhattri0** [comment]
Hope this helps!

**Comment by lindapaiste** [comment]
I converted this one a long time ago in #2360

**Comment by rahulkhattri0** [comment]
Ok no problem, can you tell me some other component I can convert please.

**Comment by raclim** [comment]
Thanks for your work on this so far! Since this was already opened and addressed, I'm going to close these for now! 

I'm not sure which exact other components might need to be converted at the moment, but we do have a lot of PRs already in queue for converting them. We would definitely be open to having any issues addressed that don't have a PR yet!
