### ISSUE TITLE
Enhancing Access: Adding More Languages to Improve Accessibility in p5.js Web Editor

### ISSUE THREAD

**Issue by swrno** [processing/p5.js-web-editor#2780]
### Increasing Access

As a contributor, I propose the addition of several new languages to the p5.js Web Editor to enhance accessibility for native speakers. The inclusion of these languages will provide a more user-friendly experience, enabling a broader audience to engage with and benefit from the p5.js Web Editor. 

### Feature enhancement details

The suggested languages include 

- [Arabic (ar)](https://gist.github.com/raclim/0f05ed08c473625f2a52d37133cd8da0)
- [Russian (ru)](https://gist.github.com/raclim/223bedc158cb4523899e6e8cf3a8d8b3)
- [Portuguese (Portugal) (pt-PT)](https://gist.github.com/raclim/bfce2162f49eb77037fa8f2dfe205553)
- [Greek (el)](https://gist.github.com/raclim/a3ae17d8e0d8f27586e6c0d7614a9df7)
- [Hebrew (he)](https://gist.github.com/raclim/2a29e03be701a07d754dedf34413571c)
- [Polish (pl)](https://gist.github.com/raclim/5b4f43d386c6a0eb14f33f748351cab5)
- [Vietnamese (vi)](https://gist.github.com/raclim/71bc5989b49ef0b5f7cd491fd8f824a2)
- [Thai (th)](https://gist.github.com/raclim/06d39539b80ad38c5f631ff7d9c7b817)
- [Indonesian (id)](https://gist.github.com/raclim/9cc888b46363c0cbcbadeab2967b5eb5)
- [Malay (ms)](https://gist.github.com/raclim/5144302051c57a7877b8d028ce8b207c)
- [Filipino (fil)](https://gist.github.com/raclim/247c65496302c5b7f6d6a6f410ad7b2f)
- [Romanian (ro)](https://gist.github.com/raclim/4102bf442772c047ab1363cbba94f075)
- [Czech (cs)](https://gist.github.com/raclim/93aba49702c3844f91a185a590b584d4)
- [Slovak (sk)](https://gist.github.com/raclim/d2efeb43412b6407d8201650febfe740)
- [Azerbaijani](https://gist.github.com/raclim/14d6ca00cec24e701b5fa65f97f9733a)
- [ ] Dutch (nl)

### How Do I Add Feedback to These Translations? 
Feedback for each translation's gist can be provided by commenting suggestions at the bottom of each file, or by [forking and cloning the gist] (https://docs.github.com/en/get-started/writing-on-github/editing-and-sharing-content-with-gists/forking-and-cloning-gists). If you choose to fork and clone the gist, you can add a comment that contains a link to the forked gist that has the suggested updates.

**Comment by Swarnendu0123** [comment]
Hello @lindapaiste @raclim! I've been dedicated to addressing this issue for the past month. I would appreciate it if you could review my work and provide feedback. This will allow me to make any necessary changes based on your input. Thank you!

**Comment by swrno** [comment]
Hello @lindapaiste @raclim! I've been dedicated to addressing this issue for the past month. I would appreciate it if you could review my work and provide feedback. This will allow me to make any necessary changes based on your input. Thank you!

Should I convert all those PRs into 1 PR? or is it okey?

**Comment by raclim** [comment]
Thanks for your work on this so far! 

To be honest, I'm a little hesitant about adding in these translations since I'm not sure if we're able to attentively maintain all of these (which also ties into https://github.com/processing/p5.js-web-editor/issues/1427). Although I agree that having more languages is mostly more beneficial than not having them at all, I think it would also be ideal to ensure we can have native speakers vet these as well. I think we would also want to consider if we need to make any UI changes to the language dropdown since we're adding a good number of them here. 

@limzykenneth would you be able to add any insight on this as well? I think I'm a bit unsure here!

**Comment by swrno** [comment]
![Screenshot (68)](https://github.com/processing/p5.js-web-editor/assets/94161758/14cd4fba-1499-40e9-90b7-99fb3c6619ce)
Well I feel, we have to add a scrollbar to the dropdown, but before that we need to add a fixed height to the dropdown and we are done. 
Can you suggest me what should be the height of dropdown? also you can suggest, if any other style changes is required.

**Comment by limzykenneth** [comment]
@Swarnendu0123 Are you a fluent user of these languages and if not how did you come about these translations? I'm highly wary of machine translated strings that are not vetted by a fluent user of said language and would strongly recommend not accepting them as is.

Take for example the Malay translation of "Tidy Code" and "Tidy" which is translated as "Kod Rapi" and "Rapi". As direct translations they are fine, however it misunderstood the context of the translation here because "Rapi" is an adjective where as "Tidy" in this case is meant to be a verb. The more appropriate translations should have been something like "Kemas Kod" (might even need some adjustment grammar-wise as I'm pretty rusty). I can't vet any of the other languages but it is possible there are more issues like this.

That's also not to mention the most extreme case of Arabic where all the text will be aligned in the wrong direction.

**Comment by Swarnendu0123** [comment]
> @Swarnendu0123 Are you a fluent user of these languages and if not how did you come about these translations? I'm highly wary of machine translated strings that are not vetted by a fluent user of said language and would strongly recommend not accepting them as is.
> 
> Take for example the Malay translation of "Tidy Code" and "Tidy" which is translated as "Kod Rapi" and "Rapi". As direct translations they are fine, however it misunderstood the context of the translation here because "Rapi" is an adjective where as "Tidy" in this case is meant to be a verb. The more appropriate translations should have been something like "Kemas Kod" (might even need some adjustment grammar-wise as I'm pretty rusty). I can't vet any of the other languages but it is possible there are more issues like this.
> 
> That's also not to mention the most extreme case of Arabic where all the text will be aligned in the wrong direction.

I completely agree with you, but we can validate the translations if and only if any native speaker would verify it. What we can do, for now, we can do some modifications if required, and merge them. When the native speakers come to the web editor, they can identify, if there is any fault in our translation. Then they can eventually reach us via GitHub and give us suggestions on what the actual translation should be.

You mentioned some changes in Malay, can you please validate the Malay PR completely, so that if there are any changes, I can fix it.

**Comment by swrno** [comment]
> @Swarnendu0123 Are you a fluent user of these languages and if not how did you come about these translations? I'm highly wary of machine translated strings that are not vetted by a fluent user of said language and would strongly recommend not accepting them as is.

I completely agree with you, but we can validate the translations if and only if any native speaker would verify it. What we can do, for now, we can do some modifications if required, and merge them. When the native speakers come to the web editor, they can identify, if there is any fault in our translation. Then they can eventually reach us via GitHub and give us suggestions on what the actual translation should be.

> Take for example the Malay translation of "Tidy Code" and "Tidy" which is translated as "Kod Rapi" and "Rapi". As direct translations they are fine, however it misunderstood the context of the translation here because "Rapi" is an adjective where as "Tidy" in this case is meant to be a verb. The more appropriate translations should have been something like "Kemas Kod" (might even need some adjustment grammar-wise as I'm pretty rusty). I can't vet any of the other languages but it is possible there are more issues like this.

You mentioned some changes in Malay, can you please validate the Malay PR completely, so that if there are any changes, I can fix it. As the main motivation is to increase the accessibility for the local users.

> That's also not to mention the most extreme case of Arabic where all the text will be aligned in the wrong direction.

**Comment by raclim** [comment]
Thanks @limzykenneth! 

Hmm, @Swarnendu0123 I think then maybe for now we can give these translations some more time and wait to see if we can get other folks to review them before we release them. It might help to promote on other platforms that it'd be great if anyone who speaks those languages could give them a look.

**Comment by raclim** [comment]
I've been thinking about this and feel that since it might take a while to get these translations in and to help with PR organization, it might be better to move the each of these PRs into a [Gist](https://gist.github.com/) (which I believe contributors can still view and add comments/updates to) and link the Gists to this issue. I'll probably start transferring them into Gists tomorrow. @Swarnendu0123 @lindapaiste let me know if you have any other suggestions about this!

**Comment by swrno** [comment]
> I've been thinking about this and feel that since it might take a while to get these translations in and to help with PR organization, it might be better to move the each of these PRs into a [Gist](https://gist.github.com/) (which I believe contributors can still view and add comments/updates to) and link the Gists to this issue. 

Nice idea! In addition to that, whenever any translations will be reviewed by any native speakers, we can merge them up to the main code base. I am just a little worried about, how much the native speakers will be involved in the issue. For that, we can pin the issue, so that we can get maximum reviews.

> I'll probably start transferring them into Gists tomorrow. @Swarnendu0123 @lindapaiste let me know if you have any other suggestions about this!

 If you need any type of help in creating the Gists, feel free to delegate me that part.

**Comment by raclim** [comment]
I created several gists that contain the translations for each language, and updated the body of this issue with their links and instructions on how to provide feedback for them. I didn't add the Dutch one because the translations in that PR did not seem correct. 

Since these have been transferred, I'm going to close the associated PRs. We can consider merging these in again once the languages have been reviewed and vetted.

**Comment by raclim** [comment]
I'm also going to add [this pull request with Azerbaijani Translations](https://github.com/processing/p5.js-web-editor/pull/2915) here as well to the issue body.

**Comment by swrno** [comment]
Can we get this issue pinned, so that any native speaker comes, this issue can quickly attract him/her?

**Comment by Zerobrofan** [comment]
Hey @Swarnendu0123 and @raclim!

I would like to contribute to fix the Arabic translation since it's my first language. Upon a surface inspection, it appears that the translation is a bit messed up. Standard terms (like titles and descriptions) appear to be mostly fine with a few exceptions here and there. Some keywords have been translated literally, such as "regex", which lacks a direct equivalent in Arabic.

Also, I'm new to open-source! I learned about the "Processing Foundation" through GSoC 2024. I'll provide the updated gist here and in the comments of the gist once I'm finished.

**Comment by Zerobrofan** [comment]
Hey @Swarnendu0123 and @raclim!

I would like to contribute to fix the Arabic translation since it's my first language. Upon a surface inspection, it appears that the translation is a bit messed up. Standard terms (like titles and descriptions) appear to be mostly fine with a few exceptions here and there. Some keywords have been translated literally, such as "regex", which lacks a direct equivalent in Arabic.

Also, I'm new to open-source! I learned about the "Processing Foundation" through GSoC 2024. I'll provide the updated gist here and in the comments of the gist once I'm finished.

Here is the updated gist for Arabic: https://gist.github.com/Zerobrofan/6303e873f83cacb5bac628e67e69e99f

I have fixed all translation errors and used synonyms more appropriate for the intended meaning. Most of the issues involved synonyms that didn't quite fit. For example, "Sketch" was translated to represent a literal painting rather than a project you open and code, along with many other elements. I hope this was helpful!

**Comment by swrno** [comment]
> Hey @Swarnendu0123 and @raclim!
> 
> I would like to contribute to fix the Arabic translation since it's my first language. Upon a surface inspection, it appears that the translation is a bit messed up. Standard terms (like titles and descriptions) appear to be mostly fine with a few exceptions here and there. Some keywords have been translated literally, such as "regex", which lacks a direct equivalent in Arabic.
> 
> Also, I'm new to open-source! I learned about the "Processing Foundation" through GSoC 2024. I'll provide the updated gist here and in the comments of the gist once I'm finished.

Appreciate your enthusiasm!!

**Comment by Zerobrofan** [comment]
@Swarnendu0123 
Here is the updated gist for Arabic: https://gist.github.com/Zerobrofan/6303e873f83cacb5bac628e67e69e99f

I have fixed all translation errors and used synonyms more appropriate for the intended meaning. Most of the issues involved synonyms that didn't quite fit. For example, "Sketch" was translated to represent a literal painting rather than a project you open and code, along with many other elements. I hope this was helpful!

Also, I'm not sure what steps to take in order to get accepted for GSoC 2024 by the Processing Foundation, so any advice you have would be greatly appreciated.

**Comment by swrno** [comment]
> @Swarnendu0123 
> Here is the updated gist for Arabic: https://gist.github.com/Zerobrofan/6303e873f83cacb5bac628e67e69e99f
> 
> I have fixed all translation errors and used synonyms more appropriate for the intended meaning. Most of the issues involved synonyms that didn't quite fit. For example, "Sketch" was translated to represent a literal painting rather than a project you open and code, along with many other elements. I hope this was helpful!

Well, as you are a native speaker of Arabic, I feel this is now correct. But the main thing is the Arabic language that is a right aligned language.

Maybe we can add another property on the json by which we can decide, a particular language is aligned towards the left or right. And we can manipulate the
 ```css 
text-align: left/right
```
Also, I have come up with an article, which explains how we can add left-alignment for left aligned language in `i18n`:
https://medium.com/@saif.as/localization-react-i18-next-and-rtl-support-including-material-ui-to-a-react-project-eeab31817467

@raclim @lindapaiste needs your views on it.

**Comment by absmj** [comment]
Hey @Swarnendu0123  and @raclim !

I created [these translations](https://github.com/processing/p5.js-web-editor/pull/2915) about 6 months ago, but haven't received any response or feedback yet. The translations were done line-by-line from Turkish, which is more similar to Azerbaijani. Please note that I'm not confident that anyone has reviewed this translation.
