### ISSUE TITLE
[FEAT]  : No button to return back to Homepage from other routes on Phone.

### ISSUE THREAD

**Issue by vivekbopaliya** [processing/p5.js-web-editor#2784]
### p5.js version

latest

### What is your operating system?

Android

### Web browser and version

Chrome

### Actual Behavior

On Mobile,  When you are on other page such as `_/account_` or _`/Sketches_`, there is no way to navigate back to **Home** page, for instance: On Laptop there is `< Back to Editor` button.

![Screenshot (181)](https://github.com/processing/p5.js-web-editor/assets/122638553/de3b3295-027e-407a-89b3-76ab3e620df3)

### Expected Behavior

By clicking Asterisk Icon we should be navigated to Home Page. 

### Steps to reproduce

From Phone > SignIn/SignUp > My Stuffs or so on

**Comment by raclim** [comment]
Thanks for raising this issue! We actually do have a button to return to the editor on the far-right corner of the navigation menu pictured below. I can see how it could be a little confusing, especially since it's not consistent with the Desktop experience. 

<img width="492" alt="Screenshot 2024-03-28 at 11 35 12 AM" src="https://github.com/processing/p5.js-web-editor/assets/43053081/61dbfb22-c20e-47bf-ba91-e310b6685079">

I do see this as something we'll want to address down the line, but I think at this moment in light of some other issues we want to prioritize fixing bugs and refactoring versus feature requests and enhancements. I'm sorry we weren't able to get this in, but due to those reasons I'm going to close this issue and its associated PRs for now!
