### ISSUE TITLE
Color of checkbox should be of p5 editor's theme but its not

### ISSUE THREAD

**Issue by PiyushThapaa** [processing/p5.js-web-editor#2808]
### What is your operating system?

Windows

### Web browser and version

Chrome

### Actual Behavior

![Screenshot 2023-12-30 183221](https://github.com/processing/p5.js-web-editor/assets/112943430/44b9e8eb-fba0-460f-9456-f66ad9a75b5a)

The color of checkbox should be of p5 editor's theme according to this code but this code is not working and the color of checkbox is default

### Expected Behavior

https://github.com/processing/p5.js-web-editor/assets/112943430/5258643e-5a13-45b7-aacf-cfef8a5cc23e

The expected behaviour should be like this...

### Steps:
1. Go to the p5 web editor website
2. In tool section below the header, there is a checkbox

**Comment by PiyushThapaa** [comment]
@lindapaiste please assign this to me

**Comment by mayanksahu17** [comment]
hey I can fix this issue. Can u assign me ?

**Comment by lindapaiste** [comment]
~~Can you please explain what you are showing in the video that isn't right?  Because it looks correct to me.  I see a pink checkbox next to "Auto-refresh".  Then you change the theme to "dark" mode and it is pink.  Then to "contrast" and it is yellow.  That's all correct.~~

Ohhhh your video is showing the *expected* behavior.  Nevermind!
