### ISSUE TITLE
Console "clear on play"

### ISSUE THREAD

**Issue by joemckay5** [processing/p5.js-web-editor#284]
I think the console should clear on play, or at least have the option to set it this way that's easy to access.

**Comment by catarak** [comment]
Hmmm, this seems like a good idea since it's in line with browser consoles (i.e. you refresh the page and the browser console clears). Is there any reason a user would want the console not to clear?

**Comment by lmccart** [comment]
I think the only question is what happens when you have auto-refresh on? Does it make more sense to clear the console with every change/refresh, or only when you manually click play?

**Comment by catarak** [comment]
hmmmm, I feel like I could be convinced either way. on the one hand, auto-refresh is rebuilding the whole preview iframe again so it would make sense to clear the console. on the other hand, you could think of it more like webpack hot module replacement or live reload, which injects new JS into the browser and doesn't refresh the page, and therefore doesn't clear the console.

**Comment by joemckay5** [comment]
I would argue it should clear on auto-play only when you press play, but that's more hunch than anything.

**Comment by lmccart** [comment]
that feels right to me too

**Comment by catarak** [comment]
sounds good! i will implement the console to clear when a user clicks play (or uses the keyboard shortcut), but not when the sketch is re-run via auto-refresh.

**Comment by shiffman** [comment]
@catarak I think I would like to make the case that auto-refresh does in fact clear the console each time it is re-run.  In class I noticed the following behavior.

1) The same error appearing many times as I type:

<img width="727" alt="screen shot 2017-02-13 at 9 21 07 pm" src="https://cloud.githubusercontent.com/assets/191758/22912267/5ddaac90-f232-11e6-9214-3f413ad941b0.png">

2) Students were also confused b/c once I corrected the error, the error messages did not disappear.

A more logical behavior would be that the error message would keep re-appearing once when the problem is unresolved, but not appear when it is resolved.

Does this make sense?  If it were "live-coding" and not restarting the entire sketch then I would say we shouldn't clear it, but since the entire sketch is restarting any existing errors will re-appear anyway?

**Comment by catarak** [comment]
That makes sense to me. If the error persists when the sketch is refreshed, then the error message will appear again. Maybe this means we need a "Clear on Play" option, like there is in Unity.

**Comment by shiffman** [comment]
Agreed, however I'm wary adding too many preferences. I think I would just have it clear by default and then if scenarios arise where we wouldn't want it to clear, we could add something in as an option?

**Comment by catarak** [comment]
sounds good to me!
