### ISSUE TITLE
Hindi Translation error in mobile nav bar

### ISSUE THREAD

**Issue by punyakrit** [processing/p5.js-web-editor#2856]
### What is your operating system?

None

### Actual Behavior

<img width="920" alt="Screenshot 2024-01-07 at 12 29 27 PM" src="https://github.com/processing/p5.js-web-editor/assets/67222925/e4ad7207-855e-4dc3-addb-19da806a92d9">

Its not be translated to hindi language

### Expected Behavior

<img width="627" alt="Screenshot 2024-01-07 at 12 33 41 PM" src="https://github.com/processing/p5.js-web-editor/assets/67222925/98c40e98-50a1-4309-a8ab-9f76ec668624">
This is how it hsould look like

### Steps to reproduce

Updating code

**Comment by raclim** [comment]
Thanks for raising this issue! We're planning to take down this text since it was meant to be a temporary promotion for the 2023 fundraiser until January 15th. Since I just reverted the fundraiser PR and the next release is going to be on January 16th, we're not going to merge in further changes to the fundraiser modal for now. 

The past few PRs definitely did raise some issues with the 2023 implementation—hopefully many of these can be addressed for 2024!
