### ISSUE TITLE
mWeb: Keyboard Shortcuts Content Overflow in Mobile View

### ISSUE THREAD

**Issue by arpitghura** [processing/p5.js-web-editor#2866]
### p5.js version

1.9.0

### What is your operating system?

Android

### Web browser and version

120.0.6099.199

### Actual Behavior

The content in the keyboard shortcut is going beyond the parent container (Modal). 

![image](https://github.com/processing/p5.js-web-editor/assets/41796013/fd114b23-5056-482a-9d1a-092b7dfdd15a)

### Expected Behavior

The content should wrap inside the parent container (Modal).

### Steps:
1. Open in Mobile View
2. Click on three dot Menu 
3. Click on Keyboard Shortcuts

**Comment by arpitghura** [comment]
I would like to contribute to this. Can you please assign this to me?

**Comment by Ri-Sharma** [comment]
Hey @arpitghura, using `min-inline-size: max-content;` was pretty neat.
But there is an problem with `max-width: #{500 / $base-font-size}rem;` whenever we use a screen size that is wider, there is an abnormal gap between the scroll bar and screen end like following;
![Screenshot 2024-01-20 224022](https://github.com/processing/p5.js-web-editor/assets/80570105/6ffa034a-c57d-4489-bf83-bcddae5b33ec)

So instead of `max-width: #{500 / $base-font-size}rem;`  we can just use `width : 100%` this would prevent the overflow and prevent the scroll bar problem.

**Comment by Ri-Sharma** [comment]
Just added that :)

**Comment by raclim** [comment]
Thanks for raising this issue! I'm going to go with https://github.com/processing/p5.js-web-editor/pull/2932, but I think the resolution for this was definitely found through the solutions of both @arpitghura and @Ri-Sharma!
