### ISSUE TITLE
Using Volta to change the node version 

### ISSUE THREAD

**Issue by rahulrana701** [processing/p5.js-web-editor#2939]
### Increasing Access

Via using this tool that is volta we don't have to update the node version's using nvm we just have to install volta  once and then 
according to the version of node and npm a particular project is using it will adjust accordingly , we don't have to use nvm to update the versions. Using Volta is a better approach

### Feature request details

I have added a volta script in package.json in this way whosoever have volta installed locally they don't have to update their node versions to specific version , they just have to clone the repo and 
<img width="656" alt="Screenshot 2024-01-22 211343" src="https://github.com/processing/p5.js-web-editor/assets/123585591/ab6192b1-707a-476a-a9ca-b4472a66bbf7">
start working on it as volta will take care of the versions of npm and node

**Comment by rahulrana701** [comment]
Hi @lindapaiste I would like to work on this issue so please assign it to me

**Comment by lindapaiste** [comment]
I'm not familiar with Volta at all but this sounds fine to me.  Like there's no major downside to having extra info in the `package.json`.  It's weird that Volta can't just use the `engines` [which is a standard property](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#engines) that we already have set.

You should add a section to the contributor documentation explaining how to use Volta with this project.

**Comment by rahulrana701** [comment]
@lindapaiste done

**Comment by raclim** [comment]
Thanks for suggesting this! After reading about Volta, although it does sound great and might bring some additional benefits, I personally don't feel like there's a strong need to add this yet, especially since it's much newer compared to `nvm`, which has been around for a while. 

I definitely think it would be great to reconsider switching to Volta down the line after it gets some more usage, or seeing what other options also pop up!
