### ISSUE TITLE
UI detail: Notification (toast) bar styling

### ISSUE THREAD

**Issue by machinic** [processing/p5.js-web-editor#294]
Though there's a save example in the last design drop, the design guidelines could use some shoring up with respect to behavior and placement of toasts and other bar notifications — those are forthcoming. 

In the meantime, if we can adjust the styling to better match the guide that would be Awesome. 

Compare current implementation:

![bar-notif-detail](https://cloud.githubusercontent.com/assets/3985997/22649141/b397d2a2-ec47-11e6-8306-614945342e47.png)

Design guide for bar notif: 

<img width="462" alt="bar-notif-design-guide" src="https://cloud.githubusercontent.com/assets/3985997/22649162/c80ec394-ec47-11e6-8879-f1588c72e5df.png">

Background-color is `#4A4A4A`. Close affordance same color as text. Size and positioning of message within should be adjusted as well. Some box shadow applied as well `box-shadow: 0 6px 6px 0 rgba(0,0,0,0.10);`

**Comment by lonesword** [comment]
I'm working on this. Is the design guide hosted somewhere? Can I have a link?

A quick look tells me that the close button has a different colour due to [this](https://github.com/processing/p5.js-web-editor/blob/master/client/styles/abstracts/_variables.scss#L32) style. 

Two ways to fix this:

1. Change icon-color to $white. Affects all icons
2. In [_toast.scss](https://github.com/processing/p5.js-web-editor/blob/f017dd8a765174ab85806a8b62b7e15b2d57d2da/client/styles/components/_toast.scss#L14) do not extend %icon. Instead, specify the styles in the call to themify(). Affects only this icon but undermines the purpose of %icon

I'm not familiar with themify, so I'm not sure if there's a way to extend %icon and overwrite just the 'color' property.

**Comment by lmccart** [comment]
@lonesword the full set of designs are here: http://p5js.org/p5-web-editor-design.zip
