### ISSUE TITLE
Making 'Sublime Text shortcuts.' hyperlink easily distinguishable with rest of the text.

### ISSUE THREAD

**Issue by Ri-Sharma** [processing/p5.js-web-editor#2940]
### Increasing Access

This would allow the user to easily identify that 'Sublime Text shortcuts' is an hyperlink.

### Feature enhancement details

Before :- 
![image](https://github.com/processing/p5.js-web-editor/assets/80570105/ee23d341-eb00-4b95-891d-975202bc73b8)

After :- 
![image](https://github.com/processing/p5.js-web-editor/assets/80570105/3e5bc4ee-4bf4-400f-8136-59b423432415)

**Comment by lindapaiste** [comment]
Issues like this keep coming up in various places and I think that we probably want to change the default style for all links, not just this one link.  @raclim should we use the primary accent color (pink) for all links?

**Comment by raclim** [comment]
@lindapaiste Hmm, I think the primary accent color might not work because it doesn't pass the color contrast criteria for accessibility. 
<br>
<img width="250" alt="Screenshot 2024-01-25 at 3 42 00 PM" src="https://github.com/processing/p5.js-web-editor/assets/43053081/1fa82e41-2b11-4a01-ac77-2737e7c91d44">



I think we actually have a lot of elements within the site that definitely don't pass this 😅 particularly, the dark grey text on light grey backgrounds. I've been wondering in terms of appearance, if it might be better to reach out to a designer who can give a clear direction on how all these elements should look that also aligns with these standards?

**Comment by Noorain464** [comment]
I am new to open source and I would like to work on it
