### ISSUE TITLE
"Create Collection" button & text area overflowing outside the dialog box.

### ISSUE THREAD

**Issue by Ri-Sharma** [processing/p5.js-web-editor#2973]
# Issue#1

### Actual Behavior

The 'Create collection' button & the textarea is overflowing outside the dialog box when resizing the textarea.

https://github.com/processing/p5.js-web-editor/assets/80570105/d72a4cec-2f89-49ad-b020-460127fb889c

### Expected Behavior

The `max-height` property is causing this issue.
Also we should remove the resize from this text area, because resizing the textarea after modification in the `max-height` will cause it to go out of the screen.

# Issue#2
The `min-width` in the Collection Create modal's input area is causing horizontal scrolling for mobile screen with smaller width. It requires adjustment to prevent this issue and improve user experience.

https://github.com/processing/p5.js-web-editor/assets/80570105/6c0f056e-5bf5-4b34-86bf-939c70ba42dd

**Comment by vaishnavi192** [comment]
Hey @Ri-Sharma I would like to work on it plz assign me this issue

**Comment by Ri-Sharma** [comment]
> Hey @Ri-Sharma I would like to work on it plz assign me this issue

Hey @vaishnavi192, I appreciate your interest but I am already working on this issue.

**Comment by lindapaiste** [comment]
> Also we should remove the resize from this text area, because resizing the textarea after modification in the `max-height` will cause it to go out of the screen.

So weird.  I had to sanity-check myself and look at MDN because I forgot that textarea is automatically resizable https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea#controlling_whether_a_textarea_is_resizable

It would be possible to make the body of the modal scrollable, but I'm thinking that's probably that's a worse user experience than having a fixed (or maximum) height on the `textarea` and having a scrollbar just on that `textarea`.
