### ISSUE TITLE
Screen going blank with 'Alder veil

### ISSUE THREAD

**Issue by performant23** [processing/p5.js-web-editor#3002]
### What is your operating system?

Windows

### Web browser and version

121.0.6167.140 (Official Build) (64-bit) (cohort: Stable) 

### Actual Behavior

Not sure if this is addressed in an issue before but when reducing the screen width below about 770px, the screen of the web editor goes completely blank with the page heading 'Alder veil' and the rest of UI disappears.

### Expected Behavior

Ideal behavior would be that the interaction still remains possible for screens below 770px.

### Steps to reproduce

Going to web editor and reducing the screen size via inspection or simply resizing the window would highlight the issue. The navbar, console, input section, etc. all disappears on doing this and we get a blank page where going from code to preview only happens through pressing the stop/resume button which sort of toggles the two views. Not sure if this behavior is expected or if this is a bug and ideally both code injection and preview should be visible for smaller screens. The first image shows the page after being resized to <=770px and the other one shows the image for >770px

![Screenshot 2024-02-07 234230](https://github.com/processing/p5.js-web-editor/assets/138517416/a956334b-7789-4b6c-b961-777b539eeb73)

![Screenshot 2024-02-07 234210](https://github.com/processing/p5.js-web-editor/assets/138517416/99d9b8d7-668d-401b-b46f-a77a1c166cf7)

**Comment by PATHAKAAKASH19** [comment]
@performant23 i would like to work on this bug....

**Comment by performant23** [comment]
Hey, @PATHAKAAKASH19, I think you'll need to take this up with the maintainers of the repository.

**Comment by PATHAKAAKASH19** [comment]
thanks @performant23 i keep this in mind....

**Comment by lindapaiste** [comment]
> The navbar, console, input section, etc. all disappears on doing this and we get a blank page where going from code to preview only happens through pressing the stop/resume button which sort of toggles the two views. Not sure if this behavior is expected or if this is a bug and ideally both code injection and preview should be visible for smaller screens.

This is the expected behavior.  It is not possible to show both the code editor and the sketch preview on small screens so we switch between them.

There is only one thing here that I would consider a "Bug" which is that the sketch stops playing when switching between the mobile and desktop layouts.  The editor *thinks* it's playing the sketch which is why you see the preview rather than the code.  See #2642 

We could potentially make other improvements.  Like "Alder veil" is the name of your sketch but you're not the first person to be confused by that.  See #2790
