### ISSUE TITLE
Control+Enter to run the code works only after pressing it twice

### ISSUE THREAD

**Issue by willy-vvu** [processing/p5.js-web-editor#301]
I was playing with the Web Editor today when I tried to run my code with Control+Enter. Unfortunately, after pressing Control+Enter, it seemed to refresh the sketch that was already there, without any new changes. Pressing Control+Enter again seems to correctly update the sketch. This is strange given that the "Play" button works correctly - one press updates the code.

Take note: Control+Enter is an existing CodeMirror command bound to "Create new empty line on the line below the cursor." When hitting Control+Enter, in addition to running the code, it adds a new line in the editor, which can be annoying. This might be related?

**Comment by catarak** [comment]
This may be on Windows only. I have a Mac and for me it refreshes when I hit Command + Enter once. It is annoying that it will insert a new line, and this is because I've added Sublime Text shortcuts to CodeMirror. You can get around this by clicking outside of the text area. Command/Control + Enter is a common accessibility shortcut for running something, which is why we decided to use that. If this is too annoying we can discuss solutions.

**Comment by epiqueras** [comment]
We could overwrite the keymap to not do anything:

    editor.setOption("extraKeys", {
      'Cmd+Enter': () => null;
    });

**Comment by catarak** [comment]
@epiqueras i think that is a good idea, as I'd imagine more often users would want to use the 'run' keyboard shortcut rather than the sublime text shortcut.
