### ISSUE TITLE
loadImage results in "failed to fetch" with most images.

### ISSUE THREAD

**Issue by StevesMakerspace** [processing/p5.js-web-editor#3132]
loadImage in preload results in "failed to fetch" with most images.  This appears to be a web editor issue, as loadImage works fine with p5 locally installed.

**Comment by raclim** [comment]
Thank you for raising this issue @StevesMakerspace! This issue is probably tied to earlier issues raised about `loadImage()` (i.e https://github.com/processing/p5.js-web-editor/issues/3069). I'm sorry that there's been a delay in addressing this—we'll post more progress updates to the linked issue soon! 

I'll close this one for now to help keep issues consolidated, but please feel free to raise any other concerns that you have or chime in on the linked issue!
