### ISSUE TITLE
We are able to upload duplicate `file`

### ISSUE THREAD

**Issue by PiyushChandra17** [processing/p5.js-web-editor#3143]
### What is your operating system?

None

### Actual Behavior

We are able to upload duplicate `file`
<img width="152" alt="Screenshot 2024-06-03 at 2 01 47 PM" src="https://github.com/processing/p5.js-web-editor/assets/47579287/59d7b473-6c0a-41fa-b342-c3879629074e">

### Expected Behavior

We shouldn't be able to upload duplicate `files`, as it should throw an error stating `File already exists`

### Steps:
1. Open the editor web app
2. Click on "+"
3. Click on upload file
4. Choose a file which is already uploaded
5. Notice the file gets uploaded in the format {somexyzfile} - {1,2,3}.jpg

**Comment by rohanjadhav05** [comment]
Hello @raclim is this a valid issue? 
if it is how can we check the duplicate files -  based on filename ?
can you please share you thoughts on this one ?

**Comment by raclim** [comment]
Thanks for raising this! I think we might want to keep this functionality as is, since I could see folks wanting to have multiple versions of the same file for creative reasons, and have personally found myself wanting to have multiple versions of an image for a project! 

I'm going to close this for now, but am down to reopen this if more folks request for this in the future!

**Comment by PiyushChandra17** [comment]
> Thanks for raising this! I think we might want to keep this functionality as is, since I could see folks wanting to have multiple versions of the same file for creative reasons, and have personally found myself wanting to have multiple versions of an image for a project!
> 
> I'm going to close this for now, but am down to reopen this if more folks request for this in the future!

@raclim Sure! 👍
