### ISSUE TITLE
The Error message is not being Translated to selected Language

### ISSUE THREAD

**Issue by Ganeshvarikuppala** [processing/p5.js-web-editor#3229]
### What is your operating system?

None

### Actual Behavior

It is not getting translated 
![Pj5](https://github.com/user-attachments/assets/965c3af0-4930-4955-8fee-f4b4d904ec1e)

### Expected Behavior

It should be translated 

### Steps:
1. Go to Sign Up page
2.Select language 
3.Enter the  invalid inputs 
4.You will get a error message displayed.
5.Now select another language.
6.Everything will be translated except Error message

**Comment by Serena20003** [comment]
Hi, I think the issue here is that because the error message gets re-populated only after the user has "touched" the input field, which means that they need to enter the text field, then leave the text field for the error message to re-populate. 
This can be seen in line 79 of client/modules/User/components/SignupForm.js: ` {field.meta.touched && field.meta.error && (`
Perhaps one way to work around it is to change `field.meta.touched` to something else that doesn't require the user to enter and leave the textfield again after changing the language (perhaps `field.meta.invalid`?).
The number of translations on translations/locales/hi/translations.json match the number on translations/locales/hi/translations.json for `ReduxFormUtils`, which I believe is controlling the translations for error messages for the signup form fields.
I did notice one missing translation for "This username is already taken." though.
![Screenshot 2024-09-08 at 2 25 46 PM](https://github.com/user-attachments/assets/43f811e7-9899-4e44-b0a1-6f2a00c654a0)

**Comment by AbhigyanSrivastav** [comment]
Hey can i work on this issue?

**Comment by Sankalpcreat** [comment]
is it still open
