### ISSUE TITLE
Adding dark mode feature

### ISSUE THREAD

**Issue by urgetolearn** [processing/p5.js-web-editor#3247]
### Increasing Access

It will enhance the beauty of the website and will attract users.

### Feature request details

Adding an icon, by clicking that icon, it must turn the website into dark mode by changing the details into relevant and readable color.

**Comment by raclim** [comment]
Thank you for raising this! We do currently have a dark mode within "Settings", which can be found by clicking on the Gear icon on the right side of the editor. Since this feature already exists, I'm going to close this for now. Thanks again and please feel free to raise any other issues or ideas that come up!
