### ISSUE TITLE
feat: adding a feedback section 

### ISSUE THREAD

**Issue by solanki505** [processing/p5.js-web-editor#3248]
### Increasing Access

This will help us to know the users opinion regarding this site and the ways to improve

### Feature request details

this feedback icon will be added in the nav bar, when clicked it will open a modal feedback form.

**Comment by hamzamehmood67** [comment]
I am interested and would like to work on the feature!
Please assign me!

**Comment by Tanuj1718** [comment]
@catarak can you please assign it to me? Would like to contribute in this.

**Comment by raclim** [comment]
Thank you so much for raising this! 

We do currently have a URL to give feedback on the editor within the About page, labeled as "Report a Bug". I do feel like it could probably be more noticeable though! We do have a design underway for the About page that might help mitigate this issue. Since it's currently in progress, I'm going to close this issue for now as I feel like it will be resolved with this redesign update. Thanks again and please feel free to raise any other issues or ideas that come up!
