### ISSUE TITLE
translate doesn't work in function setup()

### ISSUE THREAD

**Issue by Kimberly1774** [processing/p5.js-web-editor#340]
translate changes the coordinate system only if used in function draw()

**Comment by catarak** [comment]
Thanks for reporting this issue! This is actually an issue in [p5.js](https://github.com/processing/p5.js) rather than the web editor, so I would create an issue there. I took a look at the [documentation](https://github.com/processing/p5.js)--and it seems like this may be the expected behavior, as translate gets reset in the `draw()` loop. On the issue you create in the p5.js repository, it would be helpful if you included your code as well.
