### ISSUE TITLE
add file / upload box feedback is confusing

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js-web-editor#350]
When I drag/drop a file onto the upload box, it wasn't clear to me at first that the file had actually successfully loaded. I'm not sure with the new design, if this will change completely. But in case it hasn't been addressed already, I think some kind of feedback that the file successfully completed would be useful. This is the current view on upload complete.

![screen shot 2017-05-08 at 12 05 54 pm](https://cloud.githubusercontent.com/assets/191056/25878827/907fcd2c-34e2-11e7-8732-b2eafa08fa1d.png)

**Comment by machinic** [comment]
The new design proposes three status messages for this process: Uploading (so the user is aware that their drop was successful and the upload is in process), and Success-Completed (so the user has confidence the operation was completed), three is Failure so that the user knows when the operation was not successful. The text for these messages is more robust than what's written above but that's the general outline.

**Comment by lmccart** [comment]
@machinic ah great, that sounds perfect, sorry I missed that in the wireframes.
