### ISSUE TITLE
Click to save sketches to github account

### ISSUE THREAD

**Issue by blue522** [processing/p5.js-web-editor#380]
Low priority request: the ability to backup sketches to my github account.

**Comment by catarak** [comment]
I think integrating with a Github gist/the Github API is actually not super difficult!

**Comment by ankur54** [comment]
Hi. I would like to work on this project. I am thinking of adding a "save to GitHub" option and on clicking it, the code with first be stored in a local file, and from there we can redirect to create a new gist using "POST /gists" router. Please correct me if my way is not an efficient one, as I am new to open source community.

**Comment by catarak** [comment]
since github oauth is already integrated into the application, i think it would make sense to leverage this along with the github api.

**Comment by catarak** [comment]
@ankur54

**Comment by ankur54** [comment]
Just to be on the same page, according to you, GitHub OAuth is already integrated into the simulation area, Is that what you are saying? Please correct me if I am wrong.

**Comment by catarak** [comment]
i'm not sure what you mean by simulation area (i'm assuming you mean the sketch preview?), however, it is possible to log into the web editor using Github, so I think that could be leveraged to make integrating with the GIthub API easier.

**Comment by ankur54** [comment]
Yes, sketch preview is what I meant. Sorry for that. So is the code for logging in with GitHub already present in the code section?

**Comment by catarak** [comment]
no worries! it sounds to me like you're confusing the code for a sketch and the code for the editor itself, which are separate.

**Comment by ankur54** [comment]
Sorry once again. I mean code for the editor. Github API is integrated into it, right?

**Comment by catarak** [comment]
the Github API is not currently integrated. though [passport](http://www.passportjs.org/), users are able to log into the editor with github. i am suggesting that maybe this could be leveraged to help with the integration with the github api so that users could upload their code there.

**Comment by ankur54** [comment]
Oh ok, I see. So my guess is, we would use passport.js and use the github details of the user, as they log in with github account, and use it instead to save the sketch.

**Comment by ankur54** [comment]
@catarak am I getting it wrong?

**Comment by catarak** [comment]
i don't know! i haven't researched it and i'm only trying to add information to help this issue ✨

**Comment by ankur54** [comment]
Can I look into this issue too? I mean if no one is working on it that is...

**Comment by catarak** [comment]
@ankur54 go ahead!

**Comment by GaurangTandon** [comment]
@ankur54 if you're not working on this issue, may I take it up?

**Comment by ankur54** [comment]
I am sorry for the delay. I was busy with college works for the last few days.
@GaurangTandon Do you have an idea of how to implement it? Maybe we can do it together. Can you brief me with your idea?

**Comment by GaurangTandon** [comment]
@ankur54 Here's my brief: 

@catarak regarding: "i am suggesting that maybe this could be leveraged to help with the integration with the github api so that users could upload their code there." Sorry, I do not think that is possible. Even when we are implementing user profile login, we are doing it with a `user:email` scope (`passport.js` line 69) - which is the right way to implement user login.

However, to be able to publish gists on behalf of the user, we need the `gist` OAuth scope as mentioned on the [docs](https://developer.github.com/v3/gists). 

Thus, I plan to do the following:

1. use passport.js to implement the necessary [OAuth](http://www.passportjs.org/docs/oauth/). Thus, even if user is signed in through github, no useful benefit as they'll have to authorize p5.js with write access to their gists.
2. use the newly received scope to be able to publish gists via the [create-gist](https://developer.github.com/v3/gists/#create-a-gist) method.

Thoughts?

I would also like to point out that having write access to a user's gists is a very responsible permission, which we should be cautious with storing it.

**Comment by ankur54** [comment]
@GaurangTandon you may take the issue.

**Comment by GaurangTandon** [comment]
@ankur54 Cool, @ankur54. However, before that I'd like to ask @catarak for green signal or any improvement suggestions to start working on this feature the way I described in my comment above :)

**Comment by catarak** [comment]
@GaurangTandon i'd check out the github import/export flow on glitch.com for reference.

**Comment by catarak** [comment]
going to merge this issue into #753 since they are the same 😄
