### ISSUE TITLE
Update Sidebar styling

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#389]
The new design is a significant change from the previous version:
<img width="512" alt="screen shot 2017-07-11 at 1 30 47 pm" src="https://user-images.githubusercontent.com/6063380/28081575-bb912ab0-663d-11e7-8cbd-fc411f7074ac.png">
<img width="511" alt="screen shot 2017-07-11 at 1 31 01 pm" src="https://user-images.githubusercontent.com/6063380/28081578-bca5b88a-663d-11e7-80f5-910e1ede943f.png">
<img width="513" alt="screen shot 2017-07-11 at 1 34 18 pm" src="https://user-images.githubusercontent.com/6063380/28081580-bdbe5fc4-663d-11e7-9ba1-5679eaaa0f09.png">
<img width="514" alt="screen shot 2017-07-11 at 1 34 26 pm" src="https://user-images.githubusercontent.com/6063380/28081581-bee11d42-663d-11e7-8676-a65d6ab0675b.png">

More details on [Zeplin](https://zpl.io/Z2cihf1).

**Comment by himanshuc3** [comment]
Working on this. Could take some time as my exams are coming through...

**Comment by catarak** [comment]
all good! this is a pretty in-depth task, maybe it would be good to split it up into smaller ones?

**Comment by himanshuc3** [comment]
- I've made a PR for this. It's a subset of changes and as said by you, I will split and do it in small commits to manage better rather than lost. 

- Also, I would want the icons of files and folders to be placed as right now they are not large enough to be increased in size. I could place icons from [flaticon](http://www.flaticon.com) if you want otherwise.

**Comment by himanshuc3** [comment]
definitely!

**Comment by catarak** [comment]
emailed it to you 🎉
