### ISSUE TITLE
Update Account Settings View

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#392]
<img width="515" alt="screen shot 2017-07-11 at 2 08 26 pm" src="https://user-images.githubusercontent.com/6063380/28083149-72527052-6642-11e7-9acf-1b7125d13e7c.png">

View more on [Zeplin](https://zpl.io/Z2cihf1).

**Comment by himanshuc3** [comment]
Is there any route currently that leads to My Account settings?

**Comment by catarak** [comment]
yes, `/<username>/settings`.

**Comment by himanshuc3** [comment]
do you mean revamping `/:username/account`. 
There is no current path `/:username/settings` defined.

**Comment by catarak** [comment]
oops, yes!

**Comment by LakshSingla** [comment]
Since this has been dead for a long time, may I take up this issue?

Just to be clear, the objective is to redesign the following view (the input text fields have black background due to OS specific settings)...
![Screenshot from 2019-03-27 00-49-01](https://user-images.githubusercontent.com/30999375/55027003-3506d700-502a-11e9-98ed-80cb3f592e07.png)

**Comment by catarak** [comment]
@LakshSingla please do!
