### ISSUE TITLE
DOM links in to iframe

### ISSUE THREAD

**Issue by nucliweb** [processing/p5.js-web-editor#396]
I have seen a bug in to *Hello P5 : song* example.

When I click in to link `Click to play notes or play song automatically.` reload the editor in to `iframe` tag.

![inception](https://user-images.githubusercontent.com/1307927/28312712-65780050-6bb4-11e7-8981-62cfb8ed315b.gif)

If you change `createA("#","play song automatically.")` for `createA("javascript:void();","play song automatically.")` in to example would work.

But I think it would be a better solution if it is fixed in the editor.

**Comment by zrispo** [comment]
Hmm, I'm thinking it might be nicer to just have a checkbox instead of a link because of weird iframe business like this

@catarak , would it be a good idea to change the example to what I have here?:

![screen shot 2017-07-18 at 8 52 35 am](https://user-images.githubusercontent.com/4970417/28317872-a836cf48-6b96-11e7-8f20-682fc92428f8.png)

**Comment by catarak** [comment]
This is a known issue (#145). The examples are automatically pulled in from the p5.js website so I'm not sure it makes sense to change the example. Rather, I think it would make more sense to either (1) serve the preview iframe from a separate subdomain to handle this, (2) inject code into the iframe to handle this, or (3) in the HTML generation step, handle DOM links in a special way.

**Comment by catarak** [comment]
I've been looking into this, and one way to handle this is to prevent the default behavior for all `<a>` and `<form>` tags. Which prevents the web editor from loading in the iframe, but also causes any links or forms not to actually work. But this also fixes this example...

Being able to handle multi-page sketches and form submission feels like an advanced feature to me. In order to get it to work, we'd have to move the preview generation to server-side, which radically changes everything. 

ALL OF THIS BEING SAID and after thinking this through I think the best thing to do is to change the `<a>` tag in the example to a `<button>`, which is the correct tag to use anyway given HTML5 standards. And possibly prevent `<a>` and `<form>` tags from working so that the editor doesn't load within the iframe.
