### ISSUE TITLE
Adjust CodeMirror styling to match new design

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#413]
Only a couple minor changes. See more on the [Zeplin project](https://zpl.io/a3qJ7Q2).

**Comment by joemckay5** [comment]
I'd be interested in looking at the design. Is it posted somewhere public, or can I get an invite?

**Comment by catarak** [comment]
I can invite you to the project. Maybe I should export all of the screens as PDFs so they are publicly accessible.

**Comment by machinic** [comment]
@catarak I think there's a way we can do this that will make the designs publicly available and not a static snapshot in time but a view into any ongoing work. I'll verify and if it's the case, get it set up and reply here tomorrow.

**Comment by machinic** [comment]
This Zeplin "scene" link exposes some outdated styles and older screens. I will archive the older stuff (it's currently managed by tags inside of Zeplin) so that the public scene link reflects the current state of the design more clearly.  

The easiest way to parse it right now is knowing that the design screens starting with an `L` are the ones to pay mind to. 

https://scene.zeplin.io/project/55f746c54a02e1e50e0632c3

**Comment by himanshuc3** [comment]
I would also like to the designs. Is that possible?

**Comment by himanshuc3** [comment]
Congrats. Designs look fresh lit.

**Comment by catarak** [comment]
This was fixed when I did an accessibility overhaul ~1 yr ago.
