### ISSUE TITLE
uploading a JS or txt file in Safari fails

### ISSUE THREAD

**Issue by lee2sman** [processing/p5.js-web-editor#476]
#### Nature of issue?

- [X] Found a bug

#### Details about the bug: 

- Web browser and version: Safari 10.1.2 and also tried 11.0.1
- Operating System: OS X
- Steps to reproduce this:

Hello, uploading images works but uploading a text file or a javascript file fails. Tested on multiple computers and browsers. Chrome works fine on the same computers.

**Comment by catarak** [comment]
thanks for reporting this! my hunch is that this has to do with how Safari is determining the MIME type. this is maybe related to #152. perhaps the uploader should just look at the file extension since apparently MIME types are not consistent?

**Comment by lee2sman** [comment]
Oh yes, looks like same or similar issue. I am able to upload in a brand new sketch but not one I've been working on for a while. 
Tried on multiple computers. I tried with .txt, .js and without an extension.

**Comment by simonlimon** [comment]
Could this also be related to #450?

**Comment by catarak** [comment]
@simonlimon yeah! i think it's basically the same issue, that the uploader configuration needs to be changed 😸

**Comment by simonlimon** [comment]
Okey! I'll take a look at it

**Comment by simonlimon** [comment]
@catarak I've been trying to work on this but I've had some trouble setting up an aws s3 bucket for development. I followed the instructions in your gist; however, when I create a bucket in an eu region it gives me the following error when uploading files:

```
The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.
```

And when I create one on us-east-1, it logs `Server responded with 0 code.` Have you encountered this before? Maybe instead of me setting up the bucket from scratch do you think it would be possible to get access to the one you are using for development?

**Comment by simonlimon** [comment]
After doing some research it seems like the most straightforward and reliable way to solve this is by performing a serverside check for the file types instead of doing it in the client. [This issue](https://github.com/enyo/dropzone/issues/1476#issuecomment-344705803) is very similar and points to that solution. 

If we do this we can eliminate all the MIME type inconsistencies across browsers and systems. We can easily configure our S3 buckets to only accept certain file types by modifying the bucket policy, and we can update this in the gist you provide for bucket creation.

**Comment by catarak** [comment]
i would like to make calls to the server as little as possible to keep the load down (because we're trying to keep hosting costs as low as possible). therefore, i think it makes sense not to look at the MIME type at all, but just look at the file extensions and assume that most files have the proper file extensions (which is 99% of cases will be true), and then maybe blacklist a few MIME types.
