### ISSUE TITLE
undo bug when switching files

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-web-editor#49]
Haven't pinpointed if this occurs in multiple scenarios but to reproduce:
1. Make a new sketch.
2. Open `style.css`.
3. Delete contents.
4. Open `sketch.js`
5. Open `style.css`
6. Undo.

![undo_bug](https://cloud.githubusercontent.com/assets/191758/17610869/5ff255c8-6010-11e6-83ab-328a253f1b16.gif)

Will investigate more.

**Comment by DexterShepherd** [comment]
Looks like steps 2 and 3 are not needed to reproduce this error. Changing files and undoing replaces the content of the previous file with that of the new file.

**Comment by catarak** [comment]
The reason this is happening is because of how I'm using CodeMirror to switch between files--I'm simply changing the `content` of the CodeMirror editor. CodeMirror keeps track of all changes to its `content`--and has its own undo/redo buffer based on those changes. To solve this, I think we'll  either have to have a different CodeMirror context for every file, or somehow store the undo/redo buffer for each file.

**Comment by catarak** [comment]
I think I figured out how to solve this! Apparently CodeMirror can have multiple documents/buffers, as I discovered from [this example](https://codemirror.net/demo/buffers.html).
