### ISSUE TITLE
Blank Content-Type set for uploaded assets in S3

### ISSUE THREAD

**Issue by francisli** [processing/p5.js-web-editor#496]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

Firefox 57.0.1/macOS 10.13.1
- open the editor, sign in to an account
- open the sidebar for a sketch, open the new file modal
- drag-and-drop a file (i.e. a .jpg image) and let it finish uploading
- in the AWS S3 console, or by using a ```curl -I``` on the asset url, observe that the Content-Type is blank
- if you have the network inspector open while uploading, you'll see that the Content-Type field in the POST to S3 is blank

**Comment by dhruvdutt** [comment]
@francisli I can look into it. What should be the correct Content-Type?

**Comment by catarak** [comment]
it should depend on the type of asset, right? like if it's an image, vs a video, vs a .js file.

**Comment by dhruvdutt** [comment]
@catarak @francisli Thanks for the guidance.

I went through package-lock (equivalent of shrinkwrap in npm5 and above). There are some dependencies using `mime-types` but it gets installed inside their dependency's nested node_modules folder and not in the project's node_modules for us to use. We'll have to explicitly install `mime-type`.

Also, can you also please update the debug setups in original issue post? We don't have any new file modal now. I'm confused about how or where is the option to upload assets/images. :thinking:

**Comment by catarak** [comment]
to upload files, you have to 1. open the sidebar (there's a > icon to the left by the file title), then click the 'v' by 'project-folder', then click 'add file', and you can upload a file in the dropzone area.

**Comment by dhruvdutt** [comment]
I get these errors when I try to upload something. I think it's because I'm missing AWS credentials. @catarak If you want to share your credentials, then send them at [dhruvdutt.jadhav@gmail.com
](url)

![screenshot_20180227_020117](https://user-images.githubusercontent.com/5961873/36693696-20ca14a8-1b62-11e8-81c5-ecc5ad157873.png)

**Comment by catarak** [comment]
you can make your own S3 bucket! the steps to set it up are in the README 😄

**Comment by stalgiag** [comment]
Hi wanted to repost a note from #1196 and say that the editor should not be updated to use [version 0.10.2](https://github.com/processing/p5.js/releases/tag/0.10.2) until this has been resolved.

@dhruvdutt are you still working on this? I can give it a try otherwise. I think that this deserves relatively high priority.

**Comment by dhruvdutt** [comment]
@stalgiag I'm not working on this. You can go ahead and pick this up.

**Comment by stalgiag** [comment]
Great thanks @dhruvdutt !

Anybody have any thoughts on where I might look first? Navigating the project for the first time. As of now my best guess is to add headers to `axios.post(...)` in this line in [uploader.js](https://github.com/processing/p5.js-web-editor/blob/master/client/modules/IDE/actions/uploader.js#L49). It seems like this will only work with files added with dropzone, but I don't think that image assets will be added to the project local storage any other way so perhaps this is acceptable?
