### ISSUE TITLE
p5 console limit

### ISSUE THREAD

**Issue by jps723** [processing/p5.js-web-editor#516]
#### Nature of issue?

- [x] Found a bug

#### Details about the bug: 

The console limits how much data can be output but does not throw an error/warning or indicate that anything has been omitted.  This caused me to believe that there was an issue in my code.

- Web browser and version: Version 63.0.3239.132 (Official Build) (64-bit)
- Operating System: Mac OSX Sierra (10.12.6)
- Steps to reproduce this:

In the below example, the output to the p5 console begins with i at 33 (instead of 0).  Opening the chrome console via inspector shows the entire output to the console.  I would expect there to be a message indicating that the p5 console is limiting results, or it should be expanded to have no limit.  

http://alpha.editor.p5js.org/jps723/sketches/HJYpA9QIG

**Comment by catarak** [comment]
there's another open ticket about console errors being omitted (#468) but this ticket could be on to something, maybe it has to do with the code that's limiting the rate of the console errors! it should be delivering the console messages in batch but perhaps it is not working as expected 😄

**Comment by himanshuc3** [comment]
![screen shot 2018-02-20 at 10 28 34 am](https://user-images.githubusercontent.com/19166045/36408043-d72c2d10-1628-11e8-853c-3efa9bcfa288.png)
Console in Firefox shows a JSHINT warning, the expected console message and Cycle object value error message.
Does this error has something to do with **createVector**. If it does, is this an issue for p5.js library instead of editor.

**Comment by shinytang6** [comment]
l'm on it:)

**Comment by catarak** [comment]
yes. otherwise, if a user is logging something every frame, the whole editor slows down and crashes.
