### ISSUE TITLE
Add Login with Google

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#553]
#### Nature of issue?

- [X] Existing feature enhancement

#### Feature enhancement details:

I got feedback from teacher that students forget their passwords a lot (and don't use password managers!). Would definitely be helpful to add this. There's an existing PR for this #224 but i don't know if it works or is outdated/stale.

**Comment by himanshuc3** [comment]
Got this error:
```
client/modules/IDE/components/PreviewFrame.jsx
7:25  error  Missing file extension for "loop-protect"  import/extensions
```
@catarak Do you know why this is happening? I didn't even touch PreviewFrame.jsx file.

**Comment by catarak** [comment]
there's something up with how the `loop-protect` library is included in `package.json` that it gets deleted. if you copy the url that's in the `package.json` and run `npm install <url>` it will install it again.

**Comment by migom6** [comment]
Can I work on this issue?

**Comment by catarak** [comment]
go for it! there's some unfinished, open PR's that might be helpful: #224 & #572

**Comment by migom6** [comment]
Thanks, I am working on this. I just dropped by for GSOC but is it late? I found this cool and pretty much similar to my taste! 😃

**Comment by catarak** [comment]
Definitely not too late for GSoC! The applications are due March 27th.

**Comment by himanshuc3** [comment]
@migom6 you can go for it. You could pretty much refer all of my code for this issue. I was getting a weird error and scrapped whole internet but couldn't find a fix. Maybe you could find an alternative fix.
@catarak Due to some personal reasons I decided to go with Revamping the hello.p5js.org idea. Could I also apply for an idea in p5 web editor. 
Also if you could afford 2 minutes of your time on my proposal and provide your valuable suggestions, it would be very helpful!
https://docs.google.com/document/d/1mzi56tfn_zZWvmtNSo2Ntfwres73H2TMqXVEnGjk8E4/edit?usp=drivesdk

**Comment by migom6** [comment]
Thank you so much! @catarak @himanshuc3 
I'll gladly ask questions if I run into some issues 😄

**Comment by catarak** [comment]
@himanshuc3 you can submit multiple applications (up to 3), so go for it!

**Comment by migom6** [comment]
@catarak what was wrong with #224  ? Why wasn't it merged?

**Comment by catarak** [comment]
I just let the PR get really stale and didn't get a chance to test it. It's probably work trying to update it to HEAD, testing it, and fixing any issues.

**Comment by migom6** [comment]
@catarak 
I sent a pr #608, regarding this. Review at your leisure.
Thank you 😄
