### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by pjohnston89** [processing/p5.js-web-editor#617]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

- Web browser and version: Google Chrome Version 65.0.3325.181 (Official Build) (64-bit)
- Operating System: Windows 10 -- version 10.0.16299

#### New feature details:
Add ability to run multiple tabs, so that you can move functional code or blocks of code into a new tab and clear the clutter in the main tab

**Comment by shiffman** [comment]
Hi @pjohnston89, thanks for the suggestion! Right now if you open the "file menu" in the editor you can add new files like `particle.js` or `extrastuff.js`, but this requires also adding references to these files in `index.html`. This is just like "tabs" in Processing, but rather than a tabs interface, there's the left file navigation.

There is the question as to when it's appropriate for the editor to make changes to `index.html` behind the scenes. Should it when the user makes a new `js` file? This relates to #4. 

![screen shot 2018-04-08 at 3 45 21 pm](https://user-images.githubusercontent.com/191758/38471885-73139c0e-3b45-11e8-8fb9-146d40b7162b.png)

![screen shot 2018-04-08 at 3 57 15 pm](https://user-images.githubusercontent.com/191758/38471891-907673ac-3b45-11e8-8c55-f0e2f95462f2.png)

![screen shot 2018-04-08 at 3 57 05 pm](https://user-images.githubusercontent.com/191758/38471893-946856d8-3b45-11e8-8db2-09653bcb2594.png)

**Comment by pjohnston89** [comment]
Wow I feel like a fool! Thanks for the response Dan! I did not even see the arrow to the left of sketch.js to open up the left file navigation on the left side! **Perhaps you should have it open by default and the user has to close it** OR **make that arrow more visible to users**. I too am using the dark theme as in your screen shots. The arrows need to have **more contrast**, especially the arrows next to the line of code to collapse/expand code -- **it's very hard to see**! Also, I couldn't figure out where to press the ADD FILE button (I didn't look at the 2nd screen shot at first) and I thought the down arrow next to "project folder" would collapse the left file navigation. That arrow's purpose in not very clear (though now I know).

**Comment by himanshuc3** [comment]
Also @shiffman I wanted to suggest if the designers could maybe polish the night/dark theme a bit more. It looks a little on the dull grey side.

**Comment by catarak** [comment]
in the newer design the UI to open the sidebar is a little more clear—see #389

**Comment by shiffman** [comment]
Love the new design so much! @pjohnston89 I think we can close this and revisit later after the new design is implemented? Let me know if you agree. Thanks again!

**Comment by kjhollen** [comment]
Since the last activity on this post was a suggestion to close the issue in 2018, and the new UI for expanding the file drawer has been implemented, I'm going to close this issue. Thanks for reporting!
