### ISSUE TITLE
loopProtect error with for loop

### ISSUE THREAD

**Issue by kuprin5** [processing/p5.js-web-editor#633]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

- Web browser and version: Chrome 66.0.3359.139
- Operating System: MacOSX
- Steps to reproduce this:
When I start new simple project with for loop, sketch crush with error "Uncaught ReferenceError: loopProtect is not defined (sketch: line 7)". I try it on few computers and result is same. 

```
function setup() {
  createCanvas(400, 400);
}

function draw() {
  background(220);
  for (var i = 0; i < width; i++) {
    var gray = map(i, 0, width, 0, 255);
    stroke(gray);
    line(i, 0, i, height);
  }
}
```

**Comment by datramt** [comment]
you can fix this by putting:
```// noprotect ```
at the beginning of your code. You'll also want to make 'gray' a string

**Comment by kuprin5** [comment]
It's work. Thanks!

**Comment by jonathanprozzi** [comment]
I know this issue is closed, but our youth in our Creative Programming course also suddenly started experiencing this issue with for loops using var. 

I had them switch from using var to let in the for loop, and there was no longer an issue. I thought it may have something to do with the scope of the loop, so I had them try using _let_ for the iterator variable.

**Comment by catarak** [comment]
interesting! could you post the specific code? i recently changed how the loopProtect code gets injected into the code preview so it could have to do with that as well.

**Comment by jonathanprozzi** [comment]
Ahh gotcha! We were wondering why some of our youth started experiencing that error with their code. 

We had about 10 different youth experience it -- All were following the same code structure:

``` javascript 
function setup() {
  createCanvas(400, 400);
}

function draw() {
  var star = random(0, 255);
	background(40);
	for (var i = 0; i < 25; i++) {
		ellipse(star + i, star + i, 30, 30);
	}
}
```

**results in the error: Uncaught ReferenceError: loopProtect is not defined (sketch: line 8)**

Switching _var_ to _let_ in the for loop worked in every case:

``` javascript 
function setup() {
  createCanvas(400, 400);
}

function draw() {
  var star = random(0, 255);
	background(40);
	for (let i = 0; i < 25; i++) {
		ellipse(star + i, star + i, 30, 30);
	}
}
```

Thanks for the speedy response! Our youth started seeing this error last week, but I only now had one of our program staff send me a specific screenshot of it so that I could look into it.

We absolutely love using the web editor in our courses.
