### ISSUE TITLE
Long Files added to sketches appear empty 

### ISSUE THREAD

**Issue by aferriss** [processing/p5.js-web-editor#645]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

When I upload a JSON file that's sufficiently long (I'm not sure what the limit is), the file will appear empty when I navigate to it via the sidebar. I can even go into the file and start writing more json and it doesn't interfere with the original invisible json. I'm not sure if it's limited to JSON or not. I think one of my students tried this with a CSV file and saw something similar but I haven't tested again to confirm.

This only happens if I upload the whole file. If I create an empty json file, and paste in my text there's no issue. 

Sketch to demonstrate the bug below.

- Web browser and version: Chrome and Firefox
- Operating System: Mac OS 10.13.3
- Steps to reproduce this: http://alpha.editor.p5js.org/aferriss/sketches/BkJExEGlm

**Comment by catarak** [comment]
thanks for reporting this! this is basically a UI/UX bug. what's happening here is that the files are so big that they are being uploaded to S3, but the UX doesn't reflect that—it just appears that the files are empty. this is handled in the new design, but it would be nice to put something sooner so that it doesn't seem like a bug 😄

**Comment by catarak** [comment]
yeah this is super confusing! i added this issue to the current milestone so it should be fixed relatively soon.

**Comment by siddhant1** [comment]
Will take a look on this

**Comment by catarak** [comment]
just pushed a fix for this in #1102.
