### ISSUE TITLE
`windowHeight` is 30px too big using the editor

### ISSUE THREAD

**Issue by belgiancoder** [processing/p5.js-web-editor#680]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

`windowHeight` doesn't match the height of the window and is off by about 30px.

- Web browser and version: Safari 12.0 (14606.1.36.1.9) & Chrome
- Operating System:  MacOSX
- Steps to reproduce this:
use `createCanvas(windowWidth, windowHeight);` in the editor, it is 30px too big to fit the screen.
You can do `createCanvas(windowWidth-10, windowHeight-40);` to fix it but it is still a bug.
[Here is a test sketch you can use](https://editor.p5js.org/belgiancoder/sketches/BytOy7eu7), You should be able to see where the lines intersect.

<img width="1475" alt="screenshot 2018-09-07 at 18 29 22" src="https://user-images.githubusercontent.com/34147102/45231357-0adb0b00-b2cc-11e8-966c-0864c8192203.png">

#### New feature details:

Just correct the value of `windowWidth` and `windowHeight`. `windowWidth` is correct but it would be nicer if there was the same padding on both sides (10px).
Here is the expected result. 
<img width="1475" alt="screenshot 2018-09-07 at 18 32 29" src="https://user-images.githubusercontent.com/34147102/45231494-6c02de80-b2cc-11e8-83d0-ef015634099e.png">

#### Update: Chrome has this too.
<img width="1224" alt="screenshot 2018-09-07 at 18 53 38" src="https://user-images.githubusercontent.com/34147102/45232421-a02bce80-b2cf-11e8-93e7-4f3f9b4581e1.png">

**Comment by catarak** [comment]
i am able to reproduce! this is likely a bug with the CSS.

**Comment by bendman** [comment]
I've started looking into this one, and I think there are actually two issues here:

1. the `windowHeight` and `windowWidth` aren't reflecting the real window size, which adds scrollbars if you make a canvas that big

I'm not sure what's is causing this, but I think it's related to whitespace and line-height because making the canvas `display: block` fixes it.

2. even with scrollbars, the iframe is positioned to drop below the window so you can't see the bottom

This is because the iframe is set to be 100% height, but it's actually sharing that height with the header element that contains the "Preview" label.
