### ISSUE TITLE
Throws Errors When it Finds Keywords in Regex

### ISSUE THREAD

**Issue by Lukalotr** [processing/p5.js-web-editor#694]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 
Parser hangs or gets confused when it finds some language keywords inside a literal regular expression.
- p5.js version: 0.7.1
- Web browser and version: Google Chrome | 68.0.3440.106 (Official Build) (64-bit)
- Operating System: MacOSX 10.12.6
- Steps to reproduce this:
var x = /while/;
--> Uncaught SyntaxError: Unexpected token { (sketch: line 1)
var x = /for/;
--> Uncaught SyntaxError: Unexpected token { (sketch: line 1)

- Here is a temporary solution until the bug is fixed
var x = /whil\e/;

**Comment by catarak** [comment]
thanks for reporting this (somehow i missed this until now)! 

this is definitely because of the `loop-protect` library, which parses the the JS to find loop statements (e.g. `while`, `for`) and adds code to prevent infinite loops. it doesn't create an AST but just uses regular expressions to find these statements. i just tried this code on jsbin (which uses the updated `loop-protect` library), so i think this will be fixed by #698.

**Comment by Lukalotr** [comment]
Good to know, I was worried you wouldn’t ever see it 😄 Thanks alot!

**Comment by catarak** [comment]
i'm going to mark this as a duplicate and close it, for the sake of ticket organization, but this is not fixed yet, and will be fixed by #698.
