### ISSUE TITLE
bug in drawing arc

### ISSUE THREAD

**Issue by yonghuming** [processing/p5.js-web-editor#737]
#### Nature of issue?

- [x ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

- Web browser and version: chrome latest
- Operating System: windows10
- Steps to reproduce this:

![image](https://user-images.githubusercontent.com/435079/47255616-b1f3ba80-d4a6-11e8-9e74-154dfcd32d8b.png)
i want to demostrate how the stop parameter of arc() function work, bug it do not work properly.
as image shows
```
var arcStart = 0;
var arcStop = 0
var arcWidth = 0
var arcHeight = 0
function setup() {
  createCanvas(600, 600);
	strokeWeight(4);
	textSize(20);
	frameRate(4);
}

function draw() {
  background(220);
	push();
	translate(300,300);
  stroke(0)
  noFill()
  // arcStop = 20

  ellipse(0, 0, 440, 400)
    stroke(255,0,0)
  arcStop += 1
    arc(0, 0, 440, 400, radians(arcStart), radians(arcStop%360))
    
    var x = 220 * cos(radians(arcStop%360))
    var y = 200 * sin(radians(arcStop%360))
    stroke(0,0,255)
    line(0,0,220,0)
    
    stroke(255,0,0)
    line(0,0,x,y)
  // arcStop += 1
    
   
    fill(255,0,0);
  	strokeWeight(1);
    
    stroke(0,0,255)
    fill(0,0,255);
    text("start ",230,0)
    stroke(0)
    fill(0);
  text("stop: "+str(arcStop), x, y)
    text("arc(200, 200, 440, 400, radians("+str(arcStart)+"), radians("+str(arcStop%360)+")",-200,240)
	  strokeWeight(4);
    fill(0);
    pop();
}
```
the end of red line and arc should in same position , but something wrong

#### New feature details:

**Comment by yonghuming** [comment]
https://editor.p5js.org/yonghuming/sketches/Syz26udsX

**Comment by yonghuming** [comment]
but similar code in processing.py work well
![image](https://user-images.githubusercontent.com/435079/47255673-6ab9f980-d4a7-11e8-8f8a-ec552c6cb375.png)

```
def setup():
    size(600, 600)
    strokeWeight(4)
    textSize(20)
    frameRate(10)
arcStart = 0
arcStop = 0
def draw():
    global arcStart, arcStop
    background(200)

    pushMatrix()
    translate(300,300)
    stroke(0)
    noFill()
    ellipse(0, 0, 440, 200)
    stroke(255,0,0)
    arcStop += 1
    arc(0, 0, 440, 200, radians(arcStart), radians(arcStop%360))
  
    x = 220 * cos(radians(arcStop))
    y = 100 * sin(radians(arcStop))
    stroke(0,0,255)
    line(0,0,220,0)
    text("start ",230,0)
    stroke(255,0,0)
    line(0,0,x,y)
    text("stop: "+str(arcStop), x, y)
    print(arcStop)
    fill(0)
    text("arc(200, 200, 440, 400, radians("+str(arcStart)+"), radians("+str(arcStop%360)+")",-200,240)
    popMatrix()
    
    
    
    ```

**Comment by yonghuming** [comment]
![image](https://user-images.githubusercontent.com/435079/47255836-24fe3080-d4a9-11e8-9883-03572ab01830.png)

**Comment by catarak** [comment]
@yonghuming thanks for reporting! this repository is for reporting issues with the web editor, and not p5.js. it seems to me like you're reporting an error with p5.js, which would go [here](https://github.com/processing/p5.js/issues). 

However, I took a look at your code, and I think there's an error. If you look at your calculation for x and y
```js
var x = 220 * cos(radians(arcStop%360))
var y = 200 * sin(radians(arcStop%360))
```
Here, this assumes that the length of the hypotenuse of the triangle (because SOH CAH TOA) is 220 for x, and 200 for y. That doesn't seem right, it should be the same, right? 

Because this ellipse has a different width and height, the radius changes as it moves around the circle. So in this case, that hypotenuse value oscillates between 200 and 220. 

I recommend using the [Processing forum](https://discourse.processing.org/) if you're looking for coding help in the future!
