### ISSUE TITLE
Line of text causes chrome browser to go unresponsive

### ISSUE THREAD

**Issue by MysteryBag** [processing/p5.js-web-editor#744]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

Hi I'm new to programming and I'm currently learning JavaScript with p5 and was messing with different 'while' and 'for' loop statements and I found a line of code that causes the chrome browser tab that the web editor is open to go unresponsive on windows 10 when it is run.
No console errors show the page immediately goes unresponsive, refreshing the page doesn't work and you have to load a new editor in another tab.

- Web browser and version:  chrome
- Operating System:  windows 10
- Steps to reproduce this: 
run the code:
     while (mousePressed = true); 
<a href="https://gyazo.com/b221e5043671f84c1917312f7cca9bdc"><img src="https://i.gyazo.com/b221e5043671f84c1917312f7cca9bdc.png" alt="Image from Gyazo" width="1263"/></a>

**Comment by catarak** [comment]
thanks for reporting! this line of code creates an infinite loop. the online editor contains a library to catch infinite loops and prevent the page from crashing, however, the library needs to be updated (see #698). 

just fyi, there is an error here in how your code is structured. there are two things wrong here:
1. `mousePressed = true`: the `=` operator is for assignment, which means that this expression is actually assigning the value `true` to `mousePressed`. i don't think this is what you intended! The `===` operator is used to compare to values, so this should be `mousePressed === true`. If fact, since mousePressed is a Boolean, this could simply be `mousePressed`.
2. `while (mousePressed = true)` is preventing the draw loop from running. this is a bad thing, because this prevents the code in `draw()` from running 60 times a second and blocks the page from processing any user input. i would recommend using an `if` statement instead, checking the value of `mousePressed` every frame.

**Comment by MysteryBag** [comment]
Thanks for your detailed response and for explaining the difference between those two operator is used.

**Comment by catarak** [comment]
i'm going to close this as a duplicate under #698. when that ticket is fixed, this one will be!
