### ISSUE TITLE
userid is email when signed up with google

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-web-editor#760]
This is likely a duplicate of #655 but I thought I would file separately since there are other bugs discussed in that issue. At creative coding fest, we noticed that if a user signs up with their google account, their username is their e-mail. This is fine for logging in, but it ends up in the path of their sketch which is a privacy concern.

```
https://editor.p5js.org/emailaddress@gmail.com/sketches/#######
```

Perhaps there is a way we can allow a user to set a custom "user id" when logging in with google. (Note when logging in with GitHub it defaults to the GitHub username.)

**Comment by catarak** [comment]
thanks for reporting! yes, agreed, it would make sense for the username to not be an email address.

**Comment by catarak** [comment]
okay cool, thanks!

**Comment by LakshSingla** [comment]
@catarak I was finally able to setup Google OAuth for a local setup. Instead of using `email` as the value, we can use `displayName`(after formatting) as the user value. In case it is not present (generally in university emails where there is no point of hiding the email address), we can default to `email`.
This is a better alternative (and offers some protection) than naively showing private email address. If it is a viable solution, should I start working on it ?

**Comment by catarak** [comment]
i'm working on this now and trying to decide if using the `displayName` is enough. this works well for users with unique names (e.g. me) vs users that don't have unique names (e.g. i have a friend named `Will Smith`).

**Comment by catarak** [comment]
i'm thinking, instead, to just append a [friendly word](https://github.com/FogCreek/friendly-words) to the part of the email before the `@`.
