### ISSUE TITLE
Sorting sketches

### ISSUE THREAD

**Issue by CranShawdy** [processing/p5.js-web-editor#789]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### New feature details:

How about sorting sketches which are present in file/open/ via Sketch(name), Date created or Date updated values?

**Comment by catarak** [comment]
thanks for reporting, and great idea! i think this is covered in #390 but i think it also makes sense to break this out into its own ticket as you have done.

**Comment by GaurangTandon** [comment]
@catarak I can work on this issue. Can you please describe what files need to be edited? Also, do you have a UI in mind?

**Comment by siddhant1** [comment]
Is this still being worked at? @catarak can i take this one?

**Comment by GaurangTandon** [comment]
Yeah, @siddhant1 you can take this issue. Sorry I was unable to work on it.

**Comment by siddhant1** [comment]
Alright ! I will work on this one

**Comment by siddhant1** [comment]
@catarak @GaurangTandon  Can you have a look at https://github.com/siddhant1/p5.js-web-editor/tree/feature
I am not able to point at the problem , in my sense it should work .
Can you help me fix this

**Comment by siddhant1** [comment]
Fixed it ! Sending a PR soon

**Comment by siddhant1** [comment]
@GaurangTandon @catarak What icons should I use for carat symbol.
Should I include font-awesome?

**Comment by catarak** [comment]
in the design there's not currently a carat for the sorting; however, i do think that there should be one to the right of each heading. this project uses modern pictograms, so that's a good place to pull icons from. i'm thinking these icons for now:
<img width="98" alt="screen shot 2019-03-05 at 5 21 17 pm" src="https://user-images.githubusercontent.com/6063380/53841585-20737980-3f6b-11e9-9067-d1dd5c3f4f08.png">
modern pictograms is not free so i can send you those icons.

**Comment by siddhant1** [comment]
Yeah ! Please share them
