### ISSUE TITLE
Upgrade to React Router 5

### ISSUE THREAD

**Issue by siddhant1** [processing/p5.js-web-editor#857]
Upgrade to React Router 4 as it brings too many new things and performance improvements.
Links to migrate :- https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/migrating.md

I can work on it and send a PR @catarak

**Comment by catarak** [comment]
this would be great to upgrade!

**Comment by siddhant1** [comment]
Working !

**Comment by dewanshDT** [comment]
since the react version used here is `v16.12.0` and we've got **React Router 6** already we must upgrade to react router 6 instead of 5, is this still `priority:high`, if yes I would like to work on this.

Migrating from React Router 3 to React Router 6 may require some significant changes in the code, as there are many breaking API changes between these versions. Some of the main changes are:

- The use of `<BrowserRouter>` instead of `<Router>` for web applications.
- The use of `<Routes>` and `<Route>` components instead of `<Switch>` and `<Route>` for defining routes.
- The use of element prop instead of `component` or `render` prop for rendering components in routes.
- The use of `useNavigate` hook instead of `history` object for navigation.
- The use of `useParams` hook instead of `match.params` for accessing route parameters.

These are some of the major changes that are needed to be made when migrating from React Router 3 to React Router 6.
