### ISSUE TITLE
Accessibility for dyslexic users 

### ISSUE THREAD

**Issue by hellonearthis** [processing/p5.js-web-editor#883]
I was just reading this story about dyslexic fonts that could help some dyslexics.  http://www.serendavies.me/dyslexic-fonts/2016/01/04/dyslexic_fonts.html

Would it be worth having in the accessibility options the ability to use this font to help dyslexic users?

- New feature request

Feature enhancement would go into the editor configuration section with accessibility.

New feature details,  is basically a font change.

**Comment by siddhant1** [comment]
This improvement will be super helpful to make the editor accessible .
I would like to take this one up.

**Comment by catarak** [comment]
this is an interesting idea! i'd like to do some research about this first before adding it. following that link you posted, it points to some fonts that are dyslexic friendly, which i think would make more sense to consider rather than adding a whole new font option that it doesn't even seem like there's a consensus as to whether it's helpful or not.

**Comment by violetcraze** [comment]
Hey @catarak would be interested in working on this. Was thinking of adding [Open Dyslexic](https://www.opendyslexic.org/) (which has a mono spaced version) as an option in the accessibility panel.

Let me know what you think. Happy to do more research or just start working on it.

**Comment by catarak** [comment]
Thanks @violetcraze! I think this is an important issue and I'd like to approach it with care and thought before jumping to a solution. 

I think it would make sense to do some research to know if adding the option of a different font is helpful! There are options, and while it doesn't seem like there's a one size fits all solution for folks with dyslexia, maybe there are choices that a significant number of folks use.

Also someone made a PR for adding a new font (see #1295), which I closed since it was missing any research to show what is useful for dyslexic users.

**Comment by violetcraze** [comment]
Well I think it's good you suggested research. I read three articles written by programmers with dyslexia.

- [https://datacarpentry.org/blog/2017/09/coding-and-dyslexia](https://datacarpentry.org/blog/2017/09/coding-and-dyslexia)
- [https://medium.com/helpful-human/embracing-dyslexia-as-a-software-engineer-86419a94bd94](https://medium.com/helpful-human/embracing-dyslexia-as-a-software-engineer-86419a94bd94)
- [https://blog.bethcodes.com/the-dyslexic-programmer](https://blog.bethcodes.com/the-dyslexic-programmer)

I'm sure there's room for more research but I feel like I definitely have a much better picture now. The overwhelming conclusion I came to is that the best solution isn't a one size fits all option. But there are some common themes around configuration. My thoughts at this point are that we should focus on adding the following features.

- Syntax Highlighting. The web editor already has that YAY! Although there adding more coloring options beyond high contrast, light, and dark mode would allow for more fine tuning and might be beneficial for all not just people with dyslexia.
- Font Choice. A down menu with at least like 10 different fonts to choose from. One or more could be fonts designed for people with dyslexia but it seems like choice in general is more important. This is also something the Processing IDE does and it helps to cover cases where people are working in languages that use non-ascii characters which might not be supported by one font or another.
- Autocomplete / IntelliSense. I know we've talked about this in the past and someone was working on this for awhile but it seems like a must for some dyslexic coders because it removes some of the barrier to spelling / remembering syntax.

So much more to do that just adding a font but I think each of these things make the experience better for everyone. Would love to hear thoughts @catarak. Would still be interested in contributing on this front in some way.

**Comment by catarak** [comment]
Thank you @violetcraze! This is super helpful. It's also just helpful context in thinking about what features to prioritize within the web editor. There are lots of other browser-based code editors out there, and I think often about how to make the p5.js web editor it's own thing. I keep coming back to access (as accessibility and inclusion), and therefore I'd like to prioritize features that increase access, and it seems like everything you've listed fits that goal.

We could maybe break out some of the features you've listed into separate issues, but feel free to work on any that interest you!

**Comment by catarak** [comment]
I'm going through old issues, and just did some thinking about this one. From doing research again about dyslexic coders, it seems like the best fonts are in fact [Roman, Monospace, Sans-Serif](https://creativemarket.com/blog/is-comic-sans-easier-for-dyslexic-users-to-read), which Inconsolata actually ticks all of those boxes. It seems like the thing that would help dyslexic folks the most would be Autocomplete (#99)! Therefore I'm going to close this issue since it's captured in #99.
