### ISSUE TITLE
For unsaved projects/files, save them on running the sketch.

### ISSUE THREAD

**Issue by AnkurIngale** [processing/p5.js-web-editor#939]
#### Nature of issue?

- New feature request

#### Details: 
Many in-built IDEs have this feature that on running the code, it first saves it and then runs it. We can have such a feature in this IDE as well. 

#### Feature enhancement details:
We need to implement save actions on the run button as well. I'll have to dig more inorder to give a clear image of it.

And I will start working on it.
Views @catarak @siddhant1 @GaurangTandon ?

**Comment by GaurangTandon** [comment]
Since people are generally cautious of not losing unsaved work, they probably already save and run their sketch everytime. Thus, this feature will certainly help avoid redundant clicks of the run and save button every time. 

Also since the save operation doesn't generate revision histories and because it's not very expensive, I am sure it can be the default mode, aka, Run button can be renamed Save and Run.

Thoughts?

**Comment by siddhant1** [comment]
I researched a bit on this and found this .
1. You have to be logged in to save a sketch
2.Saving a sketch will generate a shareable url 

This isn't beneficial for someone who is just coming to come for the first time and as soon as he hits play we are asking him/her to login. 
So I think we have the best solution to not save and run .

Still let's keep this issue open and let @catarak decide.

**Comment by AnkurIngale** [comment]
@siddhant1 yes you are right. What we can implement is save and run on logging in and just run when not logged in.

**Comment by catarak** [comment]
would it make sense to just make the autosave interval smaller? i think this is perhaps an overcomplicated solution.

**Comment by catarak** [comment]
Going to roll this issue into #1635!
