### ISSUE TITLE
Remove Nav item border on clicking it.

### ISSUE THREAD

**Issue by AnkurIngale** [processing/p5.js-web-editor#998]
#### Nature of issue?

- Found a bug

#### Details about the bug: 
If I open a nav item, say Sketch, and hover over Edit, it opens the options in Edit but the border still remains on Sketch. Also, on clicking any other nav item again, options shut down.
- Web browser and version:  On Chrome
- Operating System: MacOSX
- Steps to reproduce this bug:
Do as above.

Anybody can work on it. @catarak reviews?

**Comment by catarak** [comment]
thanks for reporting! i wonder what best practice is here, whether it's okay to programmatically change the focus like that, and how it affects keyboard users/screen readers.

**Comment by AnkurIngale** [comment]
* When tabbing through the nav items, if some nav is open, I have to press enter twice to open my desired nav.
* I believe, hovering should be removed for the time being. Opening a single nav would be preferable. Just making sure that one click opens the desired nav and closes any other opened nav.

**Comment by siddhant1** [comment]
I also think on tabbing or moving across the menus should focus them

**Comment by siddhant1** [comment]
Interestingly google docs close dropdown on tab.

**Comment by catarak** [comment]
i think that we should follow this method: https://staff.washington.edu/tft/tests/menus/html5/index.html

...which i think the nav is actually doing, except using the `tab` key to get through the menu items, rather than the arrow keys (which i _think_ is better). you'll notice that when you click on the menu, and then hover onto another one, the focus stays on the first one.

**Comment by AnkurIngale** [comment]
Which is exactly the behaviour right now. Cool then we will keep this.
